# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchSearcher.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchSearcher(object):
    def setupUi(self, BatchSearcher):
        BatchSearcher.setObjectName("BatchSearcher")
        BatchSearcher.resize(322, 112)
        self.widget = QtWidgets.QWidget(BatchSearcher)
        self.widget.setGeometry(QtCore.QRect(10, 10, 302, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblStartDate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.horizontalLayout.addWidget(self.lblStartDate)
        self.dteStartDate = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dteStartDate.setFont(font)
        self.dteStartDate.setObjectName("dteStartDate")
        self.horizontalLayout.addWidget(self.dteStartDate)
        self.lblEndDate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblEndDate.setFont(font)
        self.lblEndDate.setObjectName("lblEndDate")
        self.horizontalLayout.addWidget(self.lblEndDate)
        self.dteEndDate = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dteEndDate.setFont(font)
        self.dteEndDate.setObjectName("dteEndDate")
        self.horizontalLayout.addWidget(self.dteEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblInterval = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInterval.setFont(font)
        self.lblInterval.setObjectName("lblInterval")
        self.horizontalLayout_2.addWidget(self.lblInterval)
        self.spbInterval = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbInterval.setFont(font)
        self.spbInterval.setPrefix("")
        self.spbInterval.setMinimum(1)
        self.spbInterval.setMaximum(10)
        self.spbInterval.setObjectName("spbInterval")
        self.horizontalLayout_2.addWidget(self.spbInterval)
        self.cbbIntervalType = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.cbbIntervalType.setFont(font)
        self.cbbIntervalType.setObjectName("cbbIntervalType")
        self.horizontalLayout_2.addWidget(self.cbbIntervalType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblCriteriaName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblCriteriaName.setFont(font)
        self.lblCriteriaName.setObjectName("lblCriteriaName")
        self.horizontalLayout_3.addWidget(self.lblCriteriaName)
        self.iptCriteriaName = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.iptCriteriaName.setFont(font)
        self.iptCriteriaName.setObjectName("iptCriteriaName")
        self.horizontalLayout_3.addWidget(self.iptCriteriaName)
        self.btnStartSearch = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.btnStartSearch.setFont(font)
        self.btnStartSearch.setObjectName("btnStartSearch")
        self.horizontalLayout_3.addWidget(self.btnStartSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(BatchSearcher)
        self.btnStartSearch.clicked.connect(BatchSearcher.start_searching)
        QtCore.QMetaObject.connectSlotsByName(BatchSearcher)

    def retranslateUi(self, BatchSearcher):
        _translate = QtCore.QCoreApplication.translate
        BatchSearcher.setWindowTitle(_translate("BatchSearcher", "批量选股"))
        self.lblStartDate.setText(_translate("BatchSearcher", "开始日期"))
        self.dteStartDate.setDisplayFormat(_translate("BatchSearcher", "yyyy-MM-dd"))
        self.lblEndDate.setText(_translate("BatchSearcher", "结束日期"))
        self.dteEndDate.setDisplayFormat(_translate("BatchSearcher", "yyyy-MM-dd"))
        self.lblInterval.setText(_translate("BatchSearcher", "选股间隔"))
        self.lblCriteriaName.setText(_translate("BatchSearcher", "选股条件名称"))
        self.btnStartSearch.setText(_translate("BatchSearcher", "开始选股"))
