# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FiveDaysFinder.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FiveDayShapeFinder(object):
    def setupUi(self, FiveDayShapeFinder):
        FiveDayShapeFinder.setObjectName("FiveDayShapeFinder")
        FiveDayShapeFinder.resize(451, 311)
        self.layoutWidget = QtWidgets.QWidget(FiveDayShapeFinder)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 287))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstCriteriaItems = QtWidgets.QListWidget(self.layoutWidget)
        self.lstCriteriaItems.setObjectName("lstCriteriaItems")
        self.verticalLayout.addWidget(self.lstCriteriaItems)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnRemoveCriteria = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRemoveCriteria.setObjectName("btnRemoveCriteria")
        self.horizontalLayout_11.addWidget(self.btnRemoveCriteria)
        self.btnResetCriteria = QtWidgets.QPushButton(self.layoutWidget)
        self.btnResetCriteria.setObjectName("btnResetCriteria")
        self.horizontalLayout_11.addWidget(self.btnResetCriteria)
        self.btnExportConfig = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportConfig.setFont(font)
        self.btnExportConfig.setObjectName("btnExportConfig")
        self.horizontalLayout_11.addWidget(self.btnExportConfig)
        self.btnImportConfig = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportConfig.setFont(font)
        self.btnImportConfig.setObjectName("btnImportConfig")
        self.horizontalLayout_11.addWidget(self.btnImportConfig)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spbDayIndex = QtWidgets.QSpinBox(self.layoutWidget)
        self.spbDayIndex.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDayIndex.setFont(font)
        self.spbDayIndex.setMinimum(1)
        self.spbDayIndex.setMaximum(5)
        self.spbDayIndex.setProperty("value", 1)
        self.spbDayIndex.setObjectName("spbDayIndex")
        self.horizontalLayout.addWidget(self.spbDayIndex)
        self.cbbQueryField = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbQueryField.setFont(font)
        self.cbbQueryField.setObjectName("cbbQueryField")
        self.horizontalLayout.addWidget(self.cbbQueryField)
        self.rbnGreaterThan = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnGreaterThan.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rbnGreaterThan.setChecked(True)
        self.rbnGreaterThan.setAutoExclusive(True)
        self.rbnGreaterThan.setObjectName("rbnGreaterThan")
        self.grpOperators = QtWidgets.QButtonGroup(FiveDayShapeFinder)
        self.grpOperators.setObjectName("grpOperators")
        self.grpOperators.addButton(self.rbnGreaterThan)
        self.horizontalLayout.addWidget(self.rbnGreaterThan)
        self.rbnLessThan = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnLessThan.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rbnLessThan.setChecked(False)
        self.rbnLessThan.setObjectName("rbnLessThan")
        self.grpOperators.addButton(self.rbnLessThan)
        self.horizontalLayout.addWidget(self.rbnLessThan)
        self.spbCriteriaValue = QtWidgets.QSpinBox(self.layoutWidget)
        self.spbCriteriaValue.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbCriteriaValue.setFont(font)
        self.spbCriteriaValue.setPrefix("")
        self.spbCriteriaValue.setMinimum(-100)
        self.spbCriteriaValue.setMaximum(100)
        self.spbCriteriaValue.setProperty("value", 0)
        self.spbCriteriaValue.setDisplayIntegerBase(10)
        self.spbCriteriaValue.setObjectName("spbCriteriaValue")
        self.horizontalLayout.addWidget(self.spbCriteriaValue)
        self.btnSaveCriteria = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSaveCriteria.setObjectName("btnSaveCriteria")
        self.horizontalLayout.addWidget(self.btnSaveCriteria)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.rbnSingleStock = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnSingleStock.setChecked(True)
        self.rbnSingleStock.setObjectName("rbnSingleStock")
        self.grpSearchMode = QtWidgets.QButtonGroup(FiveDayShapeFinder)
        self.grpSearchMode.setObjectName("grpSearchMode")
        self.grpSearchMode.addButton(self.rbnSingleStock)
        self.horizontalLayout_21.addWidget(self.rbnSingleStock)
        self.iptStockCode = QtWidgets.QLineEdit(self.layoutWidget)
        self.iptStockCode.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout_21.addWidget(self.iptStockCode)
        self.rbnAllStocks = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnAllStocks.setObjectName("rbnAllStocks")
        self.grpSearchMode.addButton(self.rbnAllStocks)
        self.horizontalLayout_21.addWidget(self.rbnAllStocks)
        self.btnStartSearching = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnStartSearching.setFont(font)
        self.btnStartSearching.setObjectName("btnStartSearching")
        self.horizontalLayout_21.addWidget(self.btnStartSearching)
        self.verticalLayout.addLayout(self.horizontalLayout_21)

        self.retranslateUi(FiveDayShapeFinder)
        self.rbnSingleStock.toggled['bool'].connect(self.iptStockCode.setEnabled)
        self.btnRemoveCriteria.clicked.connect(FiveDayShapeFinder.remove_criteria)
        self.btnResetCriteria.clicked.connect(FiveDayShapeFinder.clear_criterias)
        self.btnExportConfig.clicked.connect(FiveDayShapeFinder.export_config)
        self.btnImportConfig.clicked.connect(FiveDayShapeFinder.import_config)
        self.btnSaveCriteria.clicked.connect(FiveDayShapeFinder.save_criteria)
        self.btnStartSearching.clicked.connect(FiveDayShapeFinder.start_searching)
        self.lstCriteriaItems.itemDoubleClicked['QListWidgetItem*'].connect(FiveDayShapeFinder.edit_criteria)
        self.lstCriteriaItems.itemClicked['QListWidgetItem*'].connect(FiveDayShapeFinder.select_criteria)
        QtCore.QMetaObject.connectSlotsByName(FiveDayShapeFinder)

    def retranslateUi(self, FiveDayShapeFinder):
        _translate = QtCore.QCoreApplication.translate
        FiveDayShapeFinder.setWindowTitle(_translate("FiveDayShapeFinder", "五日图形选股"))
        self.btnRemoveCriteria.setText(_translate("FiveDayShapeFinder", "删除"))
        self.btnResetCriteria.setText(_translate("FiveDayShapeFinder", "清空"))
        self.btnExportConfig.setText(_translate("FiveDayShapeFinder", "导出"))
        self.btnImportConfig.setText(_translate("FiveDayShapeFinder", "导入"))
        self.spbDayIndex.setSuffix(_translate("FiveDayShapeFinder", "日"))
        self.spbDayIndex.setPrefix(_translate("FiveDayShapeFinder", "第"))
        self.rbnGreaterThan.setText(_translate("FiveDayShapeFinder", "大于"))
        self.rbnLessThan.setText(_translate("FiveDayShapeFinder", "小于"))
        self.spbCriteriaValue.setSuffix(_translate("FiveDayShapeFinder", "%"))
        self.btnSaveCriteria.setText(_translate("FiveDayShapeFinder", "保存 / 添加"))
        self.rbnSingleStock.setText(_translate("FiveDayShapeFinder", "单只股票"))
        self.iptStockCode.setText(_translate("FiveDayShapeFinder", "贵州茅台"))
        self.rbnAllStocks.setText(_translate("FiveDayShapeFinder", "全部股票"))
        self.btnStartSearching.setText(_translate("FiveDayShapeFinder", "开始寻找"))
