# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FiveDaysFinder.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FiveDayShapeFinder(object):
    def setupUi(self, FiveDayShapeFinder):
        FiveDayShapeFinder.setObjectName("FiveDayShapeFinder")
        FiveDayShapeFinder.resize(501, 311)
        self.widget = QtWidgets.QWidget(FiveDayShapeFinder)
        self.widget.setGeometry(QtCore.QRect(10, 10, 479, 287))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstCriteriaItems = QtWidgets.QListWidget(self.widget)
        self.lstCriteriaItems.setObjectName("lstCriteriaItems")
        self.verticalLayout.addWidget(self.lstCriteriaItems)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnAddCriteria = QtWidgets.QPushButton(self.widget)
        self.btnAddCriteria.setObjectName("btnAddCriteria")
        self.horizontalLayout_11.addWidget(self.btnAddCriteria)
        self.btnRemoveCriteria = QtWidgets.QPushButton(self.widget)
        self.btnRemoveCriteria.setObjectName("btnRemoveCriteria")
        self.horizontalLayout_11.addWidget(self.btnRemoveCriteria)
        self.btnEditCriteria = QtWidgets.QPushButton(self.widget)
        self.btnEditCriteria.setObjectName("btnEditCriteria")
        self.horizontalLayout_11.addWidget(self.btnEditCriteria)
        self.btnResetCriteria = QtWidgets.QPushButton(self.widget)
        self.btnResetCriteria.setObjectName("btnResetCriteria")
        self.horizontalLayout_11.addWidget(self.btnResetCriteria)
        self.btnExportConfig = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportConfig.setFont(font)
        self.btnExportConfig.setObjectName("btnExportConfig")
        self.horizontalLayout_11.addWidget(self.btnExportConfig)
        self.btnImportConfig = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportConfig.setFont(font)
        self.btnImportConfig.setObjectName("btnImportConfig")
        self.horizontalLayout_11.addWidget(self.btnImportConfig)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spbQueryPeriodBegin = QtWidgets.QSpinBox(self.widget)
        self.spbQueryPeriodBegin.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbQueryPeriodBegin.setFont(font)
        self.spbQueryPeriodBegin.setMinimum(1)
        self.spbQueryPeriodBegin.setMaximum(5)
        self.spbQueryPeriodBegin.setProperty("value", 1)
        self.spbQueryPeriodBegin.setObjectName("spbQueryPeriodBegin")
        self.horizontalLayout.addWidget(self.spbQueryPeriodBegin)
        self.cbbQueryField = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbQueryField.setFont(font)
        self.cbbQueryField.setObjectName("cbbQueryField")
        self.horizontalLayout.addWidget(self.cbbQueryField)
        self.spbValueMin = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbValueMin.setFont(font)
        self.spbValueMin.setMinimum(-100)
        self.spbValueMin.setMaximum(100)
        self.spbValueMin.setProperty("value", -2)
        self.spbValueMin.setDisplayIntegerBase(10)
        self.spbValueMin.setObjectName("spbValueMin")
        self.horizontalLayout.addWidget(self.spbValueMin)
        self.spbValueMax = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbValueMax.setFont(font)
        self.spbValueMax.setMinimum(-100)
        self.spbValueMax.setMaximum(100)
        self.spbValueMax.setProperty("value", 2)
        self.spbValueMax.setDisplayIntegerBase(10)
        self.spbValueMax.setObjectName("spbValueMax")
        self.horizontalLayout.addWidget(self.spbValueMax)
        self.btnSaveCriteria = QtWidgets.QPushButton(self.widget)
        self.btnSaveCriteria.setObjectName("btnSaveCriteria")
        self.horizontalLayout.addWidget(self.btnSaveCriteria)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.rbnSingleStock = QtWidgets.QRadioButton(self.widget)
        self.rbnSingleStock.setChecked(True)
        self.rbnSingleStock.setObjectName("rbnSingleStock")
        self.horizontalLayout_21.addWidget(self.rbnSingleStock)
        self.iptStockCode = QtWidgets.QLineEdit(self.widget)
        self.iptStockCode.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout_21.addWidget(self.iptStockCode)
        self.rbnAllStocks = QtWidgets.QRadioButton(self.widget)
        self.rbnAllStocks.setObjectName("rbnAllStocks")
        self.horizontalLayout_21.addWidget(self.rbnAllStocks)
        self.btnStartSearching = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnStartSearching.setFont(font)
        self.btnStartSearching.setObjectName("btnStartSearching")
        self.horizontalLayout_21.addWidget(self.btnStartSearching)
        self.verticalLayout.addLayout(self.horizontalLayout_21)

        self.retranslateUi(FiveDayShapeFinder)
        self.rbnSingleStock.toggled['bool'].connect(self.iptStockCode.setEnabled)
        self.btnAddCriteria.clicked.connect(FiveDayShapeFinder.add_criteria)
        self.btnRemoveCriteria.clicked.connect(FiveDayShapeFinder.remove_criteria)
        self.btnEditCriteria.clicked.connect(FiveDayShapeFinder.edit_criteria)
        self.btnResetCriteria.clicked.connect(FiveDayShapeFinder.clear_criterias)
        self.btnExportConfig.clicked.connect(FiveDayShapeFinder.export_config)
        self.btnImportConfig.clicked.connect(FiveDayShapeFinder.import_config)
        self.btnSaveCriteria.clicked.connect(FiveDayShapeFinder.save_criteria)
        self.btnStartSearching.clicked.connect(FiveDayShapeFinder.start_searching)
        QtCore.QMetaObject.connectSlotsByName(FiveDayShapeFinder)

    def retranslateUi(self, FiveDayShapeFinder):
        _translate = QtCore.QCoreApplication.translate
        FiveDayShapeFinder.setWindowTitle(_translate("FiveDayShapeFinder", "五日图形选股"))
        self.btnAddCriteria.setText(_translate("FiveDayShapeFinder", "添加"))
        self.btnRemoveCriteria.setText(_translate("FiveDayShapeFinder", "删除"))
        self.btnEditCriteria.setText(_translate("FiveDayShapeFinder", "编辑"))
        self.btnResetCriteria.setText(_translate("FiveDayShapeFinder", "清空"))
        self.btnExportConfig.setText(_translate("FiveDayShapeFinder", "导出"))
        self.btnImportConfig.setText(_translate("FiveDayShapeFinder", "导入"))
        self.spbQueryPeriodBegin.setSuffix(_translate("FiveDayShapeFinder", "日"))
        self.spbQueryPeriodBegin.setPrefix(_translate("FiveDayShapeFinder", "第"))
        self.spbValueMin.setSuffix(_translate("FiveDayShapeFinder", "%"))
        self.spbValueMin.setPrefix(_translate("FiveDayShapeFinder", "最低"))
        self.spbValueMax.setSuffix(_translate("FiveDayShapeFinder", "%"))
        self.spbValueMax.setPrefix(_translate("FiveDayShapeFinder", "最高"))
        self.btnSaveCriteria.setText(_translate("FiveDayShapeFinder", "保存"))
        self.rbnSingleStock.setText(_translate("FiveDayShapeFinder", "单只股票"))
        self.iptStockCode.setText(_translate("FiveDayShapeFinder", "贵州茅台"))
        self.rbnAllStocks.setText(_translate("FiveDayShapeFinder", "全部股票"))
        self.btnStartSearching.setText(_translate("FiveDayShapeFinder", "开始寻找"))
