# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveTracker.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LiveTracker(object):
    def setupUi(self, LiveTracker):
        LiveTracker.setObjectName("LiveTracker")
        LiveTracker.resize(715, 564)
        self.centralwidget = QtWidgets.QWidget(LiveTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnImportStockList = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportStockList.setFont(font)
        self.btnImportStockList.setObjectName("btnImportStockList")
        self.horizontalLayout.addWidget(self.btnImportStockList)
        self.btnExportStockList = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportStockList.setFont(font)
        self.btnExportStockList.setObjectName("btnExportStockList")
        self.horizontalLayout.addWidget(self.btnExportStockList)
        self.lblNewStockCode = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lblNewStockCode.setFont(font)
        self.lblNewStockCode.setObjectName("lblNewStockCode")
        self.horizontalLayout.addWidget(self.lblNewStockCode)
        self.iptStockCode = QtWidgets.QLineEdit(self.centralwidget)
        self.iptStockCode.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout.addWidget(self.iptStockCode)
        self.btnAddStock = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnAddStock.setFont(font)
        self.btnAddStock.setObjectName("btnAddStock")
        self.horizontalLayout.addWidget(self.btnAddStock)
        self.btnRemoveStock = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnRemoveStock.setFont(font)
        self.btnRemoveStock.setObjectName("btnRemoveStock")
        self.horizontalLayout.addWidget(self.btnRemoveStock)
        self.btnClearStocks = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnClearStocks.setFont(font)
        self.btnClearStocks.setObjectName("btnClearStocks")
        self.horizontalLayout.addWidget(self.btnClearStocks)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblLastUpdateTime = QtWidgets.QLabel(self.centralwidget)
        self.lblLastUpdateTime.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lblLastUpdateTime.setFont(font)
        self.lblLastUpdateTime.setObjectName("lblLastUpdateTime")
        self.horizontalLayout_2.addWidget(self.lblLastUpdateTime)
        self.lblUpdateFrequency = QtWidgets.QLabel(self.centralwidget)
        self.lblUpdateFrequency.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lblUpdateFrequency.setFont(font)
        self.lblUpdateFrequency.setObjectName("lblUpdateFrequency")
        self.horizontalLayout_2.addWidget(self.lblUpdateFrequency)
        self.spbUpdateFrequency = QtWidgets.QSpinBox(self.centralwidget)
        self.spbUpdateFrequency.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbUpdateFrequency.setFont(font)
        self.spbUpdateFrequency.setMinimum(1)
        self.spbUpdateFrequency.setMaximum(10)
        self.spbUpdateFrequency.setProperty("value", 2)
        self.spbUpdateFrequency.setObjectName("spbUpdateFrequency")
        self.horizontalLayout_2.addWidget(self.spbUpdateFrequency)
        self.lblRecentMeasurement = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lblRecentMeasurement.setFont(font)
        self.lblRecentMeasurement.setObjectName("lblRecentMeasurement")
        self.horizontalLayout_2.addWidget(self.lblRecentMeasurement)
        self.spbRecentMeasureCount = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbRecentMeasureCount.setFont(font)
        self.spbRecentMeasureCount.setSuffix("")
        self.spbRecentMeasureCount.setMinimum(1)
        self.spbRecentMeasureCount.setMaximum(10)
        self.spbRecentMeasureCount.setProperty("value", 5)
        self.spbRecentMeasureCount.setObjectName("spbRecentMeasureCount")
        self.horizontalLayout_2.addWidget(self.spbRecentMeasureCount)
        self.cbbRecentMeasurement = QtWidgets.QComboBox(self.centralwidget)
        self.cbbRecentMeasurement.setObjectName("cbbRecentMeasurement")
        self.horizontalLayout_2.addWidget(self.cbbRecentMeasurement)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tblStockList = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.tblStockList.setFont(font)
        self.tblStockList.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblStockList.setRowCount(0)
        self.tblStockList.setObjectName("tblStockList")
        self.tblStockList.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(8, item)
        self.tblStockList.horizontalHeader().setDefaultSectionSize(75)
        self.tblStockList.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout.addWidget(self.tblStockList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblMonitorConditions = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lblMonitorConditions.setFont(font)
        self.lblMonitorConditions.setObjectName("lblMonitorConditions")
        self.horizontalLayout_4.addWidget(self.lblMonitorConditions)
        self.btnAddCondition = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnAddCondition.setFont(font)
        self.btnAddCondition.setObjectName("btnAddCondition")
        self.horizontalLayout_4.addWidget(self.btnAddCondition)
        self.btnDeleteCondition = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnDeleteCondition.setFont(font)
        self.btnDeleteCondition.setObjectName("btnDeleteCondition")
        self.horizontalLayout_4.addWidget(self.btnDeleteCondition)
        self.btnEditCondition = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnEditCondition.setFont(font)
        self.btnEditCondition.setObjectName("btnEditCondition")
        self.horizontalLayout_4.addWidget(self.btnEditCondition)
        self.btnImportMonitorConditions = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportMonitorConditions.setFont(font)
        self.btnImportMonitorConditions.setObjectName("btnImportMonitorConditions")
        self.horizontalLayout_4.addWidget(self.btnImportMonitorConditions)
        self.btnImportGenericConditions = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportGenericConditions.setFont(font)
        self.btnImportGenericConditions.setObjectName("btnImportGenericConditions")
        self.horizontalLayout_4.addWidget(self.btnImportGenericConditions)
        self.btnExportMonitorConditions = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportMonitorConditions.setFont(font)
        self.btnExportMonitorConditions.setObjectName("btnExportMonitorConditions")
        self.horizontalLayout_4.addWidget(self.btnExportMonitorConditions)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.trwMonitorConditions = QtWidgets.QTreeWidget(self.centralwidget)
        self.trwMonitorConditions.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.trwMonitorConditions.setObjectName("trwMonitorConditions")
        self.trwMonitorConditions.header().setDefaultSectionSize(150)
        self.trwMonitorConditions.header().setMinimumSectionSize(150)
        self.verticalLayout.addWidget(self.trwMonitorConditions)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStartTracking = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartTracking.setFont(font)
        self.btnStartTracking.setObjectName("btnStartTracking")
        self.horizontalLayout_3.addWidget(self.btnStartTracking)
        self.btnStopTracking = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnStopTracking.setFont(font)
        self.btnStopTracking.setObjectName("btnStopTracking")
        self.horizontalLayout_3.addWidget(self.btnStopTracking)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        LiveTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LiveTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        LiveTracker.setMenuBar(self.menubar)
        self.MaxStockWatcher = QtWidgets.QAction(LiveTracker)
        self.MaxStockWatcher.setObjectName("MaxStockWatcher")
        self.MinStockWatcher = QtWidgets.QAction(LiveTracker)
        self.MinStockWatcher.setObjectName("MinStockWatcher")
        self.menu.addAction(self.MaxStockWatcher)
        self.menu.addAction(self.MinStockWatcher)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(LiveTracker)
        self.btnImportStockList.clicked.connect(LiveTracker.import_stock_list)
        self.btnAddStock.clicked.connect(LiveTracker.add_stock_code)
        self.btnRemoveStock.clicked.connect(LiveTracker.remove_stock_code)
        self.btnClearStocks.clicked.connect(LiveTracker.clear_stock_list)
        self.btnStartTracking.clicked.connect(LiveTracker.start_monitoring)
        self.btnStopTracking.clicked.connect(LiveTracker.stop_monitoring)
        self.btnAddCondition.clicked.connect(LiveTracker.add_condition)
        self.btnDeleteCondition.clicked.connect(LiveTracker.delete_condition)
        self.btnExportStockList.clicked.connect(LiveTracker.export_stock_list)
        self.btnImportMonitorConditions.clicked.connect(LiveTracker.import_conditions)
        self.btnExportMonitorConditions.clicked.connect(LiveTracker.export_conditions)
        self.tblStockList.cellDoubleClicked['int','int'].connect(LiveTracker.open_stock_page)
        self.btnEditCondition.clicked.connect(LiveTracker.edit_condition)
        self.trwMonitorConditions.itemDoubleClicked['QTreeWidgetItem*','int'].connect(LiveTracker.edit_monitor_condition)
        self.btnImportGenericConditions.clicked.connect(LiveTracker.import_generic_conditions)
        QtCore.QMetaObject.connectSlotsByName(LiveTracker)

    def retranslateUi(self, LiveTracker):
        _translate = QtCore.QCoreApplication.translate
        LiveTracker.setWindowTitle(_translate("LiveTracker", "实时盯盘助手"))
        self.btnImportStockList.setText(_translate("LiveTracker", "导入股票列表"))
        self.btnExportStockList.setText(_translate("LiveTracker", "导出股票列表"))
        self.lblNewStockCode.setText(_translate("LiveTracker", "股票代码/名称"))
        self.iptStockCode.setText(_translate("LiveTracker", "贵州茅台"))
        self.btnAddStock.setText(_translate("LiveTracker", "添加股票"))
        self.btnRemoveStock.setText(_translate("LiveTracker", "删除股票"))
        self.btnClearStocks.setText(_translate("LiveTracker", "清空列表"))
        self.lblLastUpdateTime.setText(_translate("LiveTracker", "上次刷新："))
        self.lblUpdateFrequency.setText(_translate("LiveTracker", "刷新频率："))
        self.spbUpdateFrequency.setSuffix(_translate("LiveTracker", "秒"))
        self.spbUpdateFrequency.setPrefix(_translate("LiveTracker", "每"))
        self.lblRecentMeasurement.setText(_translate("LiveTracker", "短时数据来源："))
        item = self.tblStockList.horizontalHeaderItem(0)
        item.setText(_translate("LiveTracker", "代码"))
        item = self.tblStockList.horizontalHeaderItem(1)
        item.setText(_translate("LiveTracker", "名称"))
        item = self.tblStockList.horizontalHeaderItem(2)
        item.setText(_translate("LiveTracker", "最新成交"))
        item = self.tblStockList.horizontalHeaderItem(3)
        item.setText(_translate("LiveTracker", "价格"))
        item = self.tblStockList.horizontalHeaderItem(4)
        item.setText(_translate("LiveTracker", "涨跌幅"))
        item = self.tblStockList.horizontalHeaderItem(5)
        item.setText(_translate("LiveTracker", "五档委比"))
        item = self.tblStockList.horizontalHeaderItem(6)
        item.setText(_translate("LiveTracker", "最近涨跌"))
        item = self.tblStockList.horizontalHeaderItem(7)
        item.setText(_translate("LiveTracker", "外盘比例"))
        item = self.tblStockList.horizontalHeaderItem(8)
        item.setText(_translate("LiveTracker", "成交额"))
        self.lblMonitorConditions.setText(_translate("LiveTracker", "盯盘指标设置"))
        self.btnAddCondition.setText(_translate("LiveTracker", "添加"))
        self.btnDeleteCondition.setText(_translate("LiveTracker", "删除"))
        self.btnEditCondition.setText(_translate("LiveTracker", "编辑"))
        self.btnImportMonitorConditions.setText(_translate("LiveTracker", "导入单个"))
        self.btnImportGenericConditions.setText(_translate("LiveTracker", "导入通用"))
        self.btnExportMonitorConditions.setText(_translate("LiveTracker", "导出"))
        self.trwMonitorConditions.headerItem().setText(0, _translate("LiveTracker", "股票名称"))
        self.trwMonitorConditions.headerItem().setText(1, _translate("LiveTracker", "监控指标"))
        self.trwMonitorConditions.headerItem().setText(2, _translate("LiveTracker", "触发数值"))
        self.trwMonitorConditions.headerItem().setText(3, _translate("LiveTracker", "冷却时间（分钟）"))
        self.btnStartTracking.setText(_translate("LiveTracker", "开始盯盘"))
        self.btnStopTracking.setText(_translate("LiveTracker", "停止盯盘"))
        self.menu.setTitle(_translate("LiveTracker", "打板神器"))
        self.MaxStockWatcher.setText(_translate("LiveTracker", "涨停板"))
        self.MinStockWatcher.setText(_translate("LiveTracker", "跌停板"))
