# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveTracker.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LiveTracker(object):
    def setupUi(self, LiveTracker):
        LiveTracker.setObjectName("LiveTracker")
        LiveTracker.resize(715, 478)
        self.centralwidget = QtWidgets.QWidget(LiveTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.tblStockList = QtWidgets.QTableWidget(self.centralwidget)
        self.tblStockList.setGeometry(QtCore.QRect(10, 80, 691, 192))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tblStockList.setFont(font)
        self.tblStockList.setObjectName("tblStockList")
        self.tblStockList.setColumnCount(9)
        self.tblStockList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(8, item)
        self.tblStockList.horizontalHeader().setDefaultSectionSize(75)
        self.tblStockList.verticalHeader().setDefaultSectionSize(25)
        self.grpEventSignal = QtWidgets.QGroupBox(self.centralwidget)
        self.grpEventSignal.setGeometry(QtCore.QRect(10, 280, 691, 141))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.grpEventSignal.setFont(font)
        self.grpEventSignal.setObjectName("grpEventSignal")
        self.layoutWidget = QtWidgets.QWidget(self.grpEventSignal)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 671, 120))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblRecentMeasurement = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblRecentMeasurement.setFont(font)
        self.lblRecentMeasurement.setObjectName("lblRecentMeasurement")
        self.horizontalLayout_4.addWidget(self.lblRecentMeasurement)
        self.spbRecentMeasureCount = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbRecentMeasureCount.setFont(font)
        self.spbRecentMeasureCount.setSuffix("")
        self.spbRecentMeasureCount.setMinimum(1)
        self.spbRecentMeasureCount.setMaximum(10)
        self.spbRecentMeasureCount.setProperty("value", 5)
        self.spbRecentMeasureCount.setObjectName("spbRecentMeasureCount")
        self.horizontalLayout_4.addWidget(self.spbRecentMeasureCount)
        self.cbbRecentMeasurement = QtWidgets.QComboBox(self.layoutWidget)
        self.cbbRecentMeasurement.setObjectName("cbbRecentMeasurement")
        self.horizontalLayout_4.addWidget(self.cbbRecentMeasurement)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxDailyUpPercent = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxDailyUpPercent.setFont(font)
        self.cbxDailyUpPercent.setChecked(True)
        self.cbxDailyUpPercent.setObjectName("cbxDailyUpPercent")
        self.horizontalLayout_3.addWidget(self.cbxDailyUpPercent)
        self.spbDailyPercentChange = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbDailyPercentChange.setFont(font)
        self.spbDailyPercentChange.setMaximum(10)
        self.spbDailyPercentChange.setProperty("value", 5)
        self.spbDailyPercentChange.setObjectName("spbDailyPercentChange")
        self.horizontalLayout_3.addWidget(self.spbDailyPercentChange)
        self.cbxOneMinUpPercent = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxOneMinUpPercent.setFont(font)
        self.cbxOneMinUpPercent.setChecked(True)
        self.cbxOneMinUpPercent.setObjectName("cbxOneMinUpPercent")
        self.horizontalLayout_3.addWidget(self.cbxOneMinUpPercent)
        self.spbShortTermPercentChange = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spbShortTermPercentChange.setDecimals(1)
        self.spbShortTermPercentChange.setMaximum(10.0)
        self.spbShortTermPercentChange.setSingleStep(0.1)
        self.spbShortTermPercentChange.setProperty("value", 0.5)
        self.spbShortTermPercentChange.setObjectName("spbShortTermPercentChange")
        self.horizontalLayout_3.addWidget(self.spbShortTermPercentChange)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbxSingleBuyAmount = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxSingleBuyAmount.setFont(font)
        self.cbxSingleBuyAmount.setChecked(True)
        self.cbxSingleBuyAmount.setObjectName("cbxSingleBuyAmount")
        self.horizontalLayout_5.addWidget(self.cbxSingleBuyAmount)
        self.spbSingleTransactionAmount = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbSingleTransactionAmount.setFont(font)
        self.spbSingleTransactionAmount.setMinimum(10)
        self.spbSingleTransactionAmount.setMaximum(10000)
        self.spbSingleTransactionAmount.setProperty("value", 50)
        self.spbSingleTransactionAmount.setObjectName("spbSingleTransactionAmount")
        self.horizontalLayout_5.addWidget(self.spbSingleTransactionAmount)
        self.cbxBuyBid = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxBuyBid.setFont(font)
        self.cbxBuyBid.setChecked(True)
        self.cbxBuyBid.setObjectName("cbxBuyBid")
        self.horizontalLayout_5.addWidget(self.cbxBuyBid)
        self.spbBuyBidPercent = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbBuyBidPercent.setFont(font)
        self.spbBuyBidPercent.setMinimum(0)
        self.spbBuyBidPercent.setMaximum(100)
        self.spbBuyBidPercent.setProperty("value", 70)
        self.spbBuyBidPercent.setObjectName("spbBuyBidPercent")
        self.horizontalLayout_5.addWidget(self.spbBuyBidPercent)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbxActiveBuyRatio = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxActiveBuyRatio.setFont(font)
        self.cbxActiveBuyRatio.setChecked(True)
        self.cbxActiveBuyRatio.setObjectName("cbxActiveBuyRatio")
        self.horizontalLayout_6.addWidget(self.cbxActiveBuyRatio)
        self.spbActiveBuyPercent = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbActiveBuyPercent.setFont(font)
        self.spbActiveBuyPercent.setMinimum(50)
        self.spbActiveBuyPercent.setMaximum(100)
        self.spbActiveBuyPercent.setProperty("value", 80)
        self.spbActiveBuyPercent.setObjectName("spbActiveBuyPercent")
        self.horizontalLayout_6.addWidget(self.spbActiveBuyPercent)
        self.cbxShortTermAmount = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbxShortTermAmount.setObjectName("cbxShortTermAmount")
        self.horizontalLayout_6.addWidget(self.cbxShortTermAmount)
        self.spbShortTermAmount = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbShortTermAmount.setFont(font)
        self.spbShortTermAmount.setMinimum(10)
        self.spbShortTermAmount.setMaximum(10000)
        self.spbShortTermAmount.setProperty("value", 100)
        self.spbShortTermAmount.setObjectName("spbShortTermAmount")
        self.horizontalLayout_6.addWidget(self.spbShortTermAmount)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 691, 62))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnImportStockList = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnImportStockList.setFont(font)
        self.btnImportStockList.setObjectName("btnImportStockList")
        self.horizontalLayout.addWidget(self.btnImportStockList)
        self.btnClearStocks = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnClearStocks.setFont(font)
        self.btnClearStocks.setObjectName("btnClearStocks")
        self.horizontalLayout.addWidget(self.btnClearStocks)
        self.lblNewStockCode = QtWidgets.QLabel(self.layoutWidget1)
        self.lblNewStockCode.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblNewStockCode.setFont(font)
        self.lblNewStockCode.setObjectName("lblNewStockCode")
        self.horizontalLayout.addWidget(self.lblNewStockCode)
        self.iptStockCode = QtWidgets.QLineEdit(self.layoutWidget1)
        self.iptStockCode.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout.addWidget(self.iptStockCode)
        self.btnAddStock = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnAddStock.setFont(font)
        self.btnAddStock.setObjectName("btnAddStock")
        self.horizontalLayout.addWidget(self.btnAddStock)
        self.btnRemoveStock = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnRemoveStock.setFont(font)
        self.btnRemoveStock.setObjectName("btnRemoveStock")
        self.horizontalLayout.addWidget(self.btnRemoveStock)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnStartTracking = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnStartTracking.setFont(font)
        self.btnStartTracking.setObjectName("btnStartTracking")
        self.horizontalLayout_2.addWidget(self.btnStartTracking)
        self.btnStopTracking = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnStopTracking.setFont(font)
        self.btnStopTracking.setObjectName("btnStopTracking")
        self.horizontalLayout_2.addWidget(self.btnStopTracking)
        self.lblLastUpdateTime = QtWidgets.QLabel(self.layoutWidget1)
        self.lblLastUpdateTime.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblLastUpdateTime.setFont(font)
        self.lblLastUpdateTime.setObjectName("lblLastUpdateTime")
        self.horizontalLayout_2.addWidget(self.lblLastUpdateTime)
        self.lblUpdateFrequency = QtWidgets.QLabel(self.layoutWidget1)
        self.lblUpdateFrequency.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblUpdateFrequency.setFont(font)
        self.lblUpdateFrequency.setObjectName("lblUpdateFrequency")
        self.horizontalLayout_2.addWidget(self.lblUpdateFrequency)
        self.spbUpdateFrequency = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spbUpdateFrequency.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spbUpdateFrequency.setFont(font)
        self.spbUpdateFrequency.setMinimum(1)
        self.spbUpdateFrequency.setMaximum(10)
        self.spbUpdateFrequency.setProperty("value", 2)
        self.spbUpdateFrequency.setObjectName("spbUpdateFrequency")
        self.horizontalLayout_2.addWidget(self.spbUpdateFrequency)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        LiveTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LiveTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        LiveTracker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LiveTracker)
        self.statusbar.setObjectName("statusbar")
        LiveTracker.setStatusBar(self.statusbar)
        self.MaxStockWatcher = QtWidgets.QAction(LiveTracker)
        self.MaxStockWatcher.setObjectName("MaxStockWatcher")
        self.MinStockWatcher = QtWidgets.QAction(LiveTracker)
        self.MinStockWatcher.setObjectName("MinStockWatcher")
        self.menu.addAction(self.MaxStockWatcher)
        self.menu.addAction(self.MinStockWatcher)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(LiveTracker)
        self.btnImportStockList.clicked.connect(LiveTracker.import_stock_list)
        self.btnStartTracking.clicked.connect(LiveTracker.start_monitoring)
        self.btnStopTracking.clicked.connect(LiveTracker.stop_monitoring)
        self.btnAddStock.clicked.connect(LiveTracker.add_stock_code)
        self.btnRemoveStock.clicked.connect(LiveTracker.remove_stock_code)
        self.btnClearStocks.clicked.connect(LiveTracker.clear_stock_list)
        self.cbxDailyUpPercent.clicked['bool'].connect(self.spbDailyPercentChange.setEnabled)
        self.cbxSingleBuyAmount.clicked['bool'].connect(self.spbSingleTransactionAmount.setEnabled)
        self.cbxActiveBuyRatio.clicked['bool'].connect(self.spbActiveBuyPercent.setEnabled)
        self.cbxOneMinUpPercent.clicked['bool'].connect(self.spbShortTermPercentChange.setEnabled)
        self.cbxBuyBid.clicked['bool'].connect(self.spbBuyBidPercent.setEnabled)
        self.cbxShortTermAmount.clicked['bool'].connect(self.spbShortTermAmount.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(LiveTracker)

    def retranslateUi(self, LiveTracker):
        _translate = QtCore.QCoreApplication.translate
        LiveTracker.setWindowTitle(_translate("LiveTracker", "实时盯盘助手"))
        item = self.tblStockList.horizontalHeaderItem(0)
        item.setText(_translate("LiveTracker", "代码"))
        item = self.tblStockList.horizontalHeaderItem(1)
        item.setText(_translate("LiveTracker", "名称"))
        item = self.tblStockList.horizontalHeaderItem(2)
        item.setText(_translate("LiveTracker", "最新成交"))
        item = self.tblStockList.horizontalHeaderItem(3)
        item.setText(_translate("LiveTracker", "价格"))
        item = self.tblStockList.horizontalHeaderItem(4)
        item.setText(_translate("LiveTracker", "涨跌幅"))
        item = self.tblStockList.horizontalHeaderItem(5)
        item.setText(_translate("LiveTracker", "五档委比"))
        item = self.tblStockList.horizontalHeaderItem(6)
        item.setText(_translate("LiveTracker", "最近涨跌"))
        item = self.tblStockList.horizontalHeaderItem(7)
        item.setText(_translate("LiveTracker", "外盘比例"))
        item = self.tblStockList.horizontalHeaderItem(8)
        item.setText(_translate("LiveTracker", "成交额"))
        self.grpEventSignal.setTitle(_translate("LiveTracker", "盘中异动提示"))
        self.lblRecentMeasurement.setText(_translate("LiveTracker", "短时数据来源："))
        self.cbxDailyUpPercent.setText(_translate("LiveTracker", "日内当前涨跌幅达到"))
        self.spbDailyPercentChange.setSuffix(_translate("LiveTracker", "%"))
        self.cbxOneMinUpPercent.setText(_translate("LiveTracker", "短时涨跌幅达到"))
        self.spbShortTermPercentChange.setSuffix(_translate("LiveTracker", "%"))
        self.cbxSingleBuyAmount.setText(_translate("LiveTracker", "单笔成交大于"))
        self.spbSingleTransactionAmount.setSuffix(_translate("LiveTracker", "万元"))
        self.cbxBuyBid.setText(_translate("LiveTracker", "短时委比超过正负"))
        self.spbBuyBidPercent.setSuffix(_translate("LiveTracker", "%"))
        self.cbxActiveBuyRatio.setText(_translate("LiveTracker", "短时外盘/内盘占比大于"))
        self.spbActiveBuyPercent.setSuffix(_translate("LiveTracker", "%"))
        self.cbxShortTermAmount.setText(_translate("LiveTracker", "短时成交额大于"))
        self.spbShortTermAmount.setSuffix(_translate("LiveTracker", "万"))
        self.btnImportStockList.setText(_translate("LiveTracker", "导入股票列表"))
        self.btnClearStocks.setText(_translate("LiveTracker", "清空列表"))
        self.lblNewStockCode.setText(_translate("LiveTracker", "股票代码"))
        self.iptStockCode.setText(_translate("LiveTracker", "600519"))
        self.btnAddStock.setText(_translate("LiveTracker", "添加股票"))
        self.btnRemoveStock.setText(_translate("LiveTracker", "删除股票"))
        self.btnStartTracking.setText(_translate("LiveTracker", "开始盯盘"))
        self.btnStopTracking.setText(_translate("LiveTracker", "停止盯盘"))
        self.lblLastUpdateTime.setText(_translate("LiveTracker", "上次刷新："))
        self.lblUpdateFrequency.setText(_translate("LiveTracker", "刷新频率："))
        self.spbUpdateFrequency.setSuffix(_translate("LiveTracker", "秒"))
        self.spbUpdateFrequency.setPrefix(_translate("LiveTracker", "每"))
        self.menu.setTitle(_translate("LiveTracker", "打板神器"))
        self.MaxStockWatcher.setText(_translate("LiveTracker", "涨停板"))
        self.MinStockWatcher.setText(_translate("LiveTracker", "跌停板"))
