# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 192)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStockAnalyzer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStockAnalyzer.sizePolicy().hasHeightForWidth())
        self.btnStockAnalyzer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnStockAnalyzer.setFont(font)
        self.btnStockAnalyzer.setObjectName("btnStockAnalyzer")
        self.horizontalLayout.addWidget(self.btnStockAnalyzer)
        self.btnTradeSimulator = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTradeSimulator.sizePolicy().hasHeightForWidth())
        self.btnTradeSimulator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnTradeSimulator.setFont(font)
        self.btnTradeSimulator.setObjectName("btnTradeSimulator")
        self.horizontalLayout.addWidget(self.btnTradeSimulator)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnStockFinder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStockFinder.sizePolicy().hasHeightForWidth())
        self.btnStockFinder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnStockFinder.setFont(font)
        self.btnStockFinder.setObjectName("btnStockFinder")
        self.horizontalLayout_2.addWidget(self.btnStockFinder)
        self.btnSelectedPerformance = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectedPerformance.sizePolicy().hasHeightForWidth())
        self.btnSelectedPerformance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnSelectedPerformance.setFont(font)
        self.btnSelectedPerformance.setObjectName("btnSelectedPerformance")
        self.horizontalLayout_2.addWidget(self.btnSelectedPerformance)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnPoolMonitor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPoolMonitor.sizePolicy().hasHeightForWidth())
        self.btnPoolMonitor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnPoolMonitor.setFont(font)
        self.btnPoolMonitor.setObjectName("btnPoolMonitor")
        self.horizontalLayout_3.addWidget(self.btnPoolMonitor)
        self.btnScheduledInvestment = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScheduledInvestment.sizePolicy().hasHeightForWidth())
        self.btnScheduledInvestment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnScheduledInvestment.setFont(font)
        self.btnScheduledInvestment.setObjectName("btnScheduledInvestment")
        self.horizontalLayout_3.addWidget(self.btnScheduledInvestment)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn15MinFinder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn15MinFinder.sizePolicy().hasHeightForWidth())
        self.btn15MinFinder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btn15MinFinder.setFont(font)
        self.btn15MinFinder.setObjectName("btn15MinFinder")
        self.horizontalLayout_4.addWidget(self.btn15MinFinder)
        self.btn15MinTrader = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn15MinTrader.sizePolicy().hasHeightForWidth())
        self.btn15MinTrader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btn15MinTrader.setFont(font)
        self.btn15MinTrader.setObjectName("btn15MinTrader")
        self.horizontalLayout_4.addWidget(self.btn15MinTrader)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.actReconnect = QtWidgets.QAction(MainWindow)
        self.actReconnect.setObjectName("actReconnect")
        self.actTradeSettings = QtWidgets.QAction(MainWindow)
        self.actTradeSettings.setObjectName("actTradeSettings")
        self.actGetStockList = QtWidgets.QAction(MainWindow)
        self.actGetStockList.setObjectName("actGetStockList")
        self.actGetStockData = QtWidgets.QAction(MainWindow)
        self.actGetStockData.setObjectName("actGetStockData")
        self.menu.addAction(self.actReconnect)
        self.menu.addAction(self.actTradeSettings)
        self.menu_2.addAction(self.actGetStockList)
        self.menu_2.addAction(self.actGetStockData)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "647炒股神器"))
        self.btnStockAnalyzer.setText(_translate("MainWindow", "个股股性分析"))
        self.btnTradeSimulator.setText(_translate("MainWindow", "趋势模拟交易"))
        self.btnStockFinder.setText(_translate("MainWindow", "日线指标选股"))
        self.btnSelectedPerformance.setText(_translate("MainWindow", "日线选股回测"))
        self.btnPoolMonitor.setText(_translate("MainWindow", "日线股池监测"))
        self.btnScheduledInvestment.setText(_translate("MainWindow", "定投组合表现"))
        self.btn15MinFinder.setText(_translate("MainWindow", "15分钟线选股"))
        self.btn15MinTrader.setText(_translate("MainWindow", "15分钟线回测"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "数据"))
        self.actReconnect.setText(_translate("MainWindow", "断线重连"))
        self.actTradeSettings.setText(_translate("MainWindow", "交易设置"))
        self.actGetStockList.setText(_translate("MainWindow", "获取全部股票列表"))
        self.actGetStockData.setText(_translate("MainWindow", "获取股票历史K线"))
