# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonitorCondition.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitorCondition(object):
    def setupUi(self, MonitorCondition):
        MonitorCondition.setObjectName("MonitorCondition")
        MonitorCondition.resize(329, 263)
        self.layoutWidget = QtWidgets.QWidget(MonitorCondition)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 305, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblGroupName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblGroupName.setFont(font)
        self.lblGroupName.setObjectName("lblGroupName")
        self.horizontalLayout_2.addWidget(self.lblGroupName)
        self.txtGroupName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.txtGroupName.setFont(font)
        self.txtGroupName.setText("")
        self.txtGroupName.setPlaceholderText("")
        self.txtGroupName.setObjectName("txtGroupName")
        self.horizontalLayout_2.addWidget(self.txtGroupName)
        self.lblCoolDownTime = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblCoolDownTime.setFont(font)
        self.lblCoolDownTime.setObjectName("lblCoolDownTime")
        self.horizontalLayout_2.addWidget(self.lblCoolDownTime)
        self.spbCoolDownTime = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbCoolDownTime.setFont(font)
        self.spbCoolDownTime.setMinimum(1)
        self.spbCoolDownTime.setMaximum(120)
        self.spbCoolDownTime.setProperty("value", 10)
        self.spbCoolDownTime.setObjectName("spbCoolDownTime")
        self.horizontalLayout_2.addWidget(self.spbCoolDownTime)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddItem = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnAddItem.setFont(font)
        self.btnAddItem.setObjectName("btnAddItem")
        self.horizontalLayout.addWidget(self.btnAddItem)
        self.btnDeleteItem = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnDeleteItem.setFont(font)
        self.btnDeleteItem.setObjectName("btnDeleteItem")
        self.horizontalLayout.addWidget(self.btnDeleteItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblMonitorItems = QtWidgets.QTableWidget(self.layoutWidget)
        self.tblMonitorItems.setObjectName("tblMonitorItems")
        self.tblMonitorItems.setColumnCount(2)
        self.tblMonitorItems.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMonitorItems.setHorizontalHeaderItem(1, item)
        self.tblMonitorItems.horizontalHeader().setDefaultSectionSize(120)
        self.tblMonitorItems.horizontalHeader().setMinimumSectionSize(120)
        self.tblMonitorItems.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout.addWidget(self.tblMonitorItems)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSave = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnDiscard = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btnDiscard.setFont(font)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout_4.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(MonitorCondition)
        self.btnSave.clicked.connect(MonitorCondition.save_changes)
        self.btnDiscard.clicked.connect(MonitorCondition.discard_changes)
        self.btnAddItem.clicked.connect(MonitorCondition.add_condition_item)
        self.btnDeleteItem.clicked.connect(MonitorCondition.delete_condition_item)
        QtCore.QMetaObject.connectSlotsByName(MonitorCondition)

    def retranslateUi(self, MonitorCondition):
        _translate = QtCore.QCoreApplication.translate
        MonitorCondition.setWindowTitle(_translate("MonitorCondition", "盯盘指标"))
        self.lblGroupName.setText(_translate("MonitorCondition", "指标组合名称"))
        self.lblCoolDownTime.setText(_translate("MonitorCondition", "冷却时间"))
        self.spbCoolDownTime.setSuffix(_translate("MonitorCondition", "分钟"))
        self.btnAddItem.setText(_translate("MonitorCondition", "添加指标"))
        self.btnDeleteItem.setText(_translate("MonitorCondition", "删除指标"))
        item = self.tblMonitorItems.horizontalHeaderItem(0)
        item.setText(_translate("MonitorCondition", "监控指标"))
        item = self.tblMonitorItems.horizontalHeaderItem(1)
        item.setText(_translate("MonitorCondition", "触发数值"))
        self.btnSave.setText(_translate("MonitorCondition", "保存"))
        self.btnDiscard.setText(_translate("MonitorCondition", "取消"))
