# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegularInvestment.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupPerformance(object):
    def setupUi(self, GroupPerformance):
        GroupPerformance.setObjectName("GroupPerformance")
        GroupPerformance.resize(602, 293)
        self.centralwidget = QtWidgets.QWidget(GroupPerformance)
        self.centralwidget.setObjectName("centralwidget")
        self.RegularInvestment = QtWidgets.QTableWidget(self.centralwidget)
        self.RegularInvestment.setGeometry(QtCore.QRect(10, 46, 581, 192))
        self.RegularInvestment.setObjectName("RegularInvestment")
        self.RegularInvestment.setColumnCount(4)
        self.RegularInvestment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.RegularInvestment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegularInvestment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegularInvestment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegularInvestment.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 581, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblNewStockCode = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblNewStockCode.setFont(font)
        self.lblNewStockCode.setObjectName("lblNewStockCode")
        self.horizontalLayout.addWidget(self.lblNewStockCode)
        self.iptStockCode = QtWidgets.QLineEdit(self.widget)
        self.iptStockCode.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout.addWidget(self.iptStockCode)
        self.btnAddStock = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnAddStock.setFont(font)
        self.btnAddStock.setObjectName("btnAddStock")
        self.horizontalLayout.addWidget(self.btnAddStock)
        self.btnRemoveStock = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnRemoveStock.setFont(font)
        self.btnRemoveStock.setObjectName("btnRemoveStock")
        self.horizontalLayout.addWidget(self.btnRemoveStock)
        self.btnClearStocks = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnClearStocks.setFont(font)
        self.btnClearStocks.setObjectName("btnClearStocks")
        self.horizontalLayout.addWidget(self.btnClearStocks)
        self.btnExportStockList = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnExportStockList.setFont(font)
        self.btnExportStockList.setObjectName("btnExportStockList")
        self.horizontalLayout.addWidget(self.btnExportStockList)
        self.btnImportStockList = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnImportStockList.setFont(font)
        self.btnImportStockList.setObjectName("btnImportStockList")
        self.horizontalLayout.addWidget(self.btnImportStockList)
        GroupPerformance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GroupPerformance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 22))
        self.menubar.setObjectName("menubar")
        GroupPerformance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GroupPerformance)
        self.statusbar.setObjectName("statusbar")
        GroupPerformance.setStatusBar(self.statusbar)

        self.retranslateUi(GroupPerformance)
        QtCore.QMetaObject.connectSlotsByName(GroupPerformance)

    def retranslateUi(self, GroupPerformance):
        _translate = QtCore.QCoreApplication.translate
        GroupPerformance.setWindowTitle(_translate("GroupPerformance", "持仓组合表现"))
        item = self.RegularInvestment.horizontalHeaderItem(0)
        item.setText(_translate("GroupPerformance", "股票代码"))
        item = self.RegularInvestment.horizontalHeaderItem(1)
        item.setText(_translate("GroupPerformance", "股票名称"))
        item = self.RegularInvestment.horizontalHeaderItem(2)
        item.setText(_translate("GroupPerformance", "持股仓位"))
        item = self.RegularInvestment.horizontalHeaderItem(3)
        item.setText(_translate("GroupPerformance", "持仓盈亏"))
        self.lblNewStockCode.setText(_translate("GroupPerformance", "股票代码/名称"))
        self.iptStockCode.setText(_translate("GroupPerformance", "贵州茅台"))
        self.btnAddStock.setText(_translate("GroupPerformance", "添加股票"))
        self.btnRemoveStock.setText(_translate("GroupPerformance", "删除股票"))
        self.btnClearStocks.setText(_translate("GroupPerformance", "清空列表"))
        self.btnExportStockList.setText(_translate("GroupPerformance", "导出列表"))
        self.btnImportStockList.setText(_translate("GroupPerformance", "导入列表"))
