# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScheduledInvestment.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScheduledInvestment(object):
    def setupUi(self, ScheduledInvestment):
        ScheduledInvestment.setObjectName("ScheduledInvestment")
        ScheduledInvestment.resize(710, 395)
        self.centralwidget = QtWidgets.QWidget(ScheduledInvestment)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblStartDate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.horizontalLayout_2.addWidget(self.lblStartDate)
        self.dteStartDate = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.dteStartDate.setFont(font)
        self.dteStartDate.setObjectName("dteStartDate")
        self.horizontalLayout_2.addWidget(self.dteStartDate)
        self.lblInitialInvestment = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInitialInvestment.setFont(font)
        self.lblInitialInvestment.setObjectName("lblInitialInvestment")
        self.horizontalLayout_2.addWidget(self.lblInitialInvestment)
        self.spbInitialInvestment = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbInitialInvestment.setFont(font)
        self.spbInitialInvestment.setPrefix("")
        self.spbInitialInvestment.setMinimum(1)
        self.spbInitialInvestment.setMaximum(1000)
        self.spbInitialInvestment.setProperty("value", 20)
        self.spbInitialInvestment.setObjectName("spbInitialInvestment")
        self.horizontalLayout_2.addWidget(self.spbInitialInvestment)
        self.lblEachInvestment = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblEachInvestment.setFont(font)
        self.lblEachInvestment.setObjectName("lblEachInvestment")
        self.horizontalLayout_2.addWidget(self.lblEachInvestment)
        self.spbEachInvestment = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbEachInvestment.setFont(font)
        self.spbEachInvestment.setPrefix("")
        self.spbEachInvestment.setMinimum(1)
        self.spbEachInvestment.setMaximum(1000)
        self.spbEachInvestment.setProperty("value", 5)
        self.spbEachInvestment.setObjectName("spbEachInvestment")
        self.horizontalLayout_2.addWidget(self.spbEachInvestment)
        self.lblInvestInterval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInvestInterval.setFont(font)
        self.lblInvestInterval.setObjectName("lblInvestInterval")
        self.horizontalLayout_2.addWidget(self.lblInvestInterval)
        self.spbInvestInterval = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbInvestInterval.setFont(font)
        self.spbInvestInterval.setMinimum(1)
        self.spbInvestInterval.setMaximum(50)
        self.spbInvestInterval.setProperty("value", 3)
        self.spbInvestInterval.setObjectName("spbInvestInterval")
        self.horizontalLayout_2.addWidget(self.spbInvestInterval)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxSmartBuy = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxSmartBuy.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbxSmartBuy.setFont(font)
        self.cbxSmartBuy.setChecked(True)
        self.cbxSmartBuy.setObjectName("cbxSmartBuy")
        self.horizontalLayout_3.addWidget(self.cbxSmartBuy)
        self.spbSmartBuyMaPeriod = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbSmartBuyMaPeriod.setFont(font)
        self.spbSmartBuyMaPeriod.setMinimum(3)
        self.spbSmartBuyMaPeriod.setMaximum(60)
        self.spbSmartBuyMaPeriod.setProperty("value", 6)
        self.spbSmartBuyMaPeriod.setObjectName("spbSmartBuyMaPeriod")
        self.horizontalLayout_3.addWidget(self.spbSmartBuyMaPeriod)
        self.lblSmartBuyMa = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblSmartBuyMa.setFont(font)
        self.lblSmartBuyMa.setObjectName("lblSmartBuyMa")
        self.horizontalLayout_3.addWidget(self.lblSmartBuyMa)
        self.spbSmartBuyMaBias = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbSmartBuyMaBias.setFont(font)
        self.spbSmartBuyMaBias.setMinimum(-20)
        self.spbSmartBuyMaBias.setMaximum(20)
        self.spbSmartBuyMaBias.setProperty("value", 0)
        self.spbSmartBuyMaBias.setObjectName("spbSmartBuyMaBias")
        self.horizontalLayout_3.addWidget(self.spbSmartBuyMaBias)
        self.lblSmartBuyExplanation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblSmartBuyExplanation.setFont(font)
        self.lblSmartBuyExplanation.setObjectName("lblSmartBuyExplanation")
        self.horizontalLayout_3.addWidget(self.lblSmartBuyExplanation)
        self.spbSmartBuyFactor = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSmartBuyFactor.setFont(font)
        self.spbSmartBuyFactor.setPrefix("")
        self.spbSmartBuyFactor.setMinimum(1)
        self.spbSmartBuyFactor.setMaximum(20)
        self.spbSmartBuyFactor.setProperty("value", 5)
        self.spbSmartBuyFactor.setObjectName("spbSmartBuyFactor")
        self.horizontalLayout_3.addWidget(self.spbSmartBuyFactor)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxSmartSell = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbxSmartSell.setFont(font)
        self.cbxSmartSell.setChecked(True)
        self.cbxSmartSell.setObjectName("cbxSmartSell")
        self.horizontalLayout_4.addWidget(self.cbxSmartSell)
        self.spbSmartSellThreshold = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbSmartSellThreshold.setFont(font)
        self.spbSmartSellThreshold.setMinimum(10)
        self.spbSmartSellThreshold.setMaximum(100)
        self.spbSmartSellThreshold.setProperty("value", 20)
        self.spbSmartSellThreshold.setObjectName("spbSmartSellThreshold")
        self.horizontalLayout_4.addWidget(self.spbSmartSellThreshold)
        self.lblSmartSellExplanation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblSmartSellExplanation.setFont(font)
        self.lblSmartSellExplanation.setObjectName("lblSmartSellExplanation")
        self.horizontalLayout_4.addWidget(self.lblSmartSellExplanation)
        self.spbSmartSellFactor = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbSmartSellFactor.setFont(font)
        self.spbSmartSellFactor.setMinimum(1)
        self.spbSmartSellFactor.setMaximum(20)
        self.spbSmartSellFactor.setProperty("value", 5)
        self.spbSmartSellFactor.setObjectName("spbSmartSellFactor")
        self.horizontalLayout_4.addWidget(self.spbSmartSellFactor)
        self.cbxBuyBackAfterSell = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbxBuyBackAfterSell.setFont(font)
        self.cbxBuyBackAfterSell.setChecked(True)
        self.cbxBuyBackAfterSell.setObjectName("cbxBuyBackAfterSell")
        self.horizontalLayout_4.addWidget(self.cbxBuyBackAfterSell)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbxBuyByPercent = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbxBuyByPercent.setFont(font)
        self.cbxBuyByPercent.setChecked(True)
        self.cbxBuyByPercent.setObjectName("cbxBuyByPercent")
        self.horizontalLayout_5.addWidget(self.cbxBuyByPercent)
        self.spbBuyByPercent = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbBuyByPercent.setFont(font)
        self.spbBuyByPercent.setMinimum(0)
        self.spbBuyByPercent.setMaximum(50)
        self.spbBuyByPercent.setProperty("value", 10)
        self.spbBuyByPercent.setObjectName("spbBuyByPercent")
        self.horizontalLayout_5.addWidget(self.spbBuyByPercent)
        self.lblBuyByPercent = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblBuyByPercent.setFont(font)
        self.lblBuyByPercent.setObjectName("lblBuyByPercent")
        self.horizontalLayout_5.addWidget(self.lblBuyByPercent)
        self.cbxSellByPercent = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbxSellByPercent.setFont(font)
        self.cbxSellByPercent.setChecked(True)
        self.cbxSellByPercent.setObjectName("cbxSellByPercent")
        self.horizontalLayout_5.addWidget(self.cbxSellByPercent)
        self.spbSellByPercent = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spbSellByPercent.setFont(font)
        self.spbSellByPercent.setMinimum(0)
        self.spbSellByPercent.setMaximum(50)
        self.spbSellByPercent.setProperty("value", 15)
        self.spbSellByPercent.setObjectName("spbSellByPercent")
        self.horizontalLayout_5.addWidget(self.spbSellByPercent)
        self.lblSellByPercent = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblSellByPercent.setFont(font)
        self.lblSellByPercent.setObjectName("lblSellByPercent")
        self.horizontalLayout_5.addWidget(self.lblSellByPercent)
        self.btnImportPlan = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportPlan.setFont(font)
        self.btnImportPlan.setObjectName("btnImportPlan")
        self.horizontalLayout_5.addWidget(self.btnImportPlan)
        self.btnExportPlan = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportPlan.setFont(font)
        self.btnExportPlan.setObjectName("btnExportPlan")
        self.horizontalLayout_5.addWidget(self.btnExportPlan)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblNewStockCode = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblNewStockCode.setFont(font)
        self.lblNewStockCode.setObjectName("lblNewStockCode")
        self.horizontalLayout.addWidget(self.lblNewStockCode)
        self.iptStockCode = QtWidgets.QLineEdit(self.centralwidget)
        self.iptStockCode.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout.addWidget(self.iptStockCode)
        self.btnAddStock = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnAddStock.setFont(font)
        self.btnAddStock.setObjectName("btnAddStock")
        self.horizontalLayout.addWidget(self.btnAddStock)
        self.btnRemoveStock = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnRemoveStock.setFont(font)
        self.btnRemoveStock.setObjectName("btnRemoveStock")
        self.horizontalLayout.addWidget(self.btnRemoveStock)
        self.btnClearStocks = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnClearStocks.setFont(font)
        self.btnClearStocks.setObjectName("btnClearStocks")
        self.horizontalLayout.addWidget(self.btnClearStocks)
        self.btnImportStockList = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportStockList.setFont(font)
        self.btnImportStockList.setObjectName("btnImportStockList")
        self.horizontalLayout.addWidget(self.btnImportStockList)
        self.btnExportStockList = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportStockList.setFont(font)
        self.btnExportStockList.setObjectName("btnExportStockList")
        self.horizontalLayout.addWidget(self.btnExportStockList)
        self.btnAutoSplitRatio = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnAutoSplitRatio.setFont(font)
        self.btnAutoSplitRatio.setObjectName("btnAutoSplitRatio")
        self.horizontalLayout.addWidget(self.btnAutoSplitRatio)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblStockList = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tblStockList.setFont(font)
        self.tblStockList.setObjectName("tblStockList")
        self.tblStockList.setColumnCount(9)
        self.tblStockList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(8, item)
        self.tblStockList.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout.addWidget(self.tblStockList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnStartInvesting = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartInvesting.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartInvesting.setFont(font)
        self.btnStartInvesting.setObjectName("btnStartInvesting")
        self.horizontalLayout_6.addWidget(self.btnStartInvesting)
        self.lblTradeSummary = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblTradeSummary.setFont(font)
        self.lblTradeSummary.setObjectName("lblTradeSummary")
        self.horizontalLayout_6.addWidget(self.lblTradeSummary)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        ScheduledInvestment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ScheduledInvestment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 22))
        self.menubar.setObjectName("menubar")
        ScheduledInvestment.setMenuBar(self.menubar)

        self.retranslateUi(ScheduledInvestment)
        self.btnExportPlan.clicked.connect(ScheduledInvestment.export_investment_plan)
        self.btnImportPlan.clicked.connect(ScheduledInvestment.import_investment_plan)
        self.btnExportStockList.clicked.connect(ScheduledInvestment.export_stock_list)
        self.btnImportStockList.clicked.connect(ScheduledInvestment.import_stock_list)
        self.btnAddStock.clicked.connect(ScheduledInvestment.add_stock_code)
        self.btnRemoveStock.clicked.connect(ScheduledInvestment.remove_stock_code)
        self.btnClearStocks.clicked.connect(ScheduledInvestment.clear_stock_list)
        self.btnStartInvesting.clicked.connect(ScheduledInvestment.start_investing)
        self.tblStockList.cellDoubleClicked['int','int'].connect(ScheduledInvestment.show_stock_graph)
        self.cbxSmartBuy.toggled['bool'].connect(self.spbSmartBuyFactor.setEnabled)
        self.btnAutoSplitRatio.clicked.connect(ScheduledInvestment.auto_split_ratio)
        self.cbxSmartBuy.toggled['bool'].connect(self.spbSmartBuyMaPeriod.setEnabled)
        self.cbxSmartBuy.toggled['bool'].connect(self.spbSmartBuyMaBias.setEnabled)
        self.cbxSmartSell.toggled['bool'].connect(self.spbSmartSellThreshold.setEnabled)
        self.cbxSmartSell.toggled['bool'].connect(self.spbSmartSellFactor.setEnabled)
        self.cbxSmartSell.toggled['bool'].connect(self.cbxBuyBackAfterSell.setEnabled)
        self.cbxBuyByPercent.toggled['bool'].connect(self.spbBuyByPercent.setEnabled)
        self.cbxSellByPercent.toggled['bool'].connect(self.spbSellByPercent.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ScheduledInvestment)

    def retranslateUi(self, ScheduledInvestment):
        _translate = QtCore.QCoreApplication.translate
        ScheduledInvestment.setWindowTitle(_translate("ScheduledInvestment", "定投组合表现"))
        self.lblStartDate.setText(_translate("ScheduledInvestment", "开始日期"))
        self.dteStartDate.setDisplayFormat(_translate("ScheduledInvestment", "yyyy-MM-dd"))
        self.lblInitialInvestment.setText(_translate("ScheduledInvestment", "初始总金额"))
        self.spbInitialInvestment.setSuffix(_translate("ScheduledInvestment", "万元"))
        self.lblEachInvestment.setText(_translate("ScheduledInvestment", "每期总金额"))
        self.spbEachInvestment.setSuffix(_translate("ScheduledInvestment", "万元"))
        self.lblInvestInterval.setText(_translate("ScheduledInvestment", "定投间隔"))
        self.spbInvestInterval.setSuffix(_translate("ScheduledInvestment", "月"))
        self.spbInvestInterval.setPrefix(_translate("ScheduledInvestment", "每"))
        self.cbxSmartBuy.setText(_translate("ScheduledInvestment", "以"))
        self.spbSmartBuyMaPeriod.setSuffix(_translate("ScheduledInvestment", "月"))
        self.lblSmartBuyMa.setText(_translate("ScheduledInvestment", "均线之上"))
        self.spbSmartBuyMaBias.setSuffix(_translate("ScheduledInvestment", "%"))
        self.lblSmartBuyExplanation.setText(_translate("ScheduledInvestment", "的价格为基准，每上涨或下跌1%，相应减少或增加买入投资额 × "))
        self.spbSmartBuyFactor.setSuffix(_translate("ScheduledInvestment", "%"))
        self.cbxSmartSell.setText(_translate("ScheduledInvestment", "比上期上涨达到"))
        self.spbSmartSellThreshold.setSuffix(_translate("ScheduledInvestment", "%"))
        self.lblSmartSellExplanation.setText(_translate("ScheduledInvestment", "则不买入并卖出一笔，每额外上涨1%多卖出投资额 ×"))
        self.spbSmartSellFactor.setSuffix(_translate("ScheduledInvestment", "%"))
        self.cbxBuyBackAfterSell.setText(_translate("ScheduledInvestment", "卖出后若下期下跌则买回"))
        self.cbxBuyByPercent.setText(_translate("ScheduledInvestment", "单月跌幅每达到"))
        self.spbBuyByPercent.setSuffix(_translate("ScheduledInvestment", "%"))
        self.lblBuyByPercent.setText(_translate("ScheduledInvestment", "立刻买入一笔"))
        self.cbxSellByPercent.setText(_translate("ScheduledInvestment", "单月涨幅每达到"))
        self.spbSellByPercent.setSuffix(_translate("ScheduledInvestment", "%"))
        self.lblSellByPercent.setText(_translate("ScheduledInvestment", "立刻卖出一笔"))
        self.btnImportPlan.setText(_translate("ScheduledInvestment", "导入策略"))
        self.btnExportPlan.setText(_translate("ScheduledInvestment", "导出策略"))
        self.lblNewStockCode.setText(_translate("ScheduledInvestment", "股票代码/名称"))
        self.iptStockCode.setText(_translate("ScheduledInvestment", "贵州茅台"))
        self.btnAddStock.setText(_translate("ScheduledInvestment", "添加股票"))
        self.btnRemoveStock.setText(_translate("ScheduledInvestment", "删除股票"))
        self.btnClearStocks.setText(_translate("ScheduledInvestment", "清空列表"))
        self.btnImportStockList.setText(_translate("ScheduledInvestment", "导入列表"))
        self.btnExportStockList.setText(_translate("ScheduledInvestment", "导出列表"))
        self.btnAutoSplitRatio.setText(_translate("ScheduledInvestment", "平分仓位"))
        self.tblStockList.setSortingEnabled(True)
        item = self.tblStockList.horizontalHeaderItem(0)
        item.setText(_translate("ScheduledInvestment", "股票代码"))
        item = self.tblStockList.horizontalHeaderItem(1)
        item.setText(_translate("ScheduledInvestment", "股票名称"))
        item = self.tblStockList.horizontalHeaderItem(2)
        item.setText(_translate("ScheduledInvestment", "持股仓位"))
        item = self.tblStockList.horizontalHeaderItem(3)
        item.setText(_translate("ScheduledInvestment", "上市日期"))
        item = self.tblStockList.horizontalHeaderItem(4)
        item.setText(_translate("ScheduledInvestment", "年化复利"))
        item = self.tblStockList.horizontalHeaderItem(5)
        item.setText(_translate("ScheduledInvestment", "累计投入"))
        item = self.tblStockList.horizontalHeaderItem(6)
        item.setText(_translate("ScheduledInvestment", "最终获利"))
        item = self.tblStockList.horizontalHeaderItem(7)
        item.setText(_translate("ScheduledInvestment", "最高亏损"))
        item = self.tblStockList.horizontalHeaderItem(8)
        item.setText(_translate("ScheduledInvestment", "盈亏比例"))
        self.btnStartInvesting.setText(_translate("ScheduledInvestment", "开始定投"))
        self.lblTradeSummary.setText(_translate("ScheduledInvestment", "共计成本0元，至今获利0元，收益率0%"))
