# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchCriteria.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchCriteria(object):
    def setupUi(self, SearchCriteria):
        SearchCriteria.setObjectName("SearchCriteria")
        SearchCriteria.resize(363, 148)
        self.layoutWidget = QtWidgets.QWidget(SearchCriteria)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 350, 91))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblRecent = QtWidgets.QLabel(self.layoutWidget)
        self.lblRecent.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblRecent.setFont(font)
        self.lblRecent.setObjectName("lblRecent")
        self.horizontalLayout.addWidget(self.lblRecent)
        self.spbQueryPeriodBegin = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbQueryPeriodBegin.setFont(font)
        self.spbQueryPeriodBegin.setMinimum(1)
        self.spbQueryPeriodBegin.setMaximum(250)
        self.spbQueryPeriodBegin.setProperty("value", 3)
        self.spbQueryPeriodBegin.setObjectName("spbQueryPeriodBegin")
        self.horizontalLayout.addWidget(self.spbQueryPeriodBegin)
        self.lblTo1 = QtWidgets.QLabel(self.layoutWidget)
        self.lblTo1.setMaximumSize(QtCore.QSize(15, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblTo1.setFont(font)
        self.lblTo1.setObjectName("lblTo1")
        self.horizontalLayout.addWidget(self.lblTo1)
        self.spbQueryPeriodEnd = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbQueryPeriodEnd.setFont(font)
        self.spbQueryPeriodEnd.setMinimum(1)
        self.spbQueryPeriodEnd.setMaximum(250)
        self.spbQueryPeriodEnd.setObjectName("spbQueryPeriodEnd")
        self.horizontalLayout.addWidget(self.spbQueryPeriodEnd)
        self.cbbQueryLogic = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbQueryLogic.setFont(font)
        self.cbbQueryLogic.setObjectName("cbbQueryLogic")
        self.horizontalLayout.addWidget(self.cbbQueryLogic)
        self.cbbQueryField = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbQueryField.setFont(font)
        self.cbbQueryField.setObjectName("cbbQueryField")
        self.horizontalLayout.addWidget(self.cbbQueryField)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblComparison = QtWidgets.QLabel(self.layoutWidget)
        self.lblComparison.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblComparison.setFont(font)
        self.lblComparison.setObjectName("lblComparison")
        self.horizontalLayout_2.addWidget(self.lblComparison)
        self.spbComparedPeriodBegin = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbComparedPeriodBegin.setFont(font)
        self.spbComparedPeriodBegin.setMinimum(1)
        self.spbComparedPeriodBegin.setMaximum(250)
        self.spbComparedPeriodBegin.setProperty("value", 10)
        self.spbComparedPeriodBegin.setObjectName("spbComparedPeriodBegin")
        self.horizontalLayout_2.addWidget(self.spbComparedPeriodBegin)
        self.lblTo2 = QtWidgets.QLabel(self.layoutWidget)
        self.lblTo2.setMaximumSize(QtCore.QSize(15, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblTo2.setFont(font)
        self.lblTo2.setObjectName("lblTo2")
        self.horizontalLayout_2.addWidget(self.lblTo2)
        self.spbComparedPeriodEnd = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbComparedPeriodEnd.setFont(font)
        self.spbComparedPeriodEnd.setMinimum(1)
        self.spbComparedPeriodEnd.setMaximum(250)
        self.spbComparedPeriodEnd.setProperty("value", 1)
        self.spbComparedPeriodEnd.setObjectName("spbComparedPeriodEnd")
        self.horizontalLayout_2.addWidget(self.spbComparedPeriodEnd)
        self.cbbComparedLogic = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbComparedLogic.setFont(font)
        self.cbbComparedLogic.setObjectName("cbbComparedLogic")
        self.horizontalLayout_2.addWidget(self.cbbComparedLogic)
        self.cbbComparedField = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbComparedField.setFont(font)
        self.cbbComparedField.setObjectName("cbbComparedField")
        self.horizontalLayout_2.addWidget(self.cbbComparedField)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbbOperator = QtWidgets.QComboBox(self.layoutWidget)
        self.cbbOperator.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbbOperator.setFont(font)
        self.cbbOperator.setObjectName("cbbOperator")
        self.horizontalLayout_3.addWidget(self.cbbOperator)
        self.rbnRatio = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnRatio.setMinimumSize(QtCore.QSize(0, 0))
        self.rbnRatio.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.rbnRatio.setFont(font)
        self.rbnRatio.setChecked(True)
        self.rbnRatio.setObjectName("rbnRatio")
        self.horizontalLayout_3.addWidget(self.rbnRatio)
        self.rbnDifference = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnDifference.setMinimumSize(QtCore.QSize(0, 0))
        self.rbnDifference.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.rbnDifference.setFont(font)
        self.rbnDifference.setChecked(False)
        self.rbnDifference.setObjectName("rbnDifference")
        self.horizontalLayout_3.addWidget(self.rbnDifference)
        self.rbnAbsValue = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbnAbsValue.setMinimumSize(QtCore.QSize(0, 0))
        self.rbnAbsValue.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.rbnAbsValue.setFont(font)
        self.rbnAbsValue.setObjectName("rbnAbsValue")
        self.horizontalLayout_3.addWidget(self.rbnAbsValue)
        self.spbValue = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spbValue.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbValue.setFont(font)
        self.spbValue.setSuffix("")
        self.spbValue.setDecimals(2)
        self.spbValue.setMinimum(-10000.0)
        self.spbValue.setMaximum(10000.0)
        self.spbValue.setSingleStep(0.1)
        self.spbValue.setProperty("value", 1.0)
        self.spbValue.setObjectName("spbValue")
        self.horizontalLayout_3.addWidget(self.spbValue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(SearchCriteria)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 110, 158, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnConfirm = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnConfirm.setFont(font)
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout_4.addWidget(self.btnConfirm)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)

        self.retranslateUi(SearchCriteria)
        self.rbnAbsValue.toggled['bool'].connect(self.spbComparedPeriodBegin.setDisabled)
        self.btnConfirm.clicked.connect(SearchCriteria.save_changes)
        self.btnCancel.clicked.connect(SearchCriteria.close)
        self.rbnAbsValue.toggled['bool'].connect(self.spbComparedPeriodEnd.setDisabled)
        self.rbnAbsValue.toggled['bool'].connect(self.cbbComparedLogic.setDisabled)
        self.rbnAbsValue.toggled['bool'].connect(self.cbbComparedField.setDisabled)
        self.spbQueryPeriodEnd.valueChanged['int'].connect(SearchCriteria.update_gui)
        self.spbQueryPeriodBegin.valueChanged['int'].connect(SearchCriteria.update_gui)
        self.spbComparedPeriodBegin.valueChanged['int'].connect(SearchCriteria.update_gui)
        self.spbComparedPeriodEnd.valueChanged['int'].connect(SearchCriteria.update_gui)
        QtCore.QMetaObject.connectSlotsByName(SearchCriteria)

    def retranslateUi(self, SearchCriteria):
        _translate = QtCore.QCoreApplication.translate
        SearchCriteria.setWindowTitle(_translate("SearchCriteria", "筛选条件"))
        self.lblRecent.setText(_translate("SearchCriteria", "过去"))
        self.spbQueryPeriodBegin.setSuffix(_translate("SearchCriteria", "日"))
        self.lblTo1.setText(_translate("SearchCriteria", "到"))
        self.spbQueryPeriodEnd.setSuffix(_translate("SearchCriteria", "日"))
        self.lblComparison.setText(_translate("SearchCriteria", "相比过去"))
        self.spbComparedPeriodBegin.setSuffix(_translate("SearchCriteria", "日"))
        self.lblTo2.setText(_translate("SearchCriteria", "到"))
        self.spbComparedPeriodEnd.setSuffix(_translate("SearchCriteria", "日"))
        self.rbnRatio.setText(_translate("SearchCriteria", "比值"))
        self.rbnDifference.setText(_translate("SearchCriteria", "差值"))
        self.rbnAbsValue.setText(_translate("SearchCriteria", "绝对值"))
        self.btnConfirm.setText(_translate("SearchCriteria", "保存"))
        self.btnCancel.setText(_translate("SearchCriteria", "取消"))
