# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectedPerformance.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectedPerformance(object):
    def setupUi(self, SelectedPerformance):
        SelectedPerformance.setObjectName("SelectedPerformance")
        SelectedPerformance.resize(1062, 399)
        self.tblStockList = QtWidgets.QTableWidget(SelectedPerformance)
        self.tblStockList.setGeometry(QtCore.QRect(10, 48, 1041, 301))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tblStockList.setFont(font)
        self.tblStockList.setObjectName("tblStockList")
        self.tblStockList.setColumnCount(12)
        self.tblStockList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStockList.setHorizontalHeaderItem(11, item)
        self.tblStockList.horizontalHeader().setDefaultSectionSize(60)
        self.tblStockList.horizontalHeader().setSortIndicatorShown(True)
        self.widget = QtWidgets.QWidget(SelectedPerformance)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1041, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSearchDate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblSearchDate.setFont(font)
        self.lblSearchDate.setObjectName("lblSearchDate")
        self.horizontalLayout.addWidget(self.lblSearchDate)
        self.dteSearchDate = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.dteSearchDate.setFont(font)
        self.dteSearchDate.setObjectName("dteSearchDate")
        self.horizontalLayout.addWidget(self.dteSearchDate)
        self.lblLoseThreshold = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblLoseThreshold.setFont(font)
        self.lblLoseThreshold.setObjectName("lblLoseThreshold")
        self.horizontalLayout.addWidget(self.lblLoseThreshold)
        self.spbLoseThreshold = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spbLoseThreshold.setFont(font)
        self.spbLoseThreshold.setProperty("value", 5)
        self.spbLoseThreshold.setObjectName("spbLoseThreshold")
        self.horizontalLayout.addWidget(self.spbLoseThreshold)
        self.lblWinThreshold = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblWinThreshold.setFont(font)
        self.lblWinThreshold.setObjectName("lblWinThreshold")
        self.horizontalLayout.addWidget(self.lblWinThreshold)
        self.spbWinThreshold = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spbWinThreshold.setFont(font)
        self.spbWinThreshold.setMaximum(9999)
        self.spbWinThreshold.setSingleStep(1)
        self.spbWinThreshold.setProperty("value", 10)
        self.spbWinThreshold.setObjectName("spbWinThreshold")
        self.horizontalLayout.addWidget(self.spbWinThreshold)
        self.lblMaxHoldTime = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMaxHoldTime.setFont(font)
        self.lblMaxHoldTime.setObjectName("lblMaxHoldTime")
        self.horizontalLayout.addWidget(self.lblMaxHoldTime)
        self.spbMaxHoldTime = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.spbMaxHoldTime.setFont(font)
        self.spbMaxHoldTime.setMinimum(2)
        self.spbMaxHoldTime.setMaximum(9999)
        self.spbMaxHoldTime.setSingleStep(1)
        self.spbMaxHoldTime.setProperty("value", 20)
        self.spbMaxHoldTime.setObjectName("spbMaxHoldTime")
        self.horizontalLayout.addWidget(self.spbMaxHoldTime)
        self.btnStartCalculation = QtWidgets.QPushButton(self.widget)
        self.btnStartCalculation.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnStartCalculation.setFont(font)
        self.btnStartCalculation.setObjectName("btnStartCalculation")
        self.horizontalLayout.addWidget(self.btnStartCalculation)
        self.widget1 = QtWidgets.QWidget(SelectedPerformance)
        self.widget1.setGeometry(QtCore.QRect(10, 360, 1041, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblNewStockCode = QtWidgets.QLabel(self.widget1)
        self.lblNewStockCode.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lblNewStockCode.setFont(font)
        self.lblNewStockCode.setObjectName("lblNewStockCode")
        self.horizontalLayout_2.addWidget(self.lblNewStockCode)
        self.iptStockCode = QtWidgets.QLineEdit(self.widget1)
        self.iptStockCode.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.iptStockCode.setFont(font)
        self.iptStockCode.setMaxLength(6)
        self.iptStockCode.setObjectName("iptStockCode")
        self.horizontalLayout_2.addWidget(self.iptStockCode)
        self.btnAddStock = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnAddStock.setFont(font)
        self.btnAddStock.setObjectName("btnAddStock")
        self.horizontalLayout_2.addWidget(self.btnAddStock)
        self.btnRemoveStock = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnRemoveStock.setFont(font)
        self.btnRemoveStock.setObjectName("btnRemoveStock")
        self.horizontalLayout_2.addWidget(self.btnRemoveStock)
        self.btnImportStockList = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnImportStockList.setFont(font)
        self.btnImportStockList.setObjectName("btnImportStockList")
        self.horizontalLayout_2.addWidget(self.btnImportStockList)
        self.btnExportStockList = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnExportStockList.setFont(font)
        self.btnExportStockList.setObjectName("btnExportStockList")
        self.horizontalLayout_2.addWidget(self.btnExportStockList)
        self.btnClearStocks = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnClearStocks.setFont(font)
        self.btnClearStocks.setObjectName("btnClearStocks")
        self.horizontalLayout_2.addWidget(self.btnClearStocks)

        self.retranslateUi(SelectedPerformance)
        self.btnStartCalculation.clicked.connect(SelectedPerformance.get_stock_data)
        self.btnImportStockList.clicked.connect(SelectedPerformance.import_stock_list)
        self.btnRemoveStock.clicked.connect(SelectedPerformance.remove_stock_code)
        self.btnAddStock.clicked.connect(SelectedPerformance.add_stock_code)
        self.btnClearStocks.clicked.connect(SelectedPerformance.clear_stock_list)
        self.btnExportStockList.clicked.connect(SelectedPerformance.export_stock_list)
        QtCore.QMetaObject.connectSlotsByName(SelectedPerformance)

    def retranslateUi(self, SelectedPerformance):
        _translate = QtCore.QCoreApplication.translate
        SelectedPerformance.setWindowTitle(_translate("SelectedPerformance", "选股器回测"))
        item = self.tblStockList.horizontalHeaderItem(0)
        item.setText(_translate("SelectedPerformance", "股票代码"))
        item = self.tblStockList.horizontalHeaderItem(1)
        item.setText(_translate("SelectedPerformance", "股票名称"))
        item = self.tblStockList.horizontalHeaderItem(2)
        item.setText(_translate("SelectedPerformance", "当日收盘"))
        item = self.tblStockList.horizontalHeaderItem(3)
        item.setText(_translate("SelectedPerformance", "次日开盘"))
        item = self.tblStockList.horizontalHeaderItem(4)
        item.setText(_translate("SelectedPerformance", "次日收盘"))
        item = self.tblStockList.horizontalHeaderItem(5)
        item.setText(_translate("SelectedPerformance", "3日表现"))
        item = self.tblStockList.horizontalHeaderItem(6)
        item.setText(_translate("SelectedPerformance", "5日表现"))
        item = self.tblStockList.horizontalHeaderItem(7)
        item.setText(_translate("SelectedPerformance", "10日表现"))
        item = self.tblStockList.horizontalHeaderItem(8)
        item.setText(_translate("SelectedPerformance", "至今表现"))
        item = self.tblStockList.horizontalHeaderItem(9)
        item.setText(_translate("SelectedPerformance", "最高涨幅"))
        item = self.tblStockList.horizontalHeaderItem(10)
        item.setText(_translate("SelectedPerformance", "最大回撤"))
        item = self.tblStockList.horizontalHeaderItem(11)
        item.setText(_translate("SelectedPerformance", "最佳策略"))
        self.lblSearchDate.setText(_translate("SelectedPerformance", "选股日期（次日开盘买入）："))
        self.dteSearchDate.setDisplayFormat(_translate("SelectedPerformance", "yyyy-MM-dd"))
        self.lblLoseThreshold.setText(_translate("SelectedPerformance", "止损点"))
        self.spbLoseThreshold.setSuffix(_translate("SelectedPerformance", "%"))
        self.lblWinThreshold.setText(_translate("SelectedPerformance", "止盈点"))
        self.spbWinThreshold.setSuffix(_translate("SelectedPerformance", "%"))
        self.lblMaxHoldTime.setText(_translate("SelectedPerformance", "最长持仓时间"))
        self.spbMaxHoldTime.setSuffix(_translate("SelectedPerformance", "天"))
        self.btnStartCalculation.setText(_translate("SelectedPerformance", "获取回测数据"))
        self.lblNewStockCode.setText(_translate("SelectedPerformance", "股票代码"))
        self.iptStockCode.setText(_translate("SelectedPerformance", "600519"))
        self.btnAddStock.setText(_translate("SelectedPerformance", "添加股票"))
        self.btnRemoveStock.setText(_translate("SelectedPerformance", "删除股票"))
        self.btnImportStockList.setText(_translate("SelectedPerformance", "导入股票列表"))
        self.btnExportStockList.setText(_translate("SelectedPerformance", "导出股票列表"))
        self.btnClearStocks.setText(_translate("SelectedPerformance", "清空列表"))
