# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockFinder.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockFinder(object):
    def setupUi(self, StockFinder):
        StockFinder.setObjectName("StockFinder")
        StockFinder.resize(651, 555)
        self.centralwidget = QtWidgets.QWidget(StockFinder)
        self.centralwidget.setObjectName("centralwidget")
        self.grpSearchRange = QtWidgets.QGroupBox(self.centralwidget)
        self.grpSearchRange.setGeometry(QtCore.QRect(510, 12, 131, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.grpSearchRange.setFont(font)
        self.grpSearchRange.setObjectName("grpSearchRange")
        self.layoutWidget = QtWidgets.QWidget(self.grpSearchRange)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbxShanghaiMain = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxShanghaiMain.setFont(font)
        self.cbxShanghaiMain.setChecked(True)
        self.cbxShanghaiMain.setObjectName("cbxShanghaiMain")
        self.verticalLayout_2.addWidget(self.cbxShanghaiMain)
        self.cbxShenZhenMain = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxShenZhenMain.setFont(font)
        self.cbxShenZhenMain.setChecked(True)
        self.cbxShenZhenMain.setObjectName("cbxShenZhenMain")
        self.verticalLayout_2.addWidget(self.cbxShenZhenMain)
        self.cbxShenZhenSmall = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxShenZhenSmall.setFont(font)
        self.cbxShenZhenSmall.setChecked(True)
        self.cbxShenZhenSmall.setObjectName("cbxShenZhenSmall")
        self.verticalLayout_2.addWidget(self.cbxShenZhenSmall)
        self.cbxShenZhenNew = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxShenZhenNew.setFont(font)
        self.cbxShenZhenNew.setChecked(True)
        self.cbxShenZhenNew.setObjectName("cbxShenZhenNew")
        self.verticalLayout_2.addWidget(self.cbxShenZhenNew)
        self.cbxShanghaiScience = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxShanghaiScience.setFont(font)
        self.cbxShanghaiScience.setChecked(False)
        self.cbxShanghaiScience.setObjectName("cbxShanghaiScience")
        self.verticalLayout_2.addWidget(self.cbxShanghaiScience)
        self.grpCustomCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpCustomCriterias.setEnabled(True)
        self.grpCustomCriterias.setGeometry(QtCore.QRect(10, 12, 491, 161))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.grpCustomCriterias.setFont(font)
        self.grpCustomCriterias.setObjectName("grpCustomCriterias")
        self.lstCriteriaItems = QtWidgets.QListWidget(self.grpCustomCriterias)
        self.lstCriteriaItems.setGeometry(QtCore.QRect(10, 21, 471, 100))
        self.lstCriteriaItems.setObjectName("lstCriteriaItems")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpCustomCriterias)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 127, 477, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAddCriteria.setObjectName("btnAddCriteria")
        self.horizontalLayout.addWidget(self.btnAddCriteria)
        self.btnRemoveCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnRemoveCriteria.setObjectName("btnRemoveCriteria")
        self.horizontalLayout.addWidget(self.btnRemoveCriteria)
        self.btnEditCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnEditCriteria.setObjectName("btnEditCriteria")
        self.horizontalLayout.addWidget(self.btnEditCriteria)
        self.btnResetCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnResetCriteria.setObjectName("btnResetCriteria")
        self.horizontalLayout.addWidget(self.btnResetCriteria)
        self.btnExportCustomConfig = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExportCustomConfig.setFont(font)
        self.btnExportCustomConfig.setObjectName("btnExportCustomConfig")
        self.horizontalLayout.addWidget(self.btnExportCustomConfig)
        self.btnImportCustomConfig = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnImportCustomConfig.setFont(font)
        self.btnImportCustomConfig.setObjectName("btnImportCustomConfig")
        self.horizontalLayout.addWidget(self.btnImportCustomConfig)
        self.grpBasicCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBasicCriterias.setGeometry(QtCore.QRect(10, 180, 351, 341))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.grpBasicCriterias.setFont(font)
        self.grpBasicCriterias.setObjectName("grpBasicCriterias")
        self.layoutWidget2 = QtWidgets.QWidget(self.grpBasicCriterias)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 23, 328, 306))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbxPriceEarning = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxPriceEarning.setFont(font)
        self.cbxPriceEarning.setChecked(True)
        self.cbxPriceEarning.setObjectName("cbxPriceEarning")
        self.horizontalLayout_2.addWidget(self.cbxPriceEarning)
        self.spbPriceEarningMin = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbPriceEarningMin.setFont(font)
        self.spbPriceEarningMin.setMinimum(0)
        self.spbPriceEarningMin.setMaximum(100)
        self.spbPriceEarningMin.setProperty("value", 10)
        self.spbPriceEarningMin.setObjectName("spbPriceEarningMin")
        self.horizontalLayout_2.addWidget(self.spbPriceEarningMin)
        self.lblPriceEarningMax = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblPriceEarningMax.setFont(font)
        self.lblPriceEarningMax.setObjectName("lblPriceEarningMax")
        self.horizontalLayout_2.addWidget(self.lblPriceEarningMax)
        self.spbPriceEarningMax = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbPriceEarningMax.setFont(font)
        self.spbPriceEarningMax.setMinimum(5)
        self.spbPriceEarningMax.setMaximum(1000)
        self.spbPriceEarningMax.setProperty("value", 50)
        self.spbPriceEarningMax.setObjectName("spbPriceEarningMax")
        self.horizontalLayout_2.addWidget(self.spbPriceEarningMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbxPriceBook = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxPriceBook.setFont(font)
        self.cbxPriceBook.setChecked(True)
        self.cbxPriceBook.setObjectName("cbxPriceBook")
        self.horizontalLayout_5.addWidget(self.cbxPriceBook)
        self.spbPriceBookMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbPriceBookMin.setFont(font)
        self.spbPriceBookMin.setDecimals(1)
        self.spbPriceBookMin.setMinimum(0.0)
        self.spbPriceBookMin.setMaximum(10.0)
        self.spbPriceBookMin.setSingleStep(0.5)
        self.spbPriceBookMin.setProperty("value", 1.0)
        self.spbPriceBookMin.setObjectName("spbPriceBookMin")
        self.horizontalLayout_5.addWidget(self.spbPriceBookMin)
        self.lblPriceBookMax = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblPriceBookMax.setFont(font)
        self.lblPriceBookMax.setObjectName("lblPriceBookMax")
        self.horizontalLayout_5.addWidget(self.lblPriceBookMax)
        self.spbPriceBookMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbPriceBookMax.setFont(font)
        self.spbPriceBookMax.setDecimals(1)
        self.spbPriceBookMax.setMinimum(1.0)
        self.spbPriceBookMax.setSingleStep(0.5)
        self.spbPriceBookMax.setProperty("value", 5.0)
        self.spbPriceBookMax.setObjectName("spbPriceBookMax")
        self.horizontalLayout_5.addWidget(self.spbPriceBookMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbxTotalShare = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxTotalShare.setFont(font)
        self.cbxTotalShare.setChecked(True)
        self.cbxTotalShare.setObjectName("cbxTotalShare")
        self.horizontalLayout_7.addWidget(self.cbxTotalShare)
        self.spbTotalShareMin = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbTotalShareMin.setFont(font)
        self.spbTotalShareMin.setMinimum(0)
        self.spbTotalShareMin.setMaximum(10)
        self.spbTotalShareMin.setProperty("value", 1)
        self.spbTotalShareMin.setObjectName("spbTotalShareMin")
        self.horizontalLayout_7.addWidget(self.spbTotalShareMin)
        self.lblTotalShareMax = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblTotalShareMax.setFont(font)
        self.lblTotalShareMax.setObjectName("lblTotalShareMax")
        self.horizontalLayout_7.addWidget(self.lblTotalShareMax)
        self.spbTotalShareMax = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbTotalShareMax.setFont(font)
        self.spbTotalShareMax.setMinimum(1)
        self.spbTotalShareMax.setMaximum(10000)
        self.spbTotalShareMax.setProperty("value", 10)
        self.spbTotalShareMax.setObjectName("spbTotalShareMax")
        self.horizontalLayout_7.addWidget(self.spbTotalShareMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbxTotalAssets = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxTotalAssets.setFont(font)
        self.cbxTotalAssets.setChecked(True)
        self.cbxTotalAssets.setObjectName("cbxTotalAssets")
        self.horizontalLayout_6.addWidget(self.cbxTotalAssets)
        self.spbTotalAssetsMin = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbTotalAssetsMin.setFont(font)
        self.spbTotalAssetsMin.setMinimum(1)
        self.spbTotalAssetsMin.setMaximum(1000)
        self.spbTotalAssetsMin.setProperty("value", 10)
        self.spbTotalAssetsMin.setObjectName("spbTotalAssetsMin")
        self.horizontalLayout_6.addWidget(self.spbTotalAssetsMin)
        self.lblTotalAssetsMax = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblTotalAssetsMax.setFont(font)
        self.lblTotalAssetsMax.setObjectName("lblTotalAssetsMax")
        self.horizontalLayout_6.addWidget(self.lblTotalAssetsMax)
        self.spbTotalAssetsMax = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbTotalAssetsMax.setFont(font)
        self.spbTotalAssetsMax.setMinimum(10)
        self.spbTotalAssetsMax.setMaximum(99999)
        self.spbTotalAssetsMax.setProperty("value", 100)
        self.spbTotalAssetsMax.setObjectName("spbTotalAssetsMax")
        self.horizontalLayout_6.addWidget(self.spbTotalAssetsMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxGrossProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxGrossProfit.setFont(font)
        self.cbxGrossProfit.setChecked(True)
        self.cbxGrossProfit.setObjectName("cbxGrossProfit")
        self.horizontalLayout_4.addWidget(self.cbxGrossProfit)
        self.spbGrossProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbGrossProfit.setFont(font)
        self.spbGrossProfit.setMinimum(-20)
        self.spbGrossProfit.setMaximum(100)
        self.spbGrossProfit.setProperty("value", 30)
        self.spbGrossProfit.setObjectName("spbGrossProfit")
        self.horizontalLayout_4.addWidget(self.spbGrossProfit)
        self.cbxNetProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxNetProfit.setFont(font)
        self.cbxNetProfit.setChecked(True)
        self.cbxNetProfit.setObjectName("cbxNetProfit")
        self.horizontalLayout_4.addWidget(self.cbxNetProfit)
        self.spbNetProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbNetProfit.setFont(font)
        self.spbNetProfit.setMinimum(-20)
        self.spbNetProfit.setMaximum(100)
        self.spbNetProfit.setProperty("value", 10)
        self.spbNetProfit.setObjectName("spbNetProfit")
        self.horizontalLayout_4.addWidget(self.spbNetProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxIncomeIncrease = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxIncomeIncrease.setFont(font)
        self.cbxIncomeIncrease.setChecked(True)
        self.cbxIncomeIncrease.setObjectName("cbxIncomeIncrease")
        self.horizontalLayout_9.addWidget(self.cbxIncomeIncrease)
        self.spbIncomeIncrease = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbIncomeIncrease.setFont(font)
        self.spbIncomeIncrease.setMinimum(-20)
        self.spbIncomeIncrease.setMaximum(100)
        self.spbIncomeIncrease.setProperty("value", 10)
        self.spbIncomeIncrease.setObjectName("spbIncomeIncrease")
        self.horizontalLayout_9.addWidget(self.spbIncomeIncrease)
        self.cbxProfitIncrease = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxProfitIncrease.setFont(font)
        self.cbxProfitIncrease.setChecked(True)
        self.cbxProfitIncrease.setObjectName("cbxProfitIncrease")
        self.horizontalLayout_9.addWidget(self.cbxProfitIncrease)
        self.spbProfitIncrease = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbProfitIncrease.setFont(font)
        self.spbProfitIncrease.setMinimum(-20)
        self.spbProfitIncrease.setMaximum(100)
        self.spbProfitIncrease.setProperty("value", 10)
        self.spbProfitIncrease.setObjectName("spbProfitIncrease")
        self.horizontalLayout_9.addWidget(self.spbProfitIncrease)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbxNetAssetProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxNetAssetProfit.setFont(font)
        self.cbxNetAssetProfit.setChecked(True)
        self.cbxNetAssetProfit.setObjectName("cbxNetAssetProfit")
        self.horizontalLayout_8.addWidget(self.cbxNetAssetProfit)
        self.spbNetAssetProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbNetAssetProfit.setFont(font)
        self.spbNetAssetProfit.setMinimum(0)
        self.spbNetAssetProfit.setMaximum(100)
        self.spbNetAssetProfit.setProperty("value", 5)
        self.spbNetAssetProfit.setObjectName("spbNetAssetProfit")
        self.horizontalLayout_8.addWidget(self.spbNetAssetProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cbxTotalHolders = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxTotalHolders.setFont(font)
        self.cbxTotalHolders.setChecked(True)
        self.cbxTotalHolders.setObjectName("cbxTotalHolders")
        self.horizontalLayout_10.addWidget(self.cbxTotalHolders)
        self.spbTotalHoldersMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbTotalHoldersMin.setFont(font)
        self.spbTotalHoldersMin.setDecimals(1)
        self.spbTotalHoldersMin.setMinimum(0.0)
        self.spbTotalHoldersMin.setMaximum(10.0)
        self.spbTotalHoldersMin.setSingleStep(0.5)
        self.spbTotalHoldersMin.setProperty("value", 1.0)
        self.spbTotalHoldersMin.setObjectName("spbTotalHoldersMin")
        self.horizontalLayout_10.addWidget(self.spbTotalHoldersMin)
        self.lblTotalHoldersMax = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblTotalHoldersMax.setFont(font)
        self.lblTotalHoldersMax.setObjectName("lblTotalHoldersMax")
        self.horizontalLayout_10.addWidget(self.lblTotalHoldersMax)
        self.spbTotalHoldersMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbTotalHoldersMax.setFont(font)
        self.spbTotalHoldersMax.setDecimals(1)
        self.spbTotalHoldersMax.setMinimum(1.0)
        self.spbTotalHoldersMax.setProperty("value", 10.0)
        self.spbTotalHoldersMax.setObjectName("spbTotalHoldersMax")
        self.horizontalLayout_10.addWidget(self.spbTotalHoldersMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxIncludeStStock = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cbxIncludeStStock.setObjectName("cbxIncludeStStock")
        self.horizontalLayout_3.addWidget(self.cbxIncludeStStock)
        self.cbxIncludeNewStock = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cbxIncludeNewStock.setChecked(True)
        self.cbxIncludeNewStock.setObjectName("cbxIncludeNewStock")
        self.horizontalLayout_3.addWidget(self.cbxIncludeNewStock)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnExportBasicConfig = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExportBasicConfig.setFont(font)
        self.btnExportBasicConfig.setObjectName("btnExportBasicConfig")
        self.horizontalLayout_16.addWidget(self.btnExportBasicConfig)
        self.btnImportBasicConfig = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnImportBasicConfig.setFont(font)
        self.btnImportBasicConfig.setObjectName("btnImportBasicConfig")
        self.horizontalLayout_16.addWidget(self.btnImportBasicConfig)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.grpTechnicalCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpTechnicalCriterias.setGeometry(QtCore.QRect(370, 180, 271, 251))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.grpTechnicalCriterias.setFont(font)
        self.grpTechnicalCriterias.setObjectName("grpTechnicalCriterias")
        self.layoutWidget3 = QtWidgets.QWidget(self.grpTechnicalCriterias)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 20, 246, 221))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.spbTechnicalTimePeriod = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.spbTechnicalTimePeriod.setFont(font)
        self.spbTechnicalTimePeriod.setMinimum(1)
        self.spbTechnicalTimePeriod.setMaximum(10)
        self.spbTechnicalTimePeriod.setProperty("value", 1)
        self.spbTechnicalTimePeriod.setObjectName("spbTechnicalTimePeriod")
        self.horizontalLayout_18.addWidget(self.spbTechnicalTimePeriod)
        self.lblTechnicalTimePeriod = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblTechnicalTimePeriod.setFont(font)
        self.lblTechnicalTimePeriod.setObjectName("lblTechnicalTimePeriod")
        self.horizontalLayout_18.addWidget(self.lblTechnicalTimePeriod)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cbxMacdEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxMacdEnabled.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbxMacdEnabled.setChecked(True)
        self.cbxMacdEnabled.setObjectName("cbxMacdEnabled")
        self.horizontalLayout_11.addWidget(self.cbxMacdEnabled)
        self.cbbMacdBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMacdBehaviour.setObjectName("cbbMacdBehaviour")
        self.horizontalLayout_11.addWidget(self.cbbMacdBehaviour)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbxBollEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxBollEnabled.setChecked(True)
        self.cbxBollEnabled.setObjectName("cbxBollEnabled")
        self.horizontalLayout_12.addWidget(self.cbxBollEnabled)
        self.cbbBollBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbBollBehaviour.setObjectName("cbbBollBehaviour")
        self.horizontalLayout_12.addWidget(self.cbbBollBehaviour)
        self.cbbBollTrack = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbBollTrack.setObjectName("cbbBollTrack")
        self.horizontalLayout_12.addWidget(self.cbbBollTrack)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cbxExpmaEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxExpmaEnabled.setChecked(True)
        self.cbxExpmaEnabled.setObjectName("cbxExpmaEnabled")
        self.horizontalLayout_13.addWidget(self.cbxExpmaEnabled)
        self.cbbExpmaBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbExpmaBehaviour.setMinimumSize(QtCore.QSize(150, 0))
        self.cbbExpmaBehaviour.setObjectName("cbbExpmaBehaviour")
        self.horizontalLayout_13.addWidget(self.cbbExpmaBehaviour)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cbxMaEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxMaEnabled.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cbxMaEnabled.setChecked(True)
        self.cbxMaEnabled.setObjectName("cbxMaEnabled")
        self.horizontalLayout_14.addWidget(self.cbxMaEnabled)
        self.spbMaShort = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spbMaShort.setMinimum(5)
        self.spbMaShort.setMaximum(20)
        self.spbMaShort.setObjectName("spbMaShort")
        self.horizontalLayout_14.addWidget(self.spbMaShort)
        self.cbbMaBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMaBehaviour.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cbbMaBehaviour.setObjectName("cbbMaBehaviour")
        self.horizontalLayout_14.addWidget(self.cbbMaBehaviour)
        self.spbMaLong = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spbMaLong.setMinimum(10)
        self.spbMaLong.setMaximum(60)
        self.spbMaLong.setObjectName("spbMaLong")
        self.horizontalLayout_14.addWidget(self.spbMaLong)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cbxTrixEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxTrixEnabled.setChecked(True)
        self.cbxTrixEnabled.setObjectName("cbxTrixEnabled")
        self.horizontalLayout_15.addWidget(self.cbxTrixEnabled)
        self.cbbTrixBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbTrixBehaviour.setObjectName("cbbTrixBehaviour")
        self.horizontalLayout_15.addWidget(self.cbbTrixBehaviour)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btnExportTechnicalConfig = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnExportTechnicalConfig.setFont(font)
        self.btnExportTechnicalConfig.setObjectName("btnExportTechnicalConfig")
        self.horizontalLayout_17.addWidget(self.btnExportTechnicalConfig)
        self.btnImportTechnicalConfig = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnImportTechnicalConfig.setFont(font)
        self.btnImportTechnicalConfig.setObjectName("btnImportTechnicalConfig")
        self.horizontalLayout_17.addWidget(self.btnImportTechnicalConfig)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.cbxTechnicalCriteriasEnabled = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxTechnicalCriteriasEnabled.setGeometry(QtCore.QRect(446, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxTechnicalCriteriasEnabled.setFont(font)
        self.cbxTechnicalCriteriasEnabled.setText("")
        self.cbxTechnicalCriteriasEnabled.setChecked(True)
        self.cbxTechnicalCriteriasEnabled.setObjectName("cbxTechnicalCriteriasEnabled")
        self.cbxBasicCriteriasEnabled = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxBasicCriteriasEnabled.setGeometry(QtCore.QRect(86, 181, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.cbxBasicCriteriasEnabled.setFont(font)
        self.cbxBasicCriteriasEnabled.setText("")
        self.cbxBasicCriteriasEnabled.setChecked(True)
        self.cbxBasicCriteriasEnabled.setObjectName("cbxBasicCriteriasEnabled")
        self.lblGetStockReminder = QtWidgets.QLabel(self.centralwidget)
        self.lblGetStockReminder.setGeometry(QtCore.QRect(380, 431, 243, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblGetStockReminder.setFont(font)
        self.lblGetStockReminder.setObjectName("lblGetStockReminder")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(370, 458, 271, 62))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btnGetAllStockList = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnGetAllStockList.setFont(font)
        self.btnGetAllStockList.setObjectName("btnGetAllStockList")
        self.horizontalLayout_19.addWidget(self.btnGetAllStockList)
        self.btnGetAllStockData = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btnGetAllStockData.setFont(font)
        self.btnGetAllStockData.setObjectName("btnGetAllStockData")
        self.horizontalLayout_19.addWidget(self.btnGetAllStockData)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lblSearchDate = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lblSearchDate.setFont(font)
        self.lblSearchDate.setObjectName("lblSearchDate")
        self.horizontalLayout_20.addWidget(self.lblSearchDate)
        self.dteSearchDate = QtWidgets.QDateEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dteSearchDate.setFont(font)
        self.dteSearchDate.setObjectName("dteSearchDate")
        self.horizontalLayout_20.addWidget(self.dteSearchDate)
        self.btnStartSearch = QtWidgets.QPushButton(self.layoutWidget4)
        self.btnStartSearch.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartSearch.setFont(font)
        self.btnStartSearch.setObjectName("btnStartSearch")
        self.horizontalLayout_20.addWidget(self.btnStartSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        StockFinder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockFinder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 22))
        self.menubar.setObjectName("menubar")
        self.mnuOtherCriterias = QtWidgets.QMenu(self.menubar)
        self.mnuOtherCriterias.setObjectName("mnuOtherCriterias")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        StockFinder.setMenuBar(self.menubar)
        self.actHoldersStatus = QtWidgets.QAction(StockFinder)
        self.actHoldersStatus.setObjectName("actHoldersStatus")
        self.actBatchSelector = QtWidgets.QAction(StockFinder)
        self.actBatchSelector.setObjectName("actBatchSelector")
        self.mnuOtherCriterias.addAction(self.actHoldersStatus)
        self.menu.addAction(self.actBatchSelector)
        self.menubar.addAction(self.mnuOtherCriterias.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(StockFinder)
        self.btnStartSearch.clicked.connect(StockFinder.search_all_stocks)
        self.btnGetAllStockData.clicked.connect(StockFinder.export_all_stock_data)
        self.cbxPriceEarning.toggled['bool'].connect(self.spbPriceEarningMin.setEnabled)
        self.cbxPriceEarning.toggled['bool'].connect(self.spbPriceEarningMax.setEnabled)
        self.cbxTotalShare.toggled['bool'].connect(self.spbTotalShareMin.setEnabled)
        self.cbxTotalShare.toggled['bool'].connect(self.spbTotalShareMax.setEnabled)
        self.cbxTotalAssets.toggled['bool'].connect(self.spbTotalAssetsMin.setEnabled)
        self.cbxTotalAssets.toggled['bool'].connect(self.spbTotalAssetsMax.setEnabled)
        self.cbxBasicCriteriasEnabled.toggled['bool'].connect(self.grpBasicCriterias.setEnabled)
        self.btnAddCriteria.clicked.connect(StockFinder.add_criteria_item)
        self.btnEditCriteria.clicked.connect(StockFinder.modify_criteria_item)
        self.btnRemoveCriteria.clicked.connect(StockFinder.remove_criteria_item)
        self.btnResetCriteria.clicked.connect(StockFinder.reset_criteria_items)
        self.btnExportCustomConfig.clicked.connect(StockFinder.export_custom_config)
        self.btnImportCustomConfig.clicked.connect(StockFinder.import_custom_config)
        self.cbxGrossProfit.toggled['bool'].connect(self.spbGrossProfit.setEnabled)
        self.cbxNetProfit.toggled['bool'].connect(self.spbNetProfit.setEnabled)
        self.cbxIncomeIncrease.toggled['bool'].connect(self.spbIncomeIncrease.setEnabled)
        self.cbxProfitIncrease.toggled['bool'].connect(self.spbProfitIncrease.setEnabled)
        self.cbxNetAssetProfit.toggled['bool'].connect(self.spbNetAssetProfit.setEnabled)
        self.cbxTotalHolders.toggled['bool'].connect(self.spbTotalHoldersMin.setEnabled)
        self.cbxTotalHolders.toggled['bool'].connect(self.spbTotalHoldersMax.setEnabled)
        self.lstCriteriaItems.itemDoubleClicked['QListWidgetItem*'].connect(StockFinder.edit_selected_item)
        self.btnExportBasicConfig.clicked.connect(StockFinder.export_basic_config)
        self.btnImportBasicConfig.clicked.connect(StockFinder.import_basic_config)
        self.actHoldersStatus.triggered.connect(StockFinder.search_by_holders_structure)
        self.cbxMacdEnabled.toggled['bool'].connect(self.cbbMacdBehaviour.setEnabled)
        self.cbxBollEnabled.toggled['bool'].connect(self.cbbBollBehaviour.setEnabled)
        self.cbxBollEnabled.toggled['bool'].connect(self.cbbBollTrack.setEnabled)
        self.cbxExpmaEnabled.toggled['bool'].connect(self.cbbExpmaBehaviour.setEnabled)
        self.cbxTrixEnabled.toggled['bool'].connect(self.cbbTrixBehaviour.setEnabled)
        self.btnExportTechnicalConfig.clicked.connect(StockFinder.export_technical_config)
        self.btnImportTechnicalConfig.clicked.connect(StockFinder.import_technical_config)
        self.cbxTechnicalCriteriasEnabled.toggled['bool'].connect(self.grpTechnicalCriterias.setEnabled)
        self.btnGetAllStockList.clicked.connect(StockFinder.export_all_stock_list)
        self.actBatchSelector.triggered.connect(StockFinder.run_batch_searcher)
        self.cbxMaEnabled.toggled['bool'].connect(self.spbMaShort.setEnabled)
        self.cbxMaEnabled.toggled['bool'].connect(self.cbbMaBehaviour.setEnabled)
        self.cbxMaEnabled.toggled['bool'].connect(self.spbMaLong.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StockFinder)

    def retranslateUi(self, StockFinder):
        _translate = QtCore.QCoreApplication.translate
        StockFinder.setWindowTitle(_translate("StockFinder", "智能选股器"))
        self.grpSearchRange.setTitle(_translate("StockFinder", "搜索范围"))
        self.cbxShanghaiMain.setText(_translate("StockFinder", "上海主板"))
        self.cbxShenZhenMain.setText(_translate("StockFinder", "深圳主板"))
        self.cbxShenZhenSmall.setText(_translate("StockFinder", "中小板"))
        self.cbxShenZhenNew.setText(_translate("StockFinder", "创业板"))
        self.cbxShanghaiScience.setText(_translate("StockFinder", "科创板"))
        self.grpCustomCriterias.setTitle(_translate("StockFinder", "自定义指标"))
        self.btnAddCriteria.setText(_translate("StockFinder", "添加"))
        self.btnRemoveCriteria.setText(_translate("StockFinder", "删除"))
        self.btnEditCriteria.setText(_translate("StockFinder", "编辑"))
        self.btnResetCriteria.setText(_translate("StockFinder", "清空"))
        self.btnExportCustomConfig.setText(_translate("StockFinder", "导出"))
        self.btnImportCustomConfig.setText(_translate("StockFinder", "导入"))
        self.grpBasicCriterias.setTitle(_translate("StockFinder", "基本面指标"))
        self.cbxPriceEarning.setText(_translate("StockFinder", "市盈率最低"))
        self.spbPriceEarningMin.setSuffix(_translate("StockFinder", "倍"))
        self.lblPriceEarningMax.setText(_translate("StockFinder", "最高"))
        self.spbPriceEarningMax.setSuffix(_translate("StockFinder", "倍"))
        self.cbxPriceBook.setText(_translate("StockFinder", "市净率最低"))
        self.spbPriceBookMin.setSuffix(_translate("StockFinder", "倍"))
        self.lblPriceBookMax.setText(_translate("StockFinder", "最高"))
        self.spbPriceBookMax.setSuffix(_translate("StockFinder", "倍"))
        self.cbxTotalShare.setText(_translate("StockFinder", "总股本最小"))
        self.spbTotalShareMin.setSuffix(_translate("StockFinder", "亿"))
        self.lblTotalShareMax.setText(_translate("StockFinder", "最大"))
        self.spbTotalShareMax.setSuffix(_translate("StockFinder", "亿"))
        self.cbxTotalAssets.setText(_translate("StockFinder", "市值最小"))
        self.spbTotalAssetsMin.setSuffix(_translate("StockFinder", "亿"))
        self.lblTotalAssetsMax.setText(_translate("StockFinder", "最大"))
        self.spbTotalAssetsMax.setSuffix(_translate("StockFinder", "亿"))
        self.cbxGrossProfit.setText(_translate("StockFinder", "毛利率大于"))
        self.spbGrossProfit.setSuffix(_translate("StockFinder", "%"))
        self.cbxNetProfit.setText(_translate("StockFinder", "净利率大于"))
        self.spbNetProfit.setSuffix(_translate("StockFinder", "%"))
        self.cbxIncomeIncrease.setText(_translate("StockFinder", "收入增长大于"))
        self.spbIncomeIncrease.setSuffix(_translate("StockFinder", "%"))
        self.cbxProfitIncrease.setText(_translate("StockFinder", "利润增长大于"))
        self.spbProfitIncrease.setSuffix(_translate("StockFinder", "%"))
        self.cbxNetAssetProfit.setText(_translate("StockFinder", "净资产收益率大于"))
        self.spbNetAssetProfit.setSuffix(_translate("StockFinder", "%"))
        self.cbxTotalHolders.setText(_translate("StockFinder", "股东人数最少"))
        self.spbTotalHoldersMin.setSuffix(_translate("StockFinder", "万人"))
        self.lblTotalHoldersMax.setText(_translate("StockFinder", "最多"))
        self.spbTotalHoldersMax.setSuffix(_translate("StockFinder", "万人"))
        self.cbxIncludeStStock.setText(_translate("StockFinder", "包含ST股"))
        self.cbxIncludeNewStock.setText(_translate("StockFinder", "包含上市半年内次新股"))
        self.btnExportBasicConfig.setText(_translate("StockFinder", "保存"))
        self.btnImportBasicConfig.setText(_translate("StockFinder", "载入"))
        self.grpTechnicalCriterias.setTitle(_translate("StockFinder", "技术面指标"))
        self.spbTechnicalTimePeriod.setSuffix(_translate("StockFinder", "日内"))
        self.spbTechnicalTimePeriod.setPrefix(_translate("StockFinder", "最近"))
        self.lblTechnicalTimePeriod.setText(_translate("StockFinder", "指标出现以下信号"))
        self.cbxMacdEnabled.setText(_translate("StockFinder", "MACD"))
        self.cbxBollEnabled.setText(_translate("StockFinder", "BOLL"))
        self.cbxExpmaEnabled.setText(_translate("StockFinder", "EXPMA"))
        self.cbxMaEnabled.setText(_translate("StockFinder", "均线"))
        self.spbMaShort.setSuffix(_translate("StockFinder", "日"))
        self.spbMaLong.setSuffix(_translate("StockFinder", "日"))
        self.cbxTrixEnabled.setText(_translate("StockFinder", "TRIX"))
        self.btnExportTechnicalConfig.setText(_translate("StockFinder", "保存"))
        self.btnImportTechnicalConfig.setText(_translate("StockFinder", "载入"))
        self.lblGetStockReminder.setText(_translate("StockFinder", "每日请先获取最新K线图，16:00更新当日数据"))
        self.btnGetAllStockList.setText(_translate("StockFinder", "获取全部股票列表"))
        self.btnGetAllStockData.setText(_translate("StockFinder", "获取历史日K线"))
        self.lblSearchDate.setText(_translate("StockFinder", "选股日期"))
        self.dteSearchDate.setDisplayFormat(_translate("StockFinder", "yyyy-MM-dd"))
        self.btnStartSearch.setText(_translate("StockFinder", "开始搜索选股"))
        self.mnuOtherCriterias.setTitle(_translate("StockFinder", "其他指标"))
        self.menu.setTitle(_translate("StockFinder", "自动选股"))
        self.actHoldersStatus.setText(_translate("StockFinder", "十大流通股东"))
        self.actBatchSelector.setText(_translate("StockFinder", "定时批量选股"))
