# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockAnalyzer(object):
    def setupUi(self, StockAnalyzer):
        StockAnalyzer.setObjectName("StockAnalyzer")
        StockAnalyzer.resize(733, 312)
        self.centralwidget = QtWidgets.QWidget(StockAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.grpStockPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpStockPerformance.setGeometry(QtCore.QRect(10, 40, 171, 221))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpStockPerformance.setFont(font)
        self.grpStockPerformance.setObjectName("grpStockPerformance")
        self.layoutWidget = QtWidgets.QWidget(self.grpStockPerformance)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 20, 151, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblStockIntervalOpen = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalOpen.setFont(font)
        self.lblStockIntervalOpen.setObjectName("lblStockIntervalOpen")
        self.verticalLayout.addWidget(self.lblStockIntervalOpen)
        self.lblStockIntervalClose = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalClose.setFont(font)
        self.lblStockIntervalClose.setObjectName("lblStockIntervalClose")
        self.verticalLayout.addWidget(self.lblStockIntervalClose)
        self.lblStockIntervalHigh = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalHigh.setFont(font)
        self.lblStockIntervalHigh.setObjectName("lblStockIntervalHigh")
        self.verticalLayout.addWidget(self.lblStockIntervalHigh)
        self.lblStockIntervalLow = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalLow.setFont(font)
        self.lblStockIntervalLow.setObjectName("lblStockIntervalLow")
        self.verticalLayout.addWidget(self.lblStockIntervalLow)
        self.lblStockIntervalAverage = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalAverage.setFont(font)
        self.lblStockIntervalAverage.setObjectName("lblStockIntervalAverage")
        self.verticalLayout.addWidget(self.lblStockIntervalAverage)
        self.lblStockIntervalTotal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalTotal.setFont(font)
        self.lblStockIntervalTotal.setObjectName("lblStockIntervalTotal")
        self.verticalLayout.addWidget(self.lblStockIntervalTotal)
        self.lblStockIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalAveragePoint.setFont(font)
        self.lblStockIntervalAveragePoint.setObjectName("lblStockIntervalAveragePoint")
        self.verticalLayout.addWidget(self.lblStockIntervalAveragePoint)
        self.lblStockUpProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockUpProbability.setFont(font)
        self.lblStockUpProbability.setObjectName("lblStockUpProbability")
        self.verticalLayout.addWidget(self.lblStockUpProbability)
        self.lblWinMarket = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblWinMarket.setFont(font)
        self.lblWinMarket.setObjectName("lblWinMarket")
        self.verticalLayout.addWidget(self.lblWinMarket)
        self.grpMarketPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpMarketPerformance.setGeometry(QtCore.QRect(190, 40, 171, 221))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpMarketPerformance.setFont(font)
        self.grpMarketPerformance.setObjectName("grpMarketPerformance")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpMarketPerformance)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 151, 191))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblMarketIntervalOpen = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalOpen.setFont(font)
        self.lblMarketIntervalOpen.setObjectName("lblMarketIntervalOpen")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalOpen)
        self.lblMarketIntervalClose = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalClose.setFont(font)
        self.lblMarketIntervalClose.setObjectName("lblMarketIntervalClose")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalClose)
        self.lblMarketIntervalHigh = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalHigh.setFont(font)
        self.lblMarketIntervalHigh.setObjectName("lblMarketIntervalHigh")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalHigh)
        self.lblMarketIntervalLow = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalLow.setFont(font)
        self.lblMarketIntervalLow.setObjectName("lblMarketIntervalLow")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalLow)
        self.lblMarketIntervalAverage = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalAverage.setFont(font)
        self.lblMarketIntervalAverage.setObjectName("lblMarketIntervalAverage")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAverage)
        self.lblMarketIntervalTotal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalTotal.setFont(font)
        self.lblMarketIntervalTotal.setObjectName("lblMarketIntervalTotal")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalTotal)
        self.lblMarketIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalAveragePoint.setFont(font)
        self.lblMarketIntervalAveragePoint.setObjectName("lblMarketIntervalAveragePoint")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAveragePoint)
        self.lblMarketUpProbability = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketUpProbability.setFont(font)
        self.lblMarketUpProbability.setObjectName("lblMarketUpProbability")
        self.verticalLayout_2.addWidget(self.lblMarketUpProbability)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(370, 38, 351, 241))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 18, 161, 211))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblAverageTurn = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageTurn.setFont(font)
        self.lblAverageTurn.setObjectName("lblAverageTurn")
        self.verticalLayout_6.addWidget(self.lblAverageTurn)
        self.lblAverageAmplitude = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageAmplitude.setFont(font)
        self.lblAverageAmplitude.setObjectName("lblAverageAmplitude")
        self.verticalLayout_6.addWidget(self.lblAverageAmplitude)
        self.lblAverageCloseUp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageCloseUp.setFont(font)
        self.lblAverageCloseUp.setObjectName("lblAverageCloseUp")
        self.verticalLayout_6.addWidget(self.lblAverageCloseUp)
        self.lblAverageHighWhenUp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageHighWhenUp.setFont(font)
        self.lblAverageHighWhenUp.setObjectName("lblAverageHighWhenUp")
        self.verticalLayout_6.addWidget(self.lblAverageHighWhenUp)
        self.lblAverageLowWhenUp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageLowWhenUp.setFont(font)
        self.lblAverageLowWhenUp.setObjectName("lblAverageLowWhenUp")
        self.verticalLayout_6.addWidget(self.lblAverageLowWhenUp)
        self.lblAverageFallbackAmp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageFallbackAmp.setFont(font)
        self.lblAverageFallbackAmp.setObjectName("lblAverageFallbackAmp")
        self.verticalLayout_6.addWidget(self.lblAverageFallbackAmp)
        self.lblAverageCloseDown = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageCloseDown.setFont(font)
        self.lblAverageCloseDown.setObjectName("lblAverageCloseDown")
        self.verticalLayout_6.addWidget(self.lblAverageCloseDown)
        self.lblAverageHighWhenDown = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageHighWhenDown.setFont(font)
        self.lblAverageHighWhenDown.setObjectName("lblAverageHighWhenDown")
        self.verticalLayout_6.addWidget(self.lblAverageHighWhenDown)
        self.lblAverageLowWhenDown = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageLowWhenDown.setFont(font)
        self.lblAverageLowWhenDown.setObjectName("lblAverageLowWhenDown")
        self.verticalLayout_6.addWidget(self.lblAverageLowWhenDown)
        self.lblAverageBounceAmp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageBounceAmp.setFont(font)
        self.lblAverageBounceAmp.setObjectName("lblAverageBounceAmp")
        self.verticalLayout_6.addWidget(self.lblAverageBounceAmp)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(180, 20, 161, 211))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblInverseMarketUp = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInverseMarketUp.setFont(font)
        self.lblInverseMarketUp.setObjectName("lblInverseMarketUp")
        self.verticalLayout_9.addWidget(self.lblInverseMarketUp)
        self.lblInverseMarketDown = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInverseMarketDown.setFont(font)
        self.lblInverseMarketDown.setObjectName("lblInverseMarketDown")
        self.verticalLayout_9.addWidget(self.lblInverseMarketDown)
        self.lblHighOpenHighClose = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblHighOpenHighClose.setFont(font)
        self.lblHighOpenHighClose.setObjectName("lblHighOpenHighClose")
        self.verticalLayout_9.addWidget(self.lblHighOpenHighClose)
        self.lblHighOpenLowClose = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblHighOpenLowClose.setFont(font)
        self.lblHighOpenLowClose.setObjectName("lblHighOpenLowClose")
        self.verticalLayout_9.addWidget(self.lblHighOpenLowClose)
        self.lblLowOpenLowClose = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblLowOpenLowClose.setFont(font)
        self.lblLowOpenLowClose.setObjectName("lblLowOpenLowClose")
        self.verticalLayout_9.addWidget(self.lblLowOpenLowClose)
        self.lblLowOpenHighClose = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblLowOpenHighClose.setFont(font)
        self.lblLowOpenHighClose.setObjectName("lblLowOpenHighClose")
        self.verticalLayout_9.addWidget(self.lblLowOpenHighClose)
        self.lblReachMaxProbability = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblReachMaxProbability.setFont(font)
        self.lblReachMaxProbability.setObjectName("lblReachMaxProbability")
        self.verticalLayout_9.addWidget(self.lblReachMaxProbability)
        self.lblStayMaxProbability = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStayMaxProbability.setFont(font)
        self.lblStayMaxProbability.setObjectName("lblStayMaxProbability")
        self.verticalLayout_9.addWidget(self.lblStayMaxProbability)
        self.lblReachMinProbability = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblReachMinProbability.setFont(font)
        self.lblReachMinProbability.setObjectName("lblReachMinProbability")
        self.verticalLayout_9.addWidget(self.lblReachMinProbability)
        self.lblStayMinProbability = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStayMinProbability.setFont(font)
        self.lblStayMinProbability.setObjectName("lblStayMinProbability")
        self.verticalLayout_9.addWidget(self.lblStayMinProbability)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 711, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblStockNumber = QtWidgets.QLabel(self.widget)
        self.lblStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockNumber.setFont(font)
        self.lblStockNumber.setObjectName("lblStockNumber")
        self.horizontalLayout.addWidget(self.lblStockNumber)
        self.iptStockNumber = QtWidgets.QLineEdit(self.widget)
        self.iptStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockNumber.setFont(font)
        self.iptStockNumber.setMaxLength(6)
        self.iptStockNumber.setObjectName("iptStockNumber")
        self.horizontalLayout.addWidget(self.iptStockNumber)
        self.lblStockNumber_2 = QtWidgets.QLabel(self.widget)
        self.lblStockNumber_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockNumber_2.setFont(font)
        self.lblStockNumber_2.setObjectName("lblStockNumber_2")
        self.horizontalLayout.addWidget(self.lblStockNumber_2)
        self.spbAnalyzeMonths = QtWidgets.QSpinBox(self.widget)
        self.spbAnalyzeMonths.setMinimum(1)
        self.spbAnalyzeMonths.setMaximum(12)
        self.spbAnalyzeMonths.setProperty("value", 6)
        self.spbAnalyzeMonths.setObjectName("spbAnalyzeMonths")
        self.horizontalLayout.addWidget(self.spbAnalyzeMonths)
        self.btnGetData = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnGetData.setFont(font)
        self.btnGetData.setObjectName("btnGetData")
        self.horizontalLayout.addWidget(self.btnGetData)
        self.btnPlotOpenCloseDistribution = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnPlotOpenCloseDistribution.setFont(font)
        self.btnPlotOpenCloseDistribution.setObjectName("btnPlotOpenCloseDistribution")
        self.horizontalLayout.addWidget(self.btnPlotOpenCloseDistribution)
        self.btnPlotHighLowDistribution = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnPlotHighLowDistribution.setFont(font)
        self.btnPlotHighLowDistribution.setObjectName("btnPlotHighLowDistribution")
        self.horizontalLayout.addWidget(self.btnPlotHighLowDistribution)
        StockAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 22))
        self.menubar.setObjectName("menubar")
        StockAnalyzer.setMenuBar(self.menubar)

        self.retranslateUi(StockAnalyzer)
        self.btnGetData.clicked.connect(StockAnalyzer.get_history_data)
        self.btnPlotHighLowDistribution.clicked.connect(StockAnalyzer.plot_high_low_distribution)
        self.btnPlotOpenCloseDistribution.clicked.connect(StockAnalyzer.plot_open_close_distribution)
        QtCore.QMetaObject.connectSlotsByName(StockAnalyzer)

    def retranslateUi(self, StockAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        StockAnalyzer.setWindowTitle(_translate("StockAnalyzer", "个股股性分析"))
        self.grpStockPerformance.setTitle(_translate("StockAnalyzer", "区间个股表现"))
        self.lblStockIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘价格： "))
        self.lblStockIntervalClose.setText(_translate("StockAnalyzer", "区间收盘价格： "))
        self.lblStockIntervalHigh.setText(_translate("StockAnalyzer", "区间最高价格： "))
        self.lblStockIntervalLow.setText(_translate("StockAnalyzer", "区间最低价格： "))
        self.lblStockIntervalAverage.setText(_translate("StockAnalyzer", "区间平均价格： "))
        self.lblStockIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblStockIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblStockUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.lblWinMarket.setText(_translate("StockAnalyzer", "跑赢大盘日数："))
        self.grpMarketPerformance.setTitle(_translate("StockAnalyzer", "同期大盘表现"))
        self.lblMarketIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘点位： "))
        self.lblMarketIntervalClose.setText(_translate("StockAnalyzer", "区间收盘点位： "))
        self.lblMarketIntervalHigh.setText(_translate("StockAnalyzer", "区间最高点位： "))
        self.lblMarketIntervalLow.setText(_translate("StockAnalyzer", "区间最低点位： "))
        self.lblMarketIntervalAverage.setText(_translate("StockAnalyzer", "区间平均点位： "))
        self.lblMarketIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblMarketIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblMarketUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.groupBox.setTitle(_translate("StockAnalyzer", "股性评估"))
        self.lblAverageTurn.setText(_translate("StockAnalyzer", "平均换手率："))
        self.lblAverageAmplitude.setText(_translate("StockAnalyzer", "每日平均振幅： "))
        self.lblAverageCloseUp.setText(_translate("StockAnalyzer", "阳线平均涨幅： "))
        self.lblAverageHighWhenUp.setText(_translate("StockAnalyzer", "阳线平均最高： "))
        self.lblAverageLowWhenUp.setText(_translate("StockAnalyzer", "阳线平均最低： "))
        self.lblAverageFallbackAmp.setText(_translate("StockAnalyzer", "阳线平均回撤："))
        self.lblAverageCloseDown.setText(_translate("StockAnalyzer", "阴线平均跌幅： "))
        self.lblAverageHighWhenDown.setText(_translate("StockAnalyzer", "阴线平均最高： "))
        self.lblAverageLowWhenDown.setText(_translate("StockAnalyzer", "阴线平均最低： "))
        self.lblAverageBounceAmp.setText(_translate("StockAnalyzer", "阴线平均反弹："))
        self.lblInverseMarketUp.setText(_translate("StockAnalyzer", "逆市上涨日数："))
        self.lblInverseMarketDown.setText(_translate("StockAnalyzer", "逆市下跌日数："))
        self.lblHighOpenHighClose.setText(_translate("StockAnalyzer", "高开高走概率： "))
        self.lblHighOpenLowClose.setText(_translate("StockAnalyzer", "高开低走概率： "))
        self.lblLowOpenLowClose.setText(_translate("StockAnalyzer", "低开低走概率： "))
        self.lblLowOpenHighClose.setText(_translate("StockAnalyzer", "低开高走概率： "))
        self.lblReachMaxProbability.setText(_translate("StockAnalyzer", "涨停触板概率： "))
        self.lblStayMaxProbability.setText(_translate("StockAnalyzer", "涨停收盘概率： "))
        self.lblReachMinProbability.setText(_translate("StockAnalyzer", "跌停触板概率： "))
        self.lblStayMinProbability.setText(_translate("StockAnalyzer", "跌停收盘概率： "))
        self.lblStockNumber.setText(_translate("StockAnalyzer", "股票代码/名称"))
        self.iptStockNumber.setText(_translate("StockAnalyzer", "贵州茅台"))
        self.lblStockNumber_2.setText(_translate("StockAnalyzer", "数据范围"))
        self.spbAnalyzeMonths.setSuffix(_translate("StockAnalyzer", "个月"))
        self.spbAnalyzeMonths.setPrefix(_translate("StockAnalyzer", "最近"))
        self.btnGetData.setText(_translate("StockAnalyzer", "获取历史K线数据"))
        self.btnPlotOpenCloseDistribution.setText(_translate("StockAnalyzer", "开盘收盘分布图"))
        self.btnPlotHighLowDistribution.setText(_translate("StockAnalyzer", "最高最低分布图"))
