# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockFinder.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockFinder(object):
    def setupUi(self, StockFinder):
        StockFinder.setObjectName("StockFinder")
        StockFinder.resize(553, 704)
        self.centralwidget = QtWidgets.QWidget(StockFinder)
        self.centralwidget.setObjectName("centralwidget")
        self.grpSearchRange = QtWidgets.QGroupBox(self.centralwidget)
        self.grpSearchRange.setGeometry(QtCore.QRect(10, 10, 531, 91))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpSearchRange.setFont(font)
        self.grpSearchRange.setObjectName("grpSearchRange")
        self.layoutWidget = QtWidgets.QWidget(self.grpSearchRange)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 22, 511, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbxShanghaiMain = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxShanghaiMain.setFont(font)
        self.cbxShanghaiMain.setChecked(True)
        self.cbxShanghaiMain.setObjectName("cbxShanghaiMain")
        self.horizontalLayout_6.addWidget(self.cbxShanghaiMain)
        self.cbxShenZhenNew = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxShenZhenNew.setFont(font)
        self.cbxShenZhenNew.setChecked(True)
        self.cbxShenZhenNew.setObjectName("cbxShenZhenNew")
        self.horizontalLayout_6.addWidget(self.cbxShenZhenNew)
        self.cbxShenZhenSmall = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxShenZhenSmall.setFont(font)
        self.cbxShenZhenSmall.setChecked(True)
        self.cbxShenZhenSmall.setObjectName("cbxShenZhenSmall")
        self.horizontalLayout_6.addWidget(self.cbxShenZhenSmall)
        self.cbxShenZhenMain = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxShenZhenMain.setFont(font)
        self.cbxShenZhenMain.setChecked(True)
        self.cbxShenZhenMain.setObjectName("cbxShenZhenMain")
        self.horizontalLayout_6.addWidget(self.cbxShenZhenMain)
        self.cbxShanghaiScience = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxShanghaiScience.setFont(font)
        self.cbxShanghaiScience.setChecked(True)
        self.cbxShanghaiScience.setObjectName("cbxShanghaiScience")
        self.horizontalLayout_6.addWidget(self.cbxShanghaiScience)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblSearchDate = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblSearchDate.setFont(font)
        self.lblSearchDate.setObjectName("lblSearchDate")
        self.horizontalLayout_13.addWidget(self.lblSearchDate)
        self.dteSearchDate = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dteSearchDate.setFont(font)
        self.dteSearchDate.setObjectName("dteSearchDate")
        self.horizontalLayout_13.addWidget(self.dteSearchDate)
        self.btnStartSearch = QtWidgets.QPushButton(self.layoutWidget)
        self.btnStartSearch.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartSearch.setFont(font)
        self.btnStartSearch.setObjectName("btnStartSearch")
        self.horizontalLayout_13.addWidget(self.btnStartSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.grpCustomCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpCustomCriterias.setEnabled(True)
        self.grpCustomCriterias.setGeometry(QtCore.QRect(10, 430, 531, 241))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpCustomCriterias.setFont(font)
        self.grpCustomCriterias.setObjectName("grpCustomCriterias")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpCustomCriterias)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 511, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lstCriteriaItems = QtWidgets.QListWidget(self.layoutWidget1)
        self.lstCriteriaItems.setObjectName("lstCriteriaItems")
        self.verticalLayout_5.addWidget(self.lstCriteriaItems)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAddCriteria.setObjectName("btnAddCriteria")
        self.horizontalLayout.addWidget(self.btnAddCriteria)
        self.btnRemoveCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnRemoveCriteria.setObjectName("btnRemoveCriteria")
        self.horizontalLayout.addWidget(self.btnRemoveCriteria)
        self.btnEditCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnEditCriteria.setObjectName("btnEditCriteria")
        self.horizontalLayout.addWidget(self.btnEditCriteria)
        self.btnResetCriteria = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnResetCriteria.setObjectName("btnResetCriteria")
        self.horizontalLayout.addWidget(self.btnResetCriteria)
        self.btnExportCustomConfig = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportCustomConfig.setFont(font)
        self.btnExportCustomConfig.setObjectName("btnExportCustomConfig")
        self.horizontalLayout.addWidget(self.btnExportCustomConfig)
        self.btnImportCustomConfig = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportCustomConfig.setFont(font)
        self.btnImportCustomConfig.setObjectName("btnImportCustomConfig")
        self.horizontalLayout.addWidget(self.btnImportCustomConfig)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.grpBasicCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBasicCriterias.setGeometry(QtCore.QRect(10, 110, 531, 191))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpBasicCriterias.setFont(font)
        self.grpBasicCriterias.setObjectName("grpBasicCriterias")
        self.layoutWidget2 = QtWidgets.QWidget(self.grpBasicCriterias)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 23, 511, 167))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbxPriceEarning = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxPriceEarning.setFont(font)
        self.cbxPriceEarning.setChecked(False)
        self.cbxPriceEarning.setObjectName("cbxPriceEarning")
        self.horizontalLayout_2.addWidget(self.cbxPriceEarning)
        self.spbPriceEarningMin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbPriceEarningMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbPriceEarningMin.setFont(font)
        self.spbPriceEarningMin.setMinimum(-1000)
        self.spbPriceEarningMin.setMaximum(100)
        self.spbPriceEarningMin.setProperty("value", 5)
        self.spbPriceEarningMin.setDisplayIntegerBase(10)
        self.spbPriceEarningMin.setObjectName("spbPriceEarningMin")
        self.horizontalLayout_2.addWidget(self.spbPriceEarningMin)
        self.spbPriceEarningMax = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbPriceEarningMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbPriceEarningMax.setFont(font)
        self.spbPriceEarningMax.setMinimum(-100)
        self.spbPriceEarningMax.setMaximum(1000)
        self.spbPriceEarningMax.setProperty("value", 50)
        self.spbPriceEarningMax.setObjectName("spbPriceEarningMax")
        self.horizontalLayout_2.addWidget(self.spbPriceEarningMax)
        self.cbxPriceBook = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxPriceBook.setFont(font)
        self.cbxPriceBook.setChecked(False)
        self.cbxPriceBook.setObjectName("cbxPriceBook")
        self.horizontalLayout_2.addWidget(self.cbxPriceBook)
        self.spbPriceBookMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.spbPriceBookMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbPriceBookMin.setFont(font)
        self.spbPriceBookMin.setDecimals(1)
        self.spbPriceBookMin.setMinimum(-10.0)
        self.spbPriceBookMin.setMaximum(10.0)
        self.spbPriceBookMin.setSingleStep(0.0)
        self.spbPriceBookMin.setProperty("value", 0.5)
        self.spbPriceBookMin.setObjectName("spbPriceBookMin")
        self.horizontalLayout_2.addWidget(self.spbPriceBookMin)
        self.spbPriceBookMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.spbPriceBookMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbPriceBookMax.setFont(font)
        self.spbPriceBookMax.setDecimals(1)
        self.spbPriceBookMax.setMinimum(-1.0)
        self.spbPriceBookMax.setSingleStep(0.5)
        self.spbPriceBookMax.setProperty("value", 5.0)
        self.spbPriceBookMax.setObjectName("spbPriceBookMax")
        self.horizontalLayout_2.addWidget(self.spbPriceBookMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxNetAssetProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxNetAssetProfit.setFont(font)
        self.cbxNetAssetProfit.setChecked(False)
        self.cbxNetAssetProfit.setObjectName("cbxNetAssetProfit")
        self.horizontalLayout_3.addWidget(self.cbxNetAssetProfit)
        self.spbNetAssetProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbNetAssetProfit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbNetAssetProfit.setFont(font)
        self.spbNetAssetProfit.setMinimum(0)
        self.spbNetAssetProfit.setMaximum(100)
        self.spbNetAssetProfit.setProperty("value", 5)
        self.spbNetAssetProfit.setObjectName("spbNetAssetProfit")
        self.horizontalLayout_3.addWidget(self.spbNetAssetProfit)
        self.cbxGrossProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxGrossProfit.setFont(font)
        self.cbxGrossProfit.setChecked(False)
        self.cbxGrossProfit.setObjectName("cbxGrossProfit")
        self.horizontalLayout_3.addWidget(self.cbxGrossProfit)
        self.spbGrossProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbGrossProfit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbGrossProfit.setFont(font)
        self.spbGrossProfit.setMinimum(-20)
        self.spbGrossProfit.setMaximum(100)
        self.spbGrossProfit.setProperty("value", 30)
        self.spbGrossProfit.setObjectName("spbGrossProfit")
        self.horizontalLayout_3.addWidget(self.spbGrossProfit)
        self.cbxNetProfit = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxNetProfit.setFont(font)
        self.cbxNetProfit.setChecked(False)
        self.cbxNetProfit.setObjectName("cbxNetProfit")
        self.horizontalLayout_3.addWidget(self.cbxNetProfit)
        self.spbNetProfit = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbNetProfit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbNetProfit.setFont(font)
        self.spbNetProfit.setMinimum(-20)
        self.spbNetProfit.setMaximum(100)
        self.spbNetProfit.setProperty("value", 10)
        self.spbNetProfit.setObjectName("spbNetProfit")
        self.horizontalLayout_3.addWidget(self.spbNetProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxIncomeIncrease = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxIncomeIncrease.setFont(font)
        self.cbxIncomeIncrease.setChecked(False)
        self.cbxIncomeIncrease.setObjectName("cbxIncomeIncrease")
        self.horizontalLayout_4.addWidget(self.cbxIncomeIncrease)
        self.spbIncomeIncrease = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbIncomeIncrease.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbIncomeIncrease.setFont(font)
        self.spbIncomeIncrease.setMinimum(-1000)
        self.spbIncomeIncrease.setMaximum(1000)
        self.spbIncomeIncrease.setProperty("value", 10)
        self.spbIncomeIncrease.setObjectName("spbIncomeIncrease")
        self.horizontalLayout_4.addWidget(self.spbIncomeIncrease)
        self.cbxProfitIncrease = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxProfitIncrease.setFont(font)
        self.cbxProfitIncrease.setChecked(False)
        self.cbxProfitIncrease.setObjectName("cbxProfitIncrease")
        self.horizontalLayout_4.addWidget(self.cbxProfitIncrease)
        self.spbProfitIncrease = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbProfitIncrease.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbProfitIncrease.setFont(font)
        self.spbProfitIncrease.setMinimum(-1000)
        self.spbProfitIncrease.setMaximum(1000)
        self.spbProfitIncrease.setProperty("value", 10)
        self.spbProfitIncrease.setObjectName("spbProfitIncrease")
        self.horizontalLayout_4.addWidget(self.spbProfitIncrease)
        self.cbxIncludeStStock = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cbxIncludeStStock.setObjectName("cbxIncludeStStock")
        self.horizontalLayout_4.addWidget(self.cbxIncludeStStock)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cbxTotalHolders = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxTotalHolders.setFont(font)
        self.cbxTotalHolders.setChecked(False)
        self.cbxTotalHolders.setObjectName("cbxTotalHolders")
        self.horizontalLayout_10.addWidget(self.cbxTotalHolders)
        self.spbTotalHoldersMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.spbTotalHoldersMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbTotalHoldersMin.setFont(font)
        self.spbTotalHoldersMin.setDecimals(1)
        self.spbTotalHoldersMin.setMinimum(0.0)
        self.spbTotalHoldersMin.setMaximum(10.0)
        self.spbTotalHoldersMin.setSingleStep(0.5)
        self.spbTotalHoldersMin.setProperty("value", 1.0)
        self.spbTotalHoldersMin.setObjectName("spbTotalHoldersMin")
        self.horizontalLayout_10.addWidget(self.spbTotalHoldersMin)
        self.spbTotalHoldersMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.spbTotalHoldersMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.spbTotalHoldersMax.setFont(font)
        self.spbTotalHoldersMax.setDecimals(1)
        self.spbTotalHoldersMax.setMinimum(1.0)
        self.spbTotalHoldersMax.setProperty("value", 10.0)
        self.spbTotalHoldersMax.setObjectName("spbTotalHoldersMax")
        self.horizontalLayout_10.addWidget(self.spbTotalHoldersMax)
        self.cbxTimeToMarket = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cbxTimeToMarket.setChecked(False)
        self.cbxTimeToMarket.setObjectName("cbxTimeToMarket")
        self.horizontalLayout_10.addWidget(self.cbxTimeToMarket)
        self.spbTimeToMarketMin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTimeToMarketMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTimeToMarketMin.setFont(font)
        self.spbTimeToMarketMin.setMinimum(0)
        self.spbTimeToMarketMin.setMaximum(360)
        self.spbTimeToMarketMin.setProperty("value", 0)
        self.spbTimeToMarketMin.setDisplayIntegerBase(10)
        self.spbTimeToMarketMin.setObjectName("spbTimeToMarketMin")
        self.horizontalLayout_10.addWidget(self.spbTimeToMarketMin)
        self.spbTimeToMarketMax = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTimeToMarketMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTimeToMarketMax.setFont(font)
        self.spbTimeToMarketMax.setMinimum(1)
        self.spbTimeToMarketMax.setMaximum(999)
        self.spbTimeToMarketMax.setProperty("value", 120)
        self.spbTimeToMarketMax.setDisplayIntegerBase(10)
        self.spbTimeToMarketMax.setObjectName("spbTimeToMarketMax")
        self.horizontalLayout_10.addWidget(self.spbTimeToMarketMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbxTotalShare = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxTotalShare.setFont(font)
        self.cbxTotalShare.setChecked(False)
        self.cbxTotalShare.setObjectName("cbxTotalShare")
        self.horizontalLayout_7.addWidget(self.cbxTotalShare)
        self.spbTotalShareMin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTotalShareMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTotalShareMin.setFont(font)
        self.spbTotalShareMin.setMinimum(0)
        self.spbTotalShareMin.setMaximum(10)
        self.spbTotalShareMin.setProperty("value", 5)
        self.spbTotalShareMin.setObjectName("spbTotalShareMin")
        self.horizontalLayout_7.addWidget(self.spbTotalShareMin)
        self.spbTotalShareMax = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTotalShareMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTotalShareMax.setFont(font)
        self.spbTotalShareMax.setMinimum(1)
        self.spbTotalShareMax.setMaximum(10000)
        self.spbTotalShareMax.setProperty("value", 100)
        self.spbTotalShareMax.setObjectName("spbTotalShareMax")
        self.horizontalLayout_7.addWidget(self.spbTotalShareMax)
        self.cbxTotalAssets = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxTotalAssets.setFont(font)
        self.cbxTotalAssets.setChecked(False)
        self.cbxTotalAssets.setObjectName("cbxTotalAssets")
        self.horizontalLayout_7.addWidget(self.cbxTotalAssets)
        self.spbTotalAssetsMin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTotalAssetsMin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTotalAssetsMin.setFont(font)
        self.spbTotalAssetsMin.setMinimum(1)
        self.spbTotalAssetsMin.setMaximum(1000)
        self.spbTotalAssetsMin.setProperty("value", 100)
        self.spbTotalAssetsMin.setObjectName("spbTotalAssetsMin")
        self.horizontalLayout_7.addWidget(self.spbTotalAssetsMin)
        self.spbTotalAssetsMax = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbTotalAssetsMax.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTotalAssetsMax.setFont(font)
        self.spbTotalAssetsMax.setMinimum(10)
        self.spbTotalAssetsMax.setMaximum(99999)
        self.spbTotalAssetsMax.setProperty("value", 1000)
        self.spbTotalAssetsMax.setObjectName("spbTotalAssetsMax")
        self.horizontalLayout_7.addWidget(self.spbTotalAssetsMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnExportBasicConfig = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportBasicConfig.setFont(font)
        self.btnExportBasicConfig.setObjectName("btnExportBasicConfig")
        self.horizontalLayout_5.addWidget(self.btnExportBasicConfig)
        self.btnImportBasicConfig = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportBasicConfig.setFont(font)
        self.btnImportBasicConfig.setObjectName("btnImportBasicConfig")
        self.horizontalLayout_5.addWidget(self.btnImportBasicConfig)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.grpTechnicalCriterias = QtWidgets.QGroupBox(self.centralwidget)
        self.grpTechnicalCriterias.setGeometry(QtCore.QRect(10, 310, 531, 111))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpTechnicalCriterias.setFont(font)
        self.grpTechnicalCriterias.setObjectName("grpTechnicalCriterias")
        self.layoutWidget3 = QtWidgets.QWidget(self.grpTechnicalCriterias)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 20, 511, 83))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.spbTechnicalTimePeriod = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbTechnicalTimePeriod.setFont(font)
        self.spbTechnicalTimePeriod.setMinimum(1)
        self.spbTechnicalTimePeriod.setMaximum(10)
        self.spbTechnicalTimePeriod.setProperty("value", 1)
        self.spbTechnicalTimePeriod.setObjectName("spbTechnicalTimePeriod")
        self.horizontalLayout_18.addWidget(self.spbTechnicalTimePeriod)
        self.lblTechnicalTimePeriod = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblTechnicalTimePeriod.setFont(font)
        self.lblTechnicalTimePeriod.setObjectName("lblTechnicalTimePeriod")
        self.horizontalLayout_18.addWidget(self.lblTechnicalTimePeriod)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cbxMacdEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxMacdEnabled.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbxMacdEnabled.setChecked(False)
        self.cbxMacdEnabled.setObjectName("cbxMacdEnabled")
        self.horizontalLayout_11.addWidget(self.cbxMacdEnabled)
        self.cbbMacdBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMacdBehaviour.setEnabled(False)
        self.cbbMacdBehaviour.setObjectName("cbbMacdBehaviour")
        self.horizontalLayout_11.addWidget(self.cbbMacdBehaviour)
        self.cbxBollEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxBollEnabled.setEnabled(True)
        self.cbxBollEnabled.setChecked(False)
        self.cbxBollEnabled.setObjectName("cbxBollEnabled")
        self.horizontalLayout_11.addWidget(self.cbxBollEnabled)
        self.cbbBollBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbBollBehaviour.setEnabled(False)
        self.cbbBollBehaviour.setObjectName("cbbBollBehaviour")
        self.horizontalLayout_11.addWidget(self.cbbBollBehaviour)
        self.cbbBollTrack = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbBollTrack.setEnabled(False)
        self.cbbBollTrack.setObjectName("cbbBollTrack")
        self.horizontalLayout_11.addWidget(self.cbbBollTrack)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbxMaEnabled = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbxMaEnabled.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cbxMaEnabled.setChecked(False)
        self.cbxMaEnabled.setObjectName("cbxMaEnabled")
        self.horizontalLayout_8.addWidget(self.cbxMaEnabled)
        self.spbMaShort = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spbMaShort.setEnabled(False)
        self.spbMaShort.setMinimum(5)
        self.spbMaShort.setMaximum(20)
        self.spbMaShort.setObjectName("spbMaShort")
        self.horizontalLayout_8.addWidget(self.spbMaShort)
        self.cbbMaBehaviour = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMaBehaviour.setEnabled(False)
        self.cbbMaBehaviour.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cbbMaBehaviour.setObjectName("cbbMaBehaviour")
        self.horizontalLayout_8.addWidget(self.cbbMaBehaviour)
        self.spbMaLong = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spbMaLong.setEnabled(False)
        self.spbMaLong.setMinimum(10)
        self.spbMaLong.setMaximum(60)
        self.spbMaLong.setObjectName("spbMaLong")
        self.horizontalLayout_8.addWidget(self.spbMaLong)
        self.btnExportTechnicalConfig = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnExportTechnicalConfig.setFont(font)
        self.btnExportTechnicalConfig.setObjectName("btnExportTechnicalConfig")
        self.horizontalLayout_8.addWidget(self.btnExportTechnicalConfig)
        self.btnImportTechnicalConfig = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnImportTechnicalConfig.setFont(font)
        self.btnImportTechnicalConfig.setObjectName("btnImportTechnicalConfig")
        self.horizontalLayout_8.addWidget(self.btnImportTechnicalConfig)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        StockFinder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockFinder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 23))
        self.menubar.setObjectName("menubar")
        self.mnuOtherCriterias = QtWidgets.QMenu(self.menubar)
        self.mnuOtherCriterias.setObjectName("mnuOtherCriterias")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        StockFinder.setMenuBar(self.menubar)
        self.actHoldersStatus = QtWidgets.QAction(StockFinder)
        self.actHoldersStatus.setObjectName("actHoldersStatus")
        self.actBatchSelector = QtWidgets.QAction(StockFinder)
        self.actBatchSelector.setObjectName("actBatchSelector")
        self.actFiveDaysFinder = QtWidgets.QAction(StockFinder)
        self.actFiveDaysFinder.setObjectName("actFiveDaysFinder")
        self.mnuOtherCriterias.addAction(self.actHoldersStatus)
        self.mnuOtherCriterias.addAction(self.actFiveDaysFinder)
        self.menu.addAction(self.actBatchSelector)
        self.menubar.addAction(self.mnuOtherCriterias.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(StockFinder)
        self.btnStartSearch.clicked.connect(StockFinder.search_all_stocks)
        self.cbxPriceEarning.toggled['bool'].connect(self.spbPriceEarningMin.setEnabled)
        self.cbxPriceEarning.toggled['bool'].connect(self.spbPriceEarningMax.setEnabled)
        self.cbxTotalShare.toggled['bool'].connect(self.spbTotalShareMin.setEnabled)
        self.cbxTotalShare.toggled['bool'].connect(self.spbTotalShareMax.setEnabled)
        self.cbxTotalAssets.toggled['bool'].connect(self.spbTotalAssetsMin.setEnabled)
        self.cbxTotalAssets.toggled['bool'].connect(self.spbTotalAssetsMax.setEnabled)
        self.btnAddCriteria.clicked.connect(StockFinder.add_criteria_item)
        self.btnEditCriteria.clicked.connect(StockFinder.modify_criteria_item)
        self.btnRemoveCriteria.clicked.connect(StockFinder.remove_criteria_item)
        self.btnResetCriteria.clicked.connect(StockFinder.reset_criteria_items)
        self.btnExportCustomConfig.clicked.connect(StockFinder.export_custom_config)
        self.btnImportCustomConfig.clicked.connect(StockFinder.import_custom_config)
        self.cbxGrossProfit.toggled['bool'].connect(self.spbGrossProfit.setEnabled)
        self.cbxNetProfit.toggled['bool'].connect(self.spbNetProfit.setEnabled)
        self.cbxIncomeIncrease.toggled['bool'].connect(self.spbIncomeIncrease.setEnabled)
        self.cbxProfitIncrease.toggled['bool'].connect(self.spbProfitIncrease.setEnabled)
        self.cbxNetAssetProfit.toggled['bool'].connect(self.spbNetAssetProfit.setEnabled)
        self.cbxTotalHolders.toggled['bool'].connect(self.spbTotalHoldersMin.setEnabled)
        self.cbxTotalHolders.toggled['bool'].connect(self.spbTotalHoldersMax.setEnabled)
        self.lstCriteriaItems.itemDoubleClicked['QListWidgetItem*'].connect(StockFinder.edit_selected_item)
        self.btnExportBasicConfig.clicked.connect(StockFinder.export_basic_config)
        self.btnImportBasicConfig.clicked.connect(StockFinder.import_basic_config)
        self.actHoldersStatus.triggered.connect(StockFinder.search_by_holders_structure)
        self.cbxMacdEnabled.toggled['bool'].connect(self.cbbMacdBehaviour.setEnabled)
        self.cbxBollEnabled.toggled['bool'].connect(self.cbbBollBehaviour.setEnabled)
        self.cbxBollEnabled.toggled['bool'].connect(self.cbbBollTrack.setEnabled)
        self.btnExportTechnicalConfig.clicked.connect(StockFinder.export_technical_config)
        self.btnImportTechnicalConfig.clicked.connect(StockFinder.import_technical_config)
        self.actBatchSelector.triggered.connect(StockFinder.run_batch_searcher)
        self.cbxMaEnabled.toggled['bool'].connect(self.spbMaShort.setEnabled)
        self.cbxMaEnabled.toggled['bool'].connect(self.cbbMaBehaviour.setEnabled)
        self.cbxMaEnabled.toggled['bool'].connect(self.spbMaLong.setEnabled)
        self.cbxTimeToMarket.toggled['bool'].connect(self.spbTimeToMarketMin.setEnabled)
        self.cbxTimeToMarket.toggled['bool'].connect(self.spbTimeToMarketMax.setEnabled)
        self.actFiveDaysFinder.triggered.connect(StockFinder.five_day_search)
        QtCore.QMetaObject.connectSlotsByName(StockFinder)

    def retranslateUi(self, StockFinder):
        _translate = QtCore.QCoreApplication.translate
        StockFinder.setWindowTitle(_translate("StockFinder", "智能选股器"))
        self.grpSearchRange.setTitle(_translate("StockFinder", "搜索范围"))
        self.cbxShanghaiMain.setText(_translate("StockFinder", "上海主板"))
        self.cbxShenZhenNew.setText(_translate("StockFinder", "创业板"))
        self.cbxShenZhenSmall.setText(_translate("StockFinder", "中小板"))
        self.cbxShenZhenMain.setText(_translate("StockFinder", "深圳主板"))
        self.cbxShanghaiScience.setText(_translate("StockFinder", "科创板"))
        self.lblSearchDate.setText(_translate("StockFinder", "选股日期"))
        self.dteSearchDate.setDisplayFormat(_translate("StockFinder", "yyyy-MM-dd"))
        self.btnStartSearch.setText(_translate("StockFinder", "开始搜索选股"))
        self.grpCustomCriterias.setTitle(_translate("StockFinder", "自定义指标"))
        self.btnAddCriteria.setText(_translate("StockFinder", "添加"))
        self.btnRemoveCriteria.setText(_translate("StockFinder", "删除"))
        self.btnEditCriteria.setText(_translate("StockFinder", "编辑"))
        self.btnResetCriteria.setText(_translate("StockFinder", "清空"))
        self.btnExportCustomConfig.setText(_translate("StockFinder", "导出"))
        self.btnImportCustomConfig.setText(_translate("StockFinder", "导入"))
        self.grpBasicCriterias.setTitle(_translate("StockFinder", "基本面指标"))
        self.cbxPriceEarning.setText(_translate("StockFinder", "市盈率"))
        self.spbPriceEarningMin.setSuffix(_translate("StockFinder", "倍"))
        self.spbPriceEarningMin.setPrefix(_translate("StockFinder", ">"))
        self.spbPriceEarningMax.setSuffix(_translate("StockFinder", "倍"))
        self.spbPriceEarningMax.setPrefix(_translate("StockFinder", "<"))
        self.cbxPriceBook.setText(_translate("StockFinder", "市净率"))
        self.spbPriceBookMin.setPrefix(_translate("StockFinder", ">"))
        self.spbPriceBookMin.setSuffix(_translate("StockFinder", "倍"))
        self.spbPriceBookMax.setPrefix(_translate("StockFinder", "<"))
        self.spbPriceBookMax.setSuffix(_translate("StockFinder", "倍"))
        self.cbxNetAssetProfit.setText(_translate("StockFinder", "ROE"))
        self.spbNetAssetProfit.setSuffix(_translate("StockFinder", "%"))
        self.spbNetAssetProfit.setPrefix(_translate("StockFinder", ">"))
        self.cbxGrossProfit.setText(_translate("StockFinder", "毛利率"))
        self.spbGrossProfit.setSuffix(_translate("StockFinder", "%"))
        self.spbGrossProfit.setPrefix(_translate("StockFinder", ">"))
        self.cbxNetProfit.setText(_translate("StockFinder", "净利率"))
        self.spbNetProfit.setSuffix(_translate("StockFinder", "%"))
        self.spbNetProfit.setPrefix(_translate("StockFinder", ">"))
        self.cbxIncomeIncrease.setText(_translate("StockFinder", "收入增长"))
        self.spbIncomeIncrease.setSuffix(_translate("StockFinder", "%"))
        self.spbIncomeIncrease.setPrefix(_translate("StockFinder", ">"))
        self.cbxProfitIncrease.setText(_translate("StockFinder", "利润增长"))
        self.spbProfitIncrease.setSuffix(_translate("StockFinder", "%"))
        self.spbProfitIncrease.setPrefix(_translate("StockFinder", ">"))
        self.cbxIncludeStStock.setText(_translate("StockFinder", "包含ST股"))
        self.cbxTotalHolders.setText(_translate("StockFinder", "股东人数"))
        self.spbTotalHoldersMin.setPrefix(_translate("StockFinder", ">"))
        self.spbTotalHoldersMin.setSuffix(_translate("StockFinder", "万人"))
        self.spbTotalHoldersMax.setPrefix(_translate("StockFinder", "<"))
        self.spbTotalHoldersMax.setSuffix(_translate("StockFinder", "万人"))
        self.cbxTimeToMarket.setText(_translate("StockFinder", "上市时间"))
        self.spbTimeToMarketMin.setSuffix(_translate("StockFinder", "月"))
        self.spbTimeToMarketMin.setPrefix(_translate("StockFinder", ">"))
        self.spbTimeToMarketMax.setSuffix(_translate("StockFinder", "月"))
        self.spbTimeToMarketMax.setPrefix(_translate("StockFinder", "<"))
        self.cbxTotalShare.setText(_translate("StockFinder", "总股本"))
        self.spbTotalShareMin.setSuffix(_translate("StockFinder", "亿"))
        self.spbTotalShareMin.setPrefix(_translate("StockFinder", ">"))
        self.spbTotalShareMax.setSuffix(_translate("StockFinder", "亿"))
        self.spbTotalShareMax.setPrefix(_translate("StockFinder", "<"))
        self.cbxTotalAssets.setText(_translate("StockFinder", "总市值"))
        self.spbTotalAssetsMin.setSuffix(_translate("StockFinder", "亿"))
        self.spbTotalAssetsMin.setPrefix(_translate("StockFinder", ">"))
        self.spbTotalAssetsMax.setSuffix(_translate("StockFinder", "亿"))
        self.spbTotalAssetsMax.setPrefix(_translate("StockFinder", "<"))
        self.btnExportBasicConfig.setText(_translate("StockFinder", "保存"))
        self.btnImportBasicConfig.setText(_translate("StockFinder", "载入"))
        self.grpTechnicalCriterias.setTitle(_translate("StockFinder", "技术面指标"))
        self.spbTechnicalTimePeriod.setSuffix(_translate("StockFinder", "日内"))
        self.spbTechnicalTimePeriod.setPrefix(_translate("StockFinder", "最近"))
        self.lblTechnicalTimePeriod.setText(_translate("StockFinder", "指标出现以下信号"))
        self.cbxMacdEnabled.setText(_translate("StockFinder", "MACD"))
        self.cbxBollEnabled.setText(_translate("StockFinder", "BOLL"))
        self.cbxMaEnabled.setText(_translate("StockFinder", "MA"))
        self.spbMaShort.setSuffix(_translate("StockFinder", "日"))
        self.spbMaLong.setSuffix(_translate("StockFinder", "日"))
        self.btnExportTechnicalConfig.setText(_translate("StockFinder", "保存"))
        self.btnImportTechnicalConfig.setText(_translate("StockFinder", "载入"))
        self.mnuOtherCriterias.setTitle(_translate("StockFinder", "其他指标"))
        self.menu.setTitle(_translate("StockFinder", "自动选股"))
        self.actHoldersStatus.setText(_translate("StockFinder", "十大流通股东"))
        self.actBatchSelector.setText(_translate("StockFinder", "定时批量选股"))
        self.actFiveDaysFinder.setText(_translate("StockFinder", "五日图形选股"))
