# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockAnalyzer(object):
    def setupUi(self, StockAnalyzer):
        StockAnalyzer.setObjectName("StockAnalyzer")
        StockAnalyzer.resize(619, 628)
        self.centralwidget = QtWidgets.QWidget(StockAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.grpStockPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpStockPerformance.setGeometry(QtCore.QRect(30, 60, 181, 471))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.grpStockPerformance.setFont(font)
        self.grpStockPerformance.setObjectName("grpStockPerformance")
        self.layoutWidget = QtWidgets.QWidget(self.grpStockPerformance)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 19, 151, 433))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblStockIntervalOpen = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalOpen.setFont(font)
        self.lblStockIntervalOpen.setObjectName("lblStockIntervalOpen")
        self.verticalLayout.addWidget(self.lblStockIntervalOpen)
        self.lblStockIntervalClose = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalClose.setFont(font)
        self.lblStockIntervalClose.setObjectName("lblStockIntervalClose")
        self.verticalLayout.addWidget(self.lblStockIntervalClose)
        self.lblStockIntervalHigh = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalHigh.setFont(font)
        self.lblStockIntervalHigh.setObjectName("lblStockIntervalHigh")
        self.verticalLayout.addWidget(self.lblStockIntervalHigh)
        self.lblStockIntervalLow = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalLow.setFont(font)
        self.lblStockIntervalLow.setObjectName("lblStockIntervalLow")
        self.verticalLayout.addWidget(self.lblStockIntervalLow)
        self.lblStockIntervalAverage = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalAverage.setFont(font)
        self.lblStockIntervalAverage.setObjectName("lblStockIntervalAverage")
        self.verticalLayout.addWidget(self.lblStockIntervalAverage)
        self.lblStockIntervalTotal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalTotal.setFont(font)
        self.lblStockIntervalTotal.setObjectName("lblStockIntervalTotal")
        self.verticalLayout.addWidget(self.lblStockIntervalTotal)
        self.lblStockIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockIntervalAveragePoint.setFont(font)
        self.lblStockIntervalAveragePoint.setObjectName("lblStockIntervalAveragePoint")
        self.verticalLayout.addWidget(self.lblStockIntervalAveragePoint)
        self.lblStockUpProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockUpProbability.setFont(font)
        self.lblStockUpProbability.setObjectName("lblStockUpProbability")
        self.verticalLayout.addWidget(self.lblStockUpProbability)
        self.lblWinMarket = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblWinMarket.setFont(font)
        self.lblWinMarket.setObjectName("lblWinMarket")
        self.verticalLayout.addWidget(self.lblWinMarket)
        self.lblInverseMarketUp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblInverseMarketUp.setFont(font)
        self.lblInverseMarketUp.setObjectName("lblInverseMarketUp")
        self.verticalLayout.addWidget(self.lblInverseMarketUp)
        self.lblInverseMarketDown = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblInverseMarketDown.setFont(font)
        self.lblInverseMarketDown.setObjectName("lblInverseMarketDown")
        self.verticalLayout.addWidget(self.lblInverseMarketDown)
        self.lblAverageHigh = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageHigh.setFont(font)
        self.lblAverageHigh.setObjectName("lblAverageHigh")
        self.verticalLayout.addWidget(self.lblAverageHigh)
        self.lblAverageLow = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageLow.setFont(font)
        self.lblAverageLow.setObjectName("lblAverageLow")
        self.verticalLayout.addWidget(self.lblAverageLow)
        self.lblAverageCloseUp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageCloseUp.setFont(font)
        self.lblAverageCloseUp.setObjectName("lblAverageCloseUp")
        self.verticalLayout.addWidget(self.lblAverageCloseUp)
        self.lblAverageCloseDown = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageCloseDown.setFont(font)
        self.lblAverageCloseDown.setObjectName("lblAverageCloseDown")
        self.verticalLayout.addWidget(self.lblAverageCloseDown)
        self.lblReachMaxProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblReachMaxProbability.setFont(font)
        self.lblReachMaxProbability.setObjectName("lblReachMaxProbability")
        self.verticalLayout.addWidget(self.lblReachMaxProbability)
        self.lblStayMaxProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStayMaxProbability.setFont(font)
        self.lblStayMaxProbability.setObjectName("lblStayMaxProbability")
        self.verticalLayout.addWidget(self.lblStayMaxProbability)
        self.lblReachMinProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblReachMinProbability.setFont(font)
        self.lblReachMinProbability.setObjectName("lblReachMinProbability")
        self.verticalLayout.addWidget(self.lblReachMinProbability)
        self.lblStayMinProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStayMinProbability.setFont(font)
        self.lblStayMinProbability.setObjectName("lblStayMinProbability")
        self.verticalLayout.addWidget(self.lblStayMinProbability)
        self.grpMarketPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpMarketPerformance.setGeometry(QtCore.QRect(220, 60, 171, 211))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.grpMarketPerformance.setFont(font)
        self.grpMarketPerformance.setObjectName("grpMarketPerformance")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpMarketPerformance)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 151, 180))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblMarketIntervalOpen = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalOpen.setFont(font)
        self.lblMarketIntervalOpen.setObjectName("lblMarketIntervalOpen")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalOpen)
        self.lblMarketIntervalClose = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalClose.setFont(font)
        self.lblMarketIntervalClose.setObjectName("lblMarketIntervalClose")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalClose)
        self.lblMarketIntervalHigh = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalHigh.setFont(font)
        self.lblMarketIntervalHigh.setObjectName("lblMarketIntervalHigh")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalHigh)
        self.lblMarketIntervalLow = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalLow.setFont(font)
        self.lblMarketIntervalLow.setObjectName("lblMarketIntervalLow")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalLow)
        self.lblMarketIntervalAverage = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalAverage.setFont(font)
        self.lblMarketIntervalAverage.setObjectName("lblMarketIntervalAverage")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAverage)
        self.lblMarketIntervalTotal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalTotal.setFont(font)
        self.lblMarketIntervalTotal.setObjectName("lblMarketIntervalTotal")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalTotal)
        self.lblMarketIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketIntervalAveragePoint.setFont(font)
        self.lblMarketIntervalAveragePoint.setObjectName("lblMarketIntervalAveragePoint")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAveragePoint)
        self.lblMarketUpProbability = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMarketUpProbability.setFont(font)
        self.lblMarketUpProbability.setObjectName("lblMarketUpProbability")
        self.verticalLayout_2.addWidget(self.lblMarketUpProbability)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 20, 551, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblStockNumber = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStockNumber.setFont(font)
        self.lblStockNumber.setObjectName("lblStockNumber")
        self.horizontalLayout_2.addWidget(self.lblStockNumber)
        self.iptStockNumber = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.iptStockNumber.setFont(font)
        self.iptStockNumber.setMaxLength(6)
        self.iptStockNumber.setObjectName("iptStockNumber")
        self.horizontalLayout_2.addWidget(self.iptStockNumber)
        self.lblStartDate = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.horizontalLayout_2.addWidget(self.lblStartDate)
        self.dteStartDate = QtWidgets.QDateEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.dteStartDate.setFont(font)
        self.dteStartDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteStartDate.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dteStartDate.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteStartDate.setObjectName("dteStartDate")
        self.horizontalLayout_2.addWidget(self.dteStartDate)
        self.lblEndDate = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblEndDate.setFont(font)
        self.lblEndDate.setObjectName("lblEndDate")
        self.horizontalLayout_2.addWidget(self.lblEndDate)
        self.dteEndDate = QtWidgets.QDateEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.dteEndDate.setFont(font)
        self.dteEndDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteEndDate.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dteEndDate.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteEndDate.setObjectName("dteEndDate")
        self.horizontalLayout_2.addWidget(self.dteEndDate)
        self.btnGetData = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnGetData.setFont(font)
        self.btnGetData.setObjectName("btnGetData")
        self.horizontalLayout_2.addWidget(self.btnGetData)
        self.grpTradeRule = QtWidgets.QGroupBox(self.centralwidget)
        self.grpTradeRule.setGeometry(QtCore.QRect(400, 60, 201, 471))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.grpTradeRule.setFont(font)
        self.grpTradeRule.setObjectName("grpTradeRule")
        self.layoutWidget3 = QtWidgets.QWidget(self.grpTradeRule)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 161, 275))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget3.setFont(font)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblBuyPoint = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblBuyPoint.setFont(font)
        self.lblBuyPoint.setObjectName("lblBuyPoint")
        self.horizontalLayout_3.addWidget(self.lblBuyPoint)
        self.spbBuyPoint = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbBuyPoint.setFont(font)
        self.spbBuyPoint.setDecimals(1)
        self.spbBuyPoint.setMinimum(-10.0)
        self.spbBuyPoint.setMaximum(10.0)
        self.spbBuyPoint.setProperty("value", -2.0)
        self.spbBuyPoint.setObjectName("spbBuyPoint")
        self.horizontalLayout_3.addWidget(self.spbBuyPoint)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblSellPoint = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblSellPoint.setFont(font)
        self.lblSellPoint.setObjectName("lblSellPoint")
        self.horizontalLayout_4.addWidget(self.lblSellPoint)
        self.spbSellPoint = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbSellPoint.setFont(font)
        self.spbSellPoint.setDecimals(1)
        self.spbSellPoint.setMinimum(-10.0)
        self.spbSellPoint.setMaximum(10.0)
        self.spbSellPoint.setProperty("value", 2.0)
        self.spbSellPoint.setObjectName("spbSellPoint")
        self.horizontalLayout_4.addWidget(self.spbSellPoint)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxAllowSameDayTrade = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.cbxAllowSameDayTrade.setFont(font)
        self.cbxAllowSameDayTrade.setChecked(True)
        self.cbxAllowSameDayTrade.setObjectName("cbxAllowSameDayTrade")
        self.horizontalLayout_9.addWidget(self.cbxAllowSameDayTrade)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblSameDayTradeProfit = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblSameDayTradeProfit.setFont(font)
        self.lblSameDayTradeProfit.setObjectName("lblSameDayTradeProfit")
        self.horizontalLayout_14.addWidget(self.lblSameDayTradeProfit)
        self.spbSameDayProfit = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbSameDayProfit.setFont(font)
        self.spbSameDayProfit.setDecimals(1)
        self.spbSameDayProfit.setMinimum(-10.0)
        self.spbSameDayProfit.setMaximum(10.0)
        self.spbSameDayProfit.setProperty("value", 2.0)
        self.spbSameDayProfit.setObjectName("spbSameDayProfit")
        self.horizontalLayout_14.addWidget(self.spbSameDayProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblBaseShare = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblBaseShare.setFont(font)
        self.lblBaseShare.setObjectName("lblBaseShare")
        self.horizontalLayout_5.addWidget(self.lblBaseShare)
        self.spbBaseShare = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbBaseShare.setFont(font)
        self.spbBaseShare.setMinimum(100)
        self.spbBaseShare.setMaximum(100000)
        self.spbBaseShare.setSingleStep(100)
        self.spbBaseShare.setProperty("value", 2000)
        self.spbBaseShare.setObjectName("spbBaseShare")
        self.horizontalLayout_5.addWidget(self.spbBaseShare)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblSharePerTrade = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblSharePerTrade.setFont(font)
        self.lblSharePerTrade.setObjectName("lblSharePerTrade")
        self.horizontalLayout_6.addWidget(self.lblSharePerTrade)
        self.spbSharePerTrade = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbSharePerTrade.setFont(font)
        self.spbSharePerTrade.setMinimum(100)
        self.spbSharePerTrade.setMaximum(100000)
        self.spbSharePerTrade.setSingleStep(100)
        self.spbSharePerTrade.setProperty("value", 1000)
        self.spbSharePerTrade.setObjectName("spbSharePerTrade")
        self.horizontalLayout_6.addWidget(self.spbSharePerTrade)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblMaxShare = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMaxShare.setFont(font)
        self.lblMaxShare.setObjectName("lblMaxShare")
        self.horizontalLayout_7.addWidget(self.lblMaxShare)
        self.spbMaxShare = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbMaxShare.setFont(font)
        self.spbMaxShare.setMinimum(100)
        self.spbMaxShare.setMaximum(100000)
        self.spbMaxShare.setSingleStep(100)
        self.spbMaxShare.setProperty("value", 5000)
        self.spbMaxShare.setObjectName("spbMaxShare")
        self.horizontalLayout_7.addWidget(self.spbMaxShare)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblMinShare = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblMinShare.setFont(font)
        self.lblMinShare.setObjectName("lblMinShare")
        self.horizontalLayout_8.addWidget(self.lblMinShare)
        self.spbMinShare = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.spbMinShare.setFont(font)
        self.spbMinShare.setMinimum(0)
        self.spbMinShare.setMaximum(100000)
        self.spbMinShare.setSingleStep(100)
        self.spbMinShare.setProperty("value", 0)
        self.spbMinShare.setObjectName("spbMinShare")
        self.horizontalLayout_8.addWidget(self.spbMinShare)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnAutoFindStrategy = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.btnAutoFindStrategy.setFont(font)
        self.btnAutoFindStrategy.setObjectName("btnAutoFindStrategy")
        self.horizontalLayout_10.addWidget(self.btnAutoFindStrategy)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.lblBuySellSignal = QtWidgets.QLabel(self.grpTradeRule)
        self.lblBuySellSignal.setGeometry(QtCore.QRect(10, 300, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblBuySellSignal.setFont(font)
        self.lblBuySellSignal.setObjectName("lblBuySellSignal")
        self.widget = QtWidgets.QWidget(self.grpTradeRule)
        self.widget.setGeometry(QtCore.QRect(11, 322, 170, 135))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbxMacdEnabled = QtWidgets.QCheckBox(self.widget)
        self.cbxMacdEnabled.setChecked(True)
        self.cbxMacdEnabled.setObjectName("cbxMacdEnabled")
        self.verticalLayout_4.addWidget(self.cbxMacdEnabled)
        self.cbxKdjEnabled = QtWidgets.QCheckBox(self.widget)
        self.cbxKdjEnabled.setChecked(True)
        self.cbxKdjEnabled.setObjectName("cbxKdjEnabled")
        self.verticalLayout_4.addWidget(self.cbxKdjEnabled)
        self.cbxBollEnabled = QtWidgets.QCheckBox(self.widget)
        self.cbxBollEnabled.setChecked(True)
        self.cbxBollEnabled.setObjectName("cbxBollEnabled")
        self.verticalLayout_4.addWidget(self.cbxBollEnabled)
        self.cbxBollEnabled_2 = QtWidgets.QCheckBox(self.widget)
        self.cbxBollEnabled_2.setChecked(True)
        self.cbxBollEnabled_2.setObjectName("cbxBollEnabled_2")
        self.verticalLayout_4.addWidget(self.cbxBollEnabled_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSignalTradeUnit = QtWidgets.QLabel(self.widget)
        self.lblSignalTradeUnit.setObjectName("lblSignalTradeUnit")
        self.horizontalLayout.addWidget(self.lblSignalTradeUnit)
        self.spbSignalTradeUnit = QtWidgets.QSpinBox(self.widget)
        self.spbSignalTradeUnit.setMinimum(1)
        self.spbSignalTradeUnit.setObjectName("spbSignalTradeUnit")
        self.horizontalLayout.addWidget(self.spbSignalTradeUnit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(220, 270, 171, 261))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 151, 226))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.layoutWidget4.setFont(font)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblAverageTurn = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageTurn.setFont(font)
        self.lblAverageTurn.setObjectName("lblAverageTurn")
        self.verticalLayout_6.addWidget(self.lblAverageTurn)
        self.lblAverageAmplitude = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageAmplitude.setFont(font)
        self.lblAverageAmplitude.setObjectName("lblAverageAmplitude")
        self.verticalLayout_6.addWidget(self.lblAverageAmplitude)
        self.lblHighOpenHighClose = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblHighOpenHighClose.setFont(font)
        self.lblHighOpenHighClose.setObjectName("lblHighOpenHighClose")
        self.verticalLayout_6.addWidget(self.lblHighOpenHighClose)
        self.lblHighOpenLowClose = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblHighOpenLowClose.setFont(font)
        self.lblHighOpenLowClose.setObjectName("lblHighOpenLowClose")
        self.verticalLayout_6.addWidget(self.lblHighOpenLowClose)
        self.lblLowOpenLowClose = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblLowOpenLowClose.setFont(font)
        self.lblLowOpenLowClose.setObjectName("lblLowOpenLowClose")
        self.verticalLayout_6.addWidget(self.lblLowOpenLowClose)
        self.lblLowOpenHighClose = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblLowOpenHighClose.setFont(font)
        self.lblLowOpenHighClose.setObjectName("lblLowOpenHighClose")
        self.verticalLayout_6.addWidget(self.lblLowOpenHighClose)
        self.lblAverageHighWhenUp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageHighWhenUp.setFont(font)
        self.lblAverageHighWhenUp.setObjectName("lblAverageHighWhenUp")
        self.verticalLayout_6.addWidget(self.lblAverageHighWhenUp)
        self.lblAverageFallbackAmp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageFallbackAmp.setFont(font)
        self.lblAverageFallbackAmp.setObjectName("lblAverageFallbackAmp")
        self.verticalLayout_6.addWidget(self.lblAverageFallbackAmp)
        self.lblAverageLowWhenDown = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageLowWhenDown.setFont(font)
        self.lblAverageLowWhenDown.setObjectName("lblAverageLowWhenDown")
        self.verticalLayout_6.addWidget(self.lblAverageLowWhenDown)
        self.lblAverageBounceAmp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.lblAverageBounceAmp.setFont(font)
        self.lblAverageBounceAmp.setObjectName("lblAverageBounceAmp")
        self.verticalLayout_6.addWidget(self.lblAverageBounceAmp)
        self.btnStartTrade = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartTrade.setGeometry(QtCore.QRect(220, 540, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.btnStartTrade.setFont(font)
        self.btnStartTrade.setObjectName("btnStartTrade")
        StockAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 23))
        self.menubar.setObjectName("menubar")
        StockAnalyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StockAnalyzer)
        self.statusbar.setObjectName("statusbar")
        StockAnalyzer.setStatusBar(self.statusbar)

        self.retranslateUi(StockAnalyzer)
        self.btnGetData.clicked.connect(StockAnalyzer.get_history_data)
        self.btnStartTrade.clicked.connect(StockAnalyzer.start_trade)
        self.btnAutoFindStrategy.clicked.connect(StockAnalyzer.auto_get_strategy)
        self.cbxAllowSameDayTrade.clicked['bool'].connect(self.spbSameDayProfit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StockAnalyzer)

    def retranslateUi(self, StockAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        StockAnalyzer.setWindowTitle(_translate("StockAnalyzer", "个股股性分析"))
        self.grpStockPerformance.setTitle(_translate("StockAnalyzer", "个股表现"))
        self.lblStockIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘价格： "))
        self.lblStockIntervalClose.setText(_translate("StockAnalyzer", "区间收盘价格： "))
        self.lblStockIntervalHigh.setText(_translate("StockAnalyzer", "区间最高价格： "))
        self.lblStockIntervalLow.setText(_translate("StockAnalyzer", "区间最低价格： "))
        self.lblStockIntervalAverage.setText(_translate("StockAnalyzer", "区间平均价格： "))
        self.lblStockIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblStockIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblStockUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.lblWinMarket.setText(_translate("StockAnalyzer", "跑赢大盘日数："))
        self.lblInverseMarketUp.setText(_translate("StockAnalyzer", "逆市上涨日数："))
        self.lblInverseMarketDown.setText(_translate("StockAnalyzer", "逆市下跌日数："))
        self.lblAverageHigh.setText(_translate("StockAnalyzer", "平均日内最高： "))
        self.lblAverageLow.setText(_translate("StockAnalyzer", "平均日内最低： "))
        self.lblAverageCloseUp.setText(_translate("StockAnalyzer", "阳线平均涨幅： "))
        self.lblAverageCloseDown.setText(_translate("StockAnalyzer", "阴线平均跌幅： "))
        self.lblReachMaxProbability.setText(_translate("StockAnalyzer", "涨停触板概率： "))
        self.lblStayMaxProbability.setText(_translate("StockAnalyzer", "涨停收盘概率： "))
        self.lblReachMinProbability.setText(_translate("StockAnalyzer", "跌停触板概率： "))
        self.lblStayMinProbability.setText(_translate("StockAnalyzer", "跌停收盘概率： "))
        self.grpMarketPerformance.setTitle(_translate("StockAnalyzer", "大盘表现"))
        self.lblMarketIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘点位： "))
        self.lblMarketIntervalClose.setText(_translate("StockAnalyzer", "区间收盘点位： "))
        self.lblMarketIntervalHigh.setText(_translate("StockAnalyzer", "区间最高点位： "))
        self.lblMarketIntervalLow.setText(_translate("StockAnalyzer", "区间最低点位： "))
        self.lblMarketIntervalAverage.setText(_translate("StockAnalyzer", "区间平均点位： "))
        self.lblMarketIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblMarketIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblMarketUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.lblStockNumber.setText(_translate("StockAnalyzer", "股票代码"))
        self.iptStockNumber.setText(_translate("StockAnalyzer", "601933"))
        self.lblStartDate.setText(_translate("StockAnalyzer", "区间开始日期"))
        self.dteStartDate.setDisplayFormat(_translate("StockAnalyzer", "yyyy-MM-dd"))
        self.lblEndDate.setText(_translate("StockAnalyzer", "区间结束日期"))
        self.dteEndDate.setDisplayFormat(_translate("StockAnalyzer", "yyyy-MM-dd"))
        self.btnGetData.setText(_translate("StockAnalyzer", "获取历史数据"))
        self.grpTradeRule.setTitle(_translate("StockAnalyzer", "交易策略"))
        self.lblBuyPoint.setText(_translate("StockAnalyzer", "买点涨跌幅"))
        self.lblSellPoint.setText(_translate("StockAnalyzer", "卖点涨跌幅"))
        self.cbxAllowSameDayTrade.setText(_translate("StockAnalyzer", "是否允许日内做T"))
        self.lblSameDayTradeProfit.setText(_translate("StockAnalyzer", "做T单笔收益"))
        self.lblBaseShare.setText(_translate("StockAnalyzer", "底仓股数"))
        self.lblSharePerTrade.setText(_translate("StockAnalyzer", "每笔股数"))
        self.lblMaxShare.setText(_translate("StockAnalyzer", "最大股数"))
        self.lblMinShare.setText(_translate("StockAnalyzer", "最小股数"))
        self.btnAutoFindStrategy.setText(_translate("StockAnalyzer", "自动分析获取策略"))
        self.lblBuySellSignal.setText(_translate("StockAnalyzer", "多空信号："))
        self.cbxMacdEnabled.setText(_translate("StockAnalyzer", "MACD金叉/死叉"))
        self.cbxKdjEnabled.setText(_translate("StockAnalyzer", "KDJ大于100/小于0"))
        self.cbxBollEnabled.setText(_translate("StockAnalyzer", "BOLL突破上轨/跌破下轨"))
        self.cbxBollEnabled_2.setText(_translate("StockAnalyzer", "TRIX金叉/死叉"))
        self.lblSignalTradeUnit.setText(_translate("StockAnalyzer", "信号出现时立刻买卖"))
        self.spbSignalTradeUnit.setSuffix(_translate("StockAnalyzer", "笔"))
        self.groupBox.setTitle(_translate("StockAnalyzer", "股性评估"))
        self.lblAverageTurn.setText(_translate("StockAnalyzer", "平均换手率："))
        self.lblAverageAmplitude.setText(_translate("StockAnalyzer", "每日平均振幅： "))
        self.lblHighOpenHighClose.setText(_translate("StockAnalyzer", "高开高走概率： "))
        self.lblHighOpenLowClose.setText(_translate("StockAnalyzer", "高开低走概率： "))
        self.lblLowOpenLowClose.setText(_translate("StockAnalyzer", "低开低走概率： "))
        self.lblLowOpenHighClose.setText(_translate("StockAnalyzer", "低开高走概率： "))
        self.lblAverageHighWhenUp.setText(_translate("StockAnalyzer", "阳线平均最高： "))
        self.lblAverageFallbackAmp.setText(_translate("StockAnalyzer", "阳线平均回撤："))
        self.lblAverageLowWhenDown.setText(_translate("StockAnalyzer", "阴线平均最低： "))
        self.lblAverageBounceAmp.setText(_translate("StockAnalyzer", "阴线平均反弹："))
        self.btnStartTrade.setText(_translate("StockAnalyzer", "开始模拟交易回测！"))
