# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockAnalyzer(object):
    def setupUi(self, StockAnalyzer):
        StockAnalyzer.setObjectName("StockAnalyzer")
        StockAnalyzer.resize(718, 545)
        self.centralwidget = QtWidgets.QWidget(StockAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.grpStockPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpStockPerformance.setGeometry(QtCore.QRect(10, 12, 171, 211))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpStockPerformance.setFont(font)
        self.grpStockPerformance.setObjectName("grpStockPerformance")
        self.layoutWidget = QtWidgets.QWidget(self.grpStockPerformance)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 20, 151, 180))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblStockIntervalOpen = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalOpen.setFont(font)
        self.lblStockIntervalOpen.setObjectName("lblStockIntervalOpen")
        self.verticalLayout.addWidget(self.lblStockIntervalOpen)
        self.lblStockIntervalClose = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalClose.setFont(font)
        self.lblStockIntervalClose.setObjectName("lblStockIntervalClose")
        self.verticalLayout.addWidget(self.lblStockIntervalClose)
        self.lblStockIntervalHigh = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalHigh.setFont(font)
        self.lblStockIntervalHigh.setObjectName("lblStockIntervalHigh")
        self.verticalLayout.addWidget(self.lblStockIntervalHigh)
        self.lblStockIntervalLow = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalLow.setFont(font)
        self.lblStockIntervalLow.setObjectName("lblStockIntervalLow")
        self.verticalLayout.addWidget(self.lblStockIntervalLow)
        self.lblStockIntervalAverage = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalAverage.setFont(font)
        self.lblStockIntervalAverage.setObjectName("lblStockIntervalAverage")
        self.verticalLayout.addWidget(self.lblStockIntervalAverage)
        self.lblStockIntervalTotal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalTotal.setFont(font)
        self.lblStockIntervalTotal.setObjectName("lblStockIntervalTotal")
        self.verticalLayout.addWidget(self.lblStockIntervalTotal)
        self.lblStockIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockIntervalAveragePoint.setFont(font)
        self.lblStockIntervalAveragePoint.setObjectName("lblStockIntervalAveragePoint")
        self.verticalLayout.addWidget(self.lblStockIntervalAveragePoint)
        self.lblStockUpProbability = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockUpProbability.setFont(font)
        self.lblStockUpProbability.setObjectName("lblStockUpProbability")
        self.verticalLayout.addWidget(self.lblStockUpProbability)
        self.grpMarketPerformance = QtWidgets.QGroupBox(self.centralwidget)
        self.grpMarketPerformance.setGeometry(QtCore.QRect(190, 12, 171, 211))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpMarketPerformance.setFont(font)
        self.grpMarketPerformance.setObjectName("grpMarketPerformance")
        self.layoutWidget1 = QtWidgets.QWidget(self.grpMarketPerformance)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 151, 181))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblMarketIntervalOpen = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalOpen.setFont(font)
        self.lblMarketIntervalOpen.setObjectName("lblMarketIntervalOpen")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalOpen)
        self.lblMarketIntervalClose = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalClose.setFont(font)
        self.lblMarketIntervalClose.setObjectName("lblMarketIntervalClose")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalClose)
        self.lblMarketIntervalHigh = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalHigh.setFont(font)
        self.lblMarketIntervalHigh.setObjectName("lblMarketIntervalHigh")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalHigh)
        self.lblMarketIntervalLow = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalLow.setFont(font)
        self.lblMarketIntervalLow.setObjectName("lblMarketIntervalLow")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalLow)
        self.lblMarketIntervalAverage = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalAverage.setFont(font)
        self.lblMarketIntervalAverage.setObjectName("lblMarketIntervalAverage")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAverage)
        self.lblMarketIntervalTotal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalTotal.setFont(font)
        self.lblMarketIntervalTotal.setObjectName("lblMarketIntervalTotal")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalTotal)
        self.lblMarketIntervalAveragePoint = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketIntervalAveragePoint.setFont(font)
        self.lblMarketIntervalAveragePoint.setObjectName("lblMarketIntervalAveragePoint")
        self.verticalLayout_2.addWidget(self.lblMarketIntervalAveragePoint)
        self.lblMarketUpProbability = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMarketUpProbability.setFont(font)
        self.lblMarketUpProbability.setObjectName("lblMarketUpProbability")
        self.verticalLayout_2.addWidget(self.lblMarketUpProbability)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(370, 10, 341, 27))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblStockNumber = QtWidgets.QLabel(self.layoutWidget2)
        self.lblStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockNumber.setFont(font)
        self.lblStockNumber.setObjectName("lblStockNumber")
        self.horizontalLayout_2.addWidget(self.lblStockNumber)
        self.iptStockNumber = QtWidgets.QLineEdit(self.layoutWidget2)
        self.iptStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockNumber.setFont(font)
        self.iptStockNumber.setMaxLength(6)
        self.iptStockNumber.setObjectName("iptStockNumber")
        self.horizontalLayout_2.addWidget(self.iptStockNumber)
        self.spbAnalyzeMonths = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spbAnalyzeMonths.setMinimum(1)
        self.spbAnalyzeMonths.setMaximum(9)
        self.spbAnalyzeMonths.setProperty("value", 6)
        self.spbAnalyzeMonths.setObjectName("spbAnalyzeMonths")
        self.horizontalLayout_2.addWidget(self.spbAnalyzeMonths)
        self.btnGetData = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnGetData.setFont(font)
        self.btnGetData.setObjectName("btnGetData")
        self.horizontalLayout_2.addWidget(self.btnGetData)
        self.grpNormalTradeRule = QtWidgets.QGroupBox(self.centralwidget)
        self.grpNormalTradeRule.setGeometry(QtCore.QRect(370, 42, 341, 131))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpNormalTradeRule.setFont(font)
        self.grpNormalTradeRule.setObjectName("grpNormalTradeRule")
        self.layoutWidget3 = QtWidgets.QWidget(self.grpNormalTradeRule)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 328, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget3.setFont(font)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblUpTrendBuyPoint = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblUpTrendBuyPoint.setFont(font)
        self.lblUpTrendBuyPoint.setObjectName("lblUpTrendBuyPoint")
        self.horizontalLayout_3.addWidget(self.lblUpTrendBuyPoint)
        self.spbBuyPointBase = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbBuyPointBase.setFont(font)
        self.spbBuyPointBase.setDecimals(1)
        self.spbBuyPointBase.setMinimum(-10.0)
        self.spbBuyPointBase.setMaximum(10.0)
        self.spbBuyPointBase.setSingleStep(0.1)
        self.spbBuyPointBase.setProperty("value", -3.0)
        self.spbBuyPointBase.setObjectName("spbBuyPointBase")
        self.horizontalLayout_3.addWidget(self.spbBuyPointBase)
        self.lblBuyPointStep = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblBuyPointStep.setFont(font)
        self.lblBuyPointStep.setObjectName("lblBuyPointStep")
        self.horizontalLayout_3.addWidget(self.lblBuyPointStep)
        self.spbBuyPointStep = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbBuyPointStep.setFont(font)
        self.spbBuyPointStep.setDecimals(1)
        self.spbBuyPointStep.setMinimum(0.0)
        self.spbBuyPointStep.setMaximum(5.0)
        self.spbBuyPointStep.setSingleStep(0.1)
        self.spbBuyPointStep.setProperty("value", 2.0)
        self.spbBuyPointStep.setObjectName("spbBuyPointStep")
        self.horizontalLayout_3.addWidget(self.spbBuyPointStep)
        self.lblBuyPointTrendBias = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblBuyPointTrendBias.setFont(font)
        self.lblBuyPointTrendBias.setObjectName("lblBuyPointTrendBias")
        self.horizontalLayout_3.addWidget(self.lblBuyPointTrendBias)
        self.spbBuyPointTrendBias = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbBuyPointTrendBias.setFont(font)
        self.spbBuyPointTrendBias.setDecimals(1)
        self.spbBuyPointTrendBias.setMinimum(0.0)
        self.spbBuyPointTrendBias.setMaximum(5.0)
        self.spbBuyPointTrendBias.setSingleStep(0.1)
        self.spbBuyPointTrendBias.setProperty("value", 1.0)
        self.spbBuyPointTrendBias.setObjectName("spbBuyPointTrendBias")
        self.horizontalLayout_3.addWidget(self.spbBuyPointTrendBias)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblUpTrendSellPoint = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblUpTrendSellPoint.setFont(font)
        self.lblUpTrendSellPoint.setObjectName("lblUpTrendSellPoint")
        self.horizontalLayout_4.addWidget(self.lblUpTrendSellPoint)
        self.spbSellPointBase = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSellPointBase.setFont(font)
        self.spbSellPointBase.setDecimals(1)
        self.spbSellPointBase.setMinimum(-10.0)
        self.spbSellPointBase.setMaximum(10.0)
        self.spbSellPointBase.setSingleStep(0.1)
        self.spbSellPointBase.setProperty("value", 3.0)
        self.spbSellPointBase.setObjectName("spbSellPointBase")
        self.horizontalLayout_4.addWidget(self.spbSellPointBase)
        self.lblSellPointStep = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblSellPointStep.setFont(font)
        self.lblSellPointStep.setObjectName("lblSellPointStep")
        self.horizontalLayout_4.addWidget(self.lblSellPointStep)
        self.spbSellPointStep = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSellPointStep.setFont(font)
        self.spbSellPointStep.setDecimals(1)
        self.spbSellPointStep.setMinimum(0.0)
        self.spbSellPointStep.setMaximum(5.0)
        self.spbSellPointStep.setSingleStep(0.1)
        self.spbSellPointStep.setProperty("value", 2.0)
        self.spbSellPointStep.setObjectName("spbSellPointStep")
        self.horizontalLayout_4.addWidget(self.spbSellPointStep)
        self.lblSellPointTrendBias = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblSellPointTrendBias.setFont(font)
        self.lblSellPointTrendBias.setObjectName("lblSellPointTrendBias")
        self.horizontalLayout_4.addWidget(self.lblSellPointTrendBias)
        self.spbSellPointTrendBias = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSellPointTrendBias.setFont(font)
        self.spbSellPointTrendBias.setDecimals(1)
        self.spbSellPointTrendBias.setMinimum(0.0)
        self.spbSellPointTrendBias.setMaximum(5.0)
        self.spbSellPointTrendBias.setSingleStep(0.1)
        self.spbSellPointTrendBias.setProperty("value", 1.0)
        self.spbSellPointTrendBias.setObjectName("spbSellPointTrendBias")
        self.horizontalLayout_4.addWidget(self.spbSellPointTrendBias)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxAllowSameDayTrade = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxAllowSameDayTrade.setFont(font)
        self.cbxAllowSameDayTrade.setChecked(True)
        self.cbxAllowSameDayTrade.setObjectName("cbxAllowSameDayTrade")
        self.horizontalLayout_9.addWidget(self.cbxAllowSameDayTrade)
        self.spbSameDayProfit = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSameDayProfit.setFont(font)
        self.spbSameDayProfit.setDecimals(1)
        self.spbSameDayProfit.setMinimum(-10.0)
        self.spbSameDayProfit.setMaximum(10.0)
        self.spbSameDayProfit.setSingleStep(0.1)
        self.spbSameDayProfit.setProperty("value", 2.0)
        self.spbSameDayProfit.setObjectName("spbSameDayProfit")
        self.horizontalLayout_9.addWidget(self.spbSameDayProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 222, 351, 291))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 18, 161, 261))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.layoutWidget4.setFont(font)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblAverageTurn = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageTurn.setFont(font)
        self.lblAverageTurn.setObjectName("lblAverageTurn")
        self.verticalLayout_6.addWidget(self.lblAverageTurn)
        self.lblAverageAmplitude = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageAmplitude.setFont(font)
        self.lblAverageAmplitude.setObjectName("lblAverageAmplitude")
        self.verticalLayout_6.addWidget(self.lblAverageAmplitude)
        self.lblAverageCloseUp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageCloseUp.setFont(font)
        self.lblAverageCloseUp.setObjectName("lblAverageCloseUp")
        self.verticalLayout_6.addWidget(self.lblAverageCloseUp)
        self.lblAverageHighWhenUp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageHighWhenUp.setFont(font)
        self.lblAverageHighWhenUp.setObjectName("lblAverageHighWhenUp")
        self.verticalLayout_6.addWidget(self.lblAverageHighWhenUp)
        self.lblAverageLowWhenUp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageLowWhenUp.setFont(font)
        self.lblAverageLowWhenUp.setObjectName("lblAverageLowWhenUp")
        self.verticalLayout_6.addWidget(self.lblAverageLowWhenUp)
        self.lblAverageFallbackAmp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageFallbackAmp.setFont(font)
        self.lblAverageFallbackAmp.setObjectName("lblAverageFallbackAmp")
        self.verticalLayout_6.addWidget(self.lblAverageFallbackAmp)
        self.lblAverageCloseDown = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageCloseDown.setFont(font)
        self.lblAverageCloseDown.setObjectName("lblAverageCloseDown")
        self.verticalLayout_6.addWidget(self.lblAverageCloseDown)
        self.lblAverageHighWhenDown = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageHighWhenDown.setFont(font)
        self.lblAverageHighWhenDown.setObjectName("lblAverageHighWhenDown")
        self.verticalLayout_6.addWidget(self.lblAverageHighWhenDown)
        self.lblAverageLowWhenDown = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageLowWhenDown.setFont(font)
        self.lblAverageLowWhenDown.setObjectName("lblAverageLowWhenDown")
        self.verticalLayout_6.addWidget(self.lblAverageLowWhenDown)
        self.lblAverageBounceAmp = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblAverageBounceAmp.setFont(font)
        self.lblAverageBounceAmp.setObjectName("lblAverageBounceAmp")
        self.verticalLayout_6.addWidget(self.lblAverageBounceAmp)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(180, 20, 161, 261))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblWinMarket = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblWinMarket.setFont(font)
        self.lblWinMarket.setObjectName("lblWinMarket")
        self.verticalLayout_9.addWidget(self.lblWinMarket)
        self.lblInverseMarketUp = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInverseMarketUp.setFont(font)
        self.lblInverseMarketUp.setObjectName("lblInverseMarketUp")
        self.verticalLayout_9.addWidget(self.lblInverseMarketUp)
        self.lblInverseMarketDown = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInverseMarketDown.setFont(font)
        self.lblInverseMarketDown.setObjectName("lblInverseMarketDown")
        self.verticalLayout_9.addWidget(self.lblInverseMarketDown)
        self.lblHighOpenHighClose = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblHighOpenHighClose.setFont(font)
        self.lblHighOpenHighClose.setObjectName("lblHighOpenHighClose")
        self.verticalLayout_9.addWidget(self.lblHighOpenHighClose)
        self.lblHighOpenLowClose = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblHighOpenLowClose.setFont(font)
        self.lblHighOpenLowClose.setObjectName("lblHighOpenLowClose")
        self.verticalLayout_9.addWidget(self.lblHighOpenLowClose)
        self.lblLowOpenLowClose = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblLowOpenLowClose.setFont(font)
        self.lblLowOpenLowClose.setObjectName("lblLowOpenLowClose")
        self.verticalLayout_9.addWidget(self.lblLowOpenLowClose)
        self.lblLowOpenHighClose = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblLowOpenHighClose.setFont(font)
        self.lblLowOpenHighClose.setObjectName("lblLowOpenHighClose")
        self.verticalLayout_9.addWidget(self.lblLowOpenHighClose)
        self.lblReachMaxProbability = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblReachMaxProbability.setFont(font)
        self.lblReachMaxProbability.setObjectName("lblReachMaxProbability")
        self.verticalLayout_9.addWidget(self.lblReachMaxProbability)
        self.lblStayMaxProbability = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStayMaxProbability.setFont(font)
        self.lblStayMaxProbability.setObjectName("lblStayMaxProbability")
        self.verticalLayout_9.addWidget(self.lblStayMaxProbability)
        self.lblReachMinProbability = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblReachMinProbability.setFont(font)
        self.lblReachMinProbability.setObjectName("lblReachMinProbability")
        self.verticalLayout_9.addWidget(self.lblReachMinProbability)
        self.lblStayMinProbability = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStayMinProbability.setFont(font)
        self.lblStayMinProbability.setObjectName("lblStayMinProbability")
        self.verticalLayout_9.addWidget(self.lblStayMinProbability)
        self.grpTrendIndicator = QtWidgets.QGroupBox(self.centralwidget)
        self.grpTrendIndicator.setGeometry(QtCore.QRect(370, 180, 171, 231))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.grpTrendIndicator.setFont(font)
        self.grpTrendIndicator.setObjectName("grpTrendIndicator")
        self.layoutWidget6 = QtWidgets.QWidget(self.grpTrendIndicator)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 21, 151, 199))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rbnMacd = QtWidgets.QRadioButton(self.layoutWidget6)
        self.rbnMacd.setChecked(True)
        self.rbnMacd.setObjectName("rbnMacd")
        self.verticalLayout_4.addWidget(self.rbnMacd)
        self.rbnTrix = QtWidgets.QRadioButton(self.layoutWidget6)
        self.rbnTrix.setObjectName("rbnTrix")
        self.verticalLayout_4.addWidget(self.rbnTrix)
        self.rbnExpma = QtWidgets.QRadioButton(self.layoutWidget6)
        self.rbnExpma.setObjectName("rbnExpma")
        self.verticalLayout_4.addWidget(self.rbnExpma)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbnMa = QtWidgets.QRadioButton(self.layoutWidget6)
        self.rbnMa.setObjectName("rbnMa")
        self.horizontalLayout.addWidget(self.rbnMa)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lblMaShort = QtWidgets.QLabel(self.layoutWidget6)
        self.lblMaShort.setObjectName("lblMaShort")
        self.horizontalLayout_11.addWidget(self.lblMaShort)
        self.cbbMaShort = QtWidgets.QComboBox(self.layoutWidget6)
        self.cbbMaShort.setEnabled(False)
        self.cbbMaShort.setObjectName("cbbMaShort")
        self.horizontalLayout_11.addWidget(self.cbbMaShort)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblMaLong = QtWidgets.QLabel(self.layoutWidget6)
        self.lblMaLong.setObjectName("lblMaLong")
        self.horizontalLayout_14.addWidget(self.lblMaLong)
        self.cbbMaLong = QtWidgets.QComboBox(self.layoutWidget6)
        self.cbbMaLong.setEnabled(False)
        self.cbbMaLong.setObjectName("cbbMaLong")
        self.horizontalLayout_14.addWidget(self.cbbMaLong)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lblTrendChangeTradeUnit = QtWidgets.QLabel(self.layoutWidget6)
        self.lblTrendChangeTradeUnit.setObjectName("lblTrendChangeTradeUnit")
        self.horizontalLayout_16.addWidget(self.lblTrendChangeTradeUnit)
        self.spbTrendChangeTradeUnit = QtWidgets.QSpinBox(self.layoutWidget6)
        self.spbTrendChangeTradeUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spbTrendChangeTradeUnit.setMinimum(0)
        self.spbTrendChangeTradeUnit.setMaximum(10)
        self.spbTrendChangeTradeUnit.setProperty("value", 1)
        self.spbTrendChangeTradeUnit.setObjectName("spbTrendChangeTradeUnit")
        self.horizontalLayout_16.addWidget(self.spbTrendChangeTradeUnit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.grpShareAllowed = QtWidgets.QGroupBox(self.centralwidget)
        self.grpShareAllowed.setGeometry(QtCore.QRect(550, 330, 161, 151))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.grpShareAllowed.setFont(font)
        self.grpShareAllowed.setObjectName("grpShareAllowed")
        self.layoutWidget7 = QtWidgets.QWidget(self.grpShareAllowed)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 20, 141, 120))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblInitialShare = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInitialShare.setFont(font)
        self.lblInitialShare.setObjectName("lblInitialShare")
        self.horizontalLayout_5.addWidget(self.lblInitialShare)
        self.spbInitialShare = QtWidgets.QSpinBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbInitialShare.setFont(font)
        self.spbInitialShare.setMinimum(1)
        self.spbInitialShare.setMaximum(1000)
        self.spbInitialShare.setSingleStep(1)
        self.spbInitialShare.setProperty("value", 20)
        self.spbInitialShare.setObjectName("spbInitialShare")
        self.horizontalLayout_5.addWidget(self.spbInitialShare)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblSharePerTrade = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblSharePerTrade.setFont(font)
        self.lblSharePerTrade.setObjectName("lblSharePerTrade")
        self.horizontalLayout_6.addWidget(self.lblSharePerTrade)
        self.spbSharePerTrade = QtWidgets.QSpinBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbSharePerTrade.setFont(font)
        self.spbSharePerTrade.setMinimum(1)
        self.spbSharePerTrade.setMaximum(1000)
        self.spbSharePerTrade.setSingleStep(1)
        self.spbSharePerTrade.setProperty("value", 10)
        self.spbSharePerTrade.setObjectName("spbSharePerTrade")
        self.horizontalLayout_6.addWidget(self.spbSharePerTrade)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblMaxShare = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMaxShare.setFont(font)
        self.lblMaxShare.setObjectName("lblMaxShare")
        self.horizontalLayout_7.addWidget(self.lblMaxShare)
        self.spbMaxShare = QtWidgets.QSpinBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMaxShare.setFont(font)
        self.spbMaxShare.setMinimum(1)
        self.spbMaxShare.setMaximum(1000)
        self.spbMaxShare.setSingleStep(1)
        self.spbMaxShare.setProperty("value", 50)
        self.spbMaxShare.setObjectName("spbMaxShare")
        self.horizontalLayout_7.addWidget(self.spbMaxShare)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblMinShare = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMinShare.setFont(font)
        self.lblMinShare.setObjectName("lblMinShare")
        self.horizontalLayout_8.addWidget(self.lblMinShare)
        self.spbMinShare = QtWidgets.QSpinBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMinShare.setFont(font)
        self.spbMinShare.setMinimum(0)
        self.spbMinShare.setMaximum(1000)
        self.spbMinShare.setSingleStep(1)
        self.spbMinShare.setProperty("value", 0)
        self.spbMinShare.setObjectName("spbMinShare")
        self.horizontalLayout_8.addWidget(self.spbMinShare)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.grpShortTermSignal = QtWidgets.QGroupBox(self.centralwidget)
        self.grpShortTermSignal.setGeometry(QtCore.QRect(550, 180, 161, 141))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.grpShortTermSignal.setFont(font)
        self.grpShortTermSignal.setObjectName("grpShortTermSignal")
        self.layoutWidget8 = QtWidgets.QWidget(self.grpShortTermSignal)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 144, 112))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cbxKdjEnabled = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cbxKdjEnabled.setChecked(False)
        self.cbxKdjEnabled.setObjectName("cbxKdjEnabled")
        self.verticalLayout_7.addWidget(self.cbxKdjEnabled)
        self.cbxBollEnabled = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cbxBollEnabled.setChecked(False)
        self.cbxBollEnabled.setObjectName("cbxBollEnabled")
        self.verticalLayout_7.addWidget(self.cbxBollEnabled)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbxBiasEnabled = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cbxBiasEnabled.setChecked(False)
        self.cbxBiasEnabled.setObjectName("cbxBiasEnabled")
        self.horizontalLayout_12.addWidget(self.cbxBiasEnabled)
        self.spbBiasThreshold = QtWidgets.QSpinBox(self.layoutWidget8)
        self.spbBiasThreshold.setEnabled(False)
        self.spbBiasThreshold.setMinimum(5)
        self.spbBiasThreshold.setMaximum(20)
        self.spbBiasThreshold.setProperty("value", 10)
        self.spbBiasThreshold.setObjectName("spbBiasThreshold")
        self.horizontalLayout_12.addWidget(self.spbBiasThreshold)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblSignalTradeUnit = QtWidgets.QLabel(self.layoutWidget8)
        self.lblSignalTradeUnit.setObjectName("lblSignalTradeUnit")
        self.horizontalLayout_13.addWidget(self.lblSignalTradeUnit)
        self.spbSignalTradeUnit = QtWidgets.QSpinBox(self.layoutWidget8)
        self.spbSignalTradeUnit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spbSignalTradeUnit.setMinimum(0)
        self.spbSignalTradeUnit.setMaximum(100)
        self.spbSignalTradeUnit.setObjectName("spbSignalTradeUnit")
        self.horizontalLayout_13.addWidget(self.spbSignalTradeUnit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.cbxTrendEnabled = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxTrendEnabled.setGeometry(QtCore.QRect(458, 180, 16, 18))
        self.cbxTrendEnabled.setText("")
        self.cbxTrendEnabled.setChecked(True)
        self.cbxTrendEnabled.setObjectName("cbxTrendEnabled")
        self.btnStartTrade = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartTrade.setGeometry(QtCore.QRect(550, 490, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartTrade.setFont(font)
        self.btnStartTrade.setObjectName("btnStartTrade")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(370, 421, 171, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnPlotOpenCloseDistribution = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnPlotOpenCloseDistribution.setFont(font)
        self.btnPlotOpenCloseDistribution.setObjectName("btnPlotOpenCloseDistribution")
        self.verticalLayout_8.addWidget(self.btnPlotOpenCloseDistribution)
        self.btnPlotHighLowDistribution = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnPlotHighLowDistribution.setFont(font)
        self.btnPlotHighLowDistribution.setObjectName("btnPlotHighLowDistribution")
        self.verticalLayout_8.addWidget(self.btnPlotHighLowDistribution)
        self.btnAutoFindStrategy = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnAutoFindStrategy.setFont(font)
        self.btnAutoFindStrategy.setObjectName("btnAutoFindStrategy")
        self.verticalLayout_8.addWidget(self.btnAutoFindStrategy)
        StockAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 22))
        self.menubar.setObjectName("menubar")
        StockAnalyzer.setMenuBar(self.menubar)

        self.retranslateUi(StockAnalyzer)
        self.btnGetData.clicked.connect(StockAnalyzer.get_history_data)
        self.btnAutoFindStrategy.clicked.connect(StockAnalyzer.auto_get_strategy)
        self.cbxAllowSameDayTrade.clicked['bool'].connect(self.spbSameDayProfit.setEnabled)
        self.cbxBiasEnabled.clicked['bool'].connect(self.spbBiasThreshold.setEnabled)
        self.btnStartTrade.clicked.connect(StockAnalyzer.start_trade)
        self.cbxTrendEnabled.clicked['bool'].connect(self.grpTrendIndicator.setEnabled)
        self.cbxTrendEnabled.clicked['bool'].connect(self.spbBuyPointTrendBias.setEnabled)
        self.cbxTrendEnabled.clicked['bool'].connect(self.spbSellPointTrendBias.setEnabled)
        self.rbnMa.toggled['bool'].connect(self.cbbMaShort.setEnabled)
        self.rbnMa.toggled['bool'].connect(self.cbbMaLong.setEnabled)
        self.btnPlotHighLowDistribution.clicked.connect(StockAnalyzer.plot_high_low_distribution)
        self.btnPlotOpenCloseDistribution.clicked.connect(StockAnalyzer.plot_open_close_distribution)
        QtCore.QMetaObject.connectSlotsByName(StockAnalyzer)

    def retranslateUi(self, StockAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        StockAnalyzer.setWindowTitle(_translate("StockAnalyzer", "个股股性分析"))
        self.grpStockPerformance.setTitle(_translate("StockAnalyzer", "区间个股表现"))
        self.lblStockIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘价格： "))
        self.lblStockIntervalClose.setText(_translate("StockAnalyzer", "区间收盘价格： "))
        self.lblStockIntervalHigh.setText(_translate("StockAnalyzer", "区间最高价格： "))
        self.lblStockIntervalLow.setText(_translate("StockAnalyzer", "区间最低价格： "))
        self.lblStockIntervalAverage.setText(_translate("StockAnalyzer", "区间平均价格： "))
        self.lblStockIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblStockIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblStockUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.grpMarketPerformance.setTitle(_translate("StockAnalyzer", "同期大盘表现"))
        self.lblMarketIntervalOpen.setText(_translate("StockAnalyzer", "区间开盘点位： "))
        self.lblMarketIntervalClose.setText(_translate("StockAnalyzer", "区间收盘点位： "))
        self.lblMarketIntervalHigh.setText(_translate("StockAnalyzer", "区间最高点位： "))
        self.lblMarketIntervalLow.setText(_translate("StockAnalyzer", "区间最低点位： "))
        self.lblMarketIntervalAverage.setText(_translate("StockAnalyzer", "区间平均点位： "))
        self.lblMarketIntervalTotal.setText(_translate("StockAnalyzer", "区间累计涨幅： "))
        self.lblMarketIntervalAveragePoint.setText(_translate("StockAnalyzer", "平均每日涨幅： "))
        self.lblMarketUpProbability.setText(_translate("StockAnalyzer", "每日上涨概率： "))
        self.lblStockNumber.setText(_translate("StockAnalyzer", "股票代码/名称"))
        self.iptStockNumber.setText(_translate("StockAnalyzer", "贵州茅台"))
        self.spbAnalyzeMonths.setSuffix(_translate("StockAnalyzer", "个月"))
        self.spbAnalyzeMonths.setPrefix(_translate("StockAnalyzer", "最近"))
        self.btnGetData.setText(_translate("StockAnalyzer", "获取数据"))
        self.grpNormalTradeRule.setTitle(_translate("StockAnalyzer", "基础交易策略"))
        self.lblUpTrendBuyPoint.setText(_translate("StockAnalyzer", "基准买点"))
        self.spbBuyPointBase.setSuffix(_translate("StockAnalyzer", "%"))
        self.lblBuyPointStep.setText(_translate("StockAnalyzer", "间隔"))
        self.spbBuyPointStep.setSuffix(_translate("StockAnalyzer", "%"))
        self.lblBuyPointTrendBias.setText(_translate("StockAnalyzer", "趋势偏移"))
        self.spbBuyPointTrendBias.setSuffix(_translate("StockAnalyzer", "%"))
        self.lblUpTrendSellPoint.setText(_translate("StockAnalyzer", "基准卖点"))
        self.spbSellPointBase.setSuffix(_translate("StockAnalyzer", "%"))
        self.lblSellPointStep.setText(_translate("StockAnalyzer", "间隔"))
        self.spbSellPointStep.setSuffix(_translate("StockAnalyzer", "%"))
        self.lblSellPointTrendBias.setText(_translate("StockAnalyzer", "趋势偏移"))
        self.spbSellPointTrendBias.setSuffix(_translate("StockAnalyzer", "%"))
        self.cbxAllowSameDayTrade.setText(_translate("StockAnalyzer", "允许日内做T     每笔交易预期收益"))
        self.spbSameDayProfit.setSuffix(_translate("StockAnalyzer", "%"))
        self.groupBox.setTitle(_translate("StockAnalyzer", "股性评估"))
        self.lblAverageTurn.setText(_translate("StockAnalyzer", "平均换手率："))
        self.lblAverageAmplitude.setText(_translate("StockAnalyzer", "每日平均振幅： "))
        self.lblAverageCloseUp.setText(_translate("StockAnalyzer", "阳线平均涨幅： "))
        self.lblAverageHighWhenUp.setText(_translate("StockAnalyzer", "阳线平均最高： "))
        self.lblAverageLowWhenUp.setText(_translate("StockAnalyzer", "阳线平均最低： "))
        self.lblAverageFallbackAmp.setText(_translate("StockAnalyzer", "阳线平均回撤："))
        self.lblAverageCloseDown.setText(_translate("StockAnalyzer", "阴线平均跌幅： "))
        self.lblAverageHighWhenDown.setText(_translate("StockAnalyzer", "阴线平均最高： "))
        self.lblAverageLowWhenDown.setText(_translate("StockAnalyzer", "阴线平均最低： "))
        self.lblAverageBounceAmp.setText(_translate("StockAnalyzer", "阴线平均反弹："))
        self.lblWinMarket.setText(_translate("StockAnalyzer", "跑赢大盘日数："))
        self.lblInverseMarketUp.setText(_translate("StockAnalyzer", "逆市上涨日数："))
        self.lblInverseMarketDown.setText(_translate("StockAnalyzer", "逆市下跌日数："))
        self.lblHighOpenHighClose.setText(_translate("StockAnalyzer", "高开高走概率： "))
        self.lblHighOpenLowClose.setText(_translate("StockAnalyzer", "高开低走概率： "))
        self.lblLowOpenLowClose.setText(_translate("StockAnalyzer", "低开低走概率： "))
        self.lblLowOpenHighClose.setText(_translate("StockAnalyzer", "低开高走概率： "))
        self.lblReachMaxProbability.setText(_translate("StockAnalyzer", "涨停触板概率： "))
        self.lblStayMaxProbability.setText(_translate("StockAnalyzer", "涨停收盘概率： "))
        self.lblReachMinProbability.setText(_translate("StockAnalyzer", "跌停触板概率： "))
        self.lblStayMinProbability.setText(_translate("StockAnalyzer", "跌停收盘概率： "))
        self.grpTrendIndicator.setTitle(_translate("StockAnalyzer", "多空趋势信号"))
        self.rbnMacd.setText(_translate("StockAnalyzer", "MACD交叉"))
        self.rbnTrix.setText(_translate("StockAnalyzer", "TRIX交叉"))
        self.rbnExpma.setText(_translate("StockAnalyzer", "EXPMA交叉"))
        self.rbnMa.setText(_translate("StockAnalyzer", "短长期均线交叉"))
        self.lblMaShort.setText(_translate("StockAnalyzer", "短期均线"))
        self.lblMaLong.setText(_translate("StockAnalyzer", "长期均线"))
        self.lblTrendChangeTradeUnit.setText(_translate("StockAnalyzer", "趋势扭转时交易"))
        self.spbTrendChangeTradeUnit.setSuffix(_translate("StockAnalyzer", "笔"))
        self.grpShareAllowed.setTitle(_translate("StockAnalyzer", "仓位控制策略"))
        self.lblInitialShare.setText(_translate("StockAnalyzer", "初始底仓"))
        self.spbInitialShare.setSuffix(_translate("StockAnalyzer", "手"))
        self.lblSharePerTrade.setText(_translate("StockAnalyzer", "每笔交易"))
        self.spbSharePerTrade.setSuffix(_translate("StockAnalyzer", "手"))
        self.lblMaxShare.setText(_translate("StockAnalyzer", "最大持仓"))
        self.spbMaxShare.setSuffix(_translate("StockAnalyzer", "手"))
        self.lblMinShare.setText(_translate("StockAnalyzer", "最小持仓"))
        self.spbMinShare.setSuffix(_translate("StockAnalyzer", "手"))
        self.grpShortTermSignal.setTitle(_translate("StockAnalyzer", "超买超卖信号"))
        self.cbxKdjEnabled.setText(_translate("StockAnalyzer", "KDJ出现极值"))
        self.cbxBollEnabled.setText(_translate("StockAnalyzer", "BOLL穿过上下轨"))
        self.cbxBiasEnabled.setText(_translate("StockAnalyzer", "BIAS达到±"))
        self.lblSignalTradeUnit.setText(_translate("StockAnalyzer", "出现信号时交易"))
        self.spbSignalTradeUnit.setSuffix(_translate("StockAnalyzer", "笔"))
        self.btnStartTrade.setText(_translate("StockAnalyzer", "开始模拟交易回测"))
        self.btnPlotOpenCloseDistribution.setText(_translate("StockAnalyzer", "开盘收盘分布图"))
        self.btnPlotHighLowDistribution.setText(_translate("StockAnalyzer", "最高最低分布图"))
        self.btnAutoFindStrategy.setText(_translate("StockAnalyzer", "自动分析获取策略"))
