# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TradeSimulator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradeSimulator(object):
    def setupUi(self, TradeSimulator):
        TradeSimulator.setObjectName("TradeSimulator")
        TradeSimulator.resize(1042, 778)
        self.layoutWidget = QtWidgets.QWidget(TradeSimulator)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 341, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblBuyCount = QtWidgets.QLabel(self.layoutWidget)
        self.lblBuyCount.setObjectName("lblBuyCount")
        self.verticalLayout.addWidget(self.lblBuyCount)
        self.lblSellCount = QtWidgets.QLabel(self.layoutWidget)
        self.lblSellCount.setObjectName("lblSellCount")
        self.verticalLayout.addWidget(self.lblSellCount)
        self.lblSameDayPerformance = QtWidgets.QLabel(self.layoutWidget)
        self.lblSameDayPerformance.setObjectName("lblSameDayPerformance")
        self.verticalLayout.addWidget(self.lblSameDayPerformance)
        self.lblTotalFee = QtWidgets.QLabel(self.layoutWidget)
        self.lblTotalFee.setObjectName("lblTotalFee")
        self.verticalLayout.addWidget(self.lblTotalFee)
        self.lblOriginalInvestment = QtWidgets.QLabel(self.layoutWidget)
        self.lblOriginalInvestment.setObjectName("lblOriginalInvestment")
        self.verticalLayout.addWidget(self.lblOriginalInvestment)
        self.lblFinalAsset = QtWidgets.QLabel(self.layoutWidget)
        self.lblFinalAsset.setObjectName("lblFinalAsset")
        self.verticalLayout.addWidget(self.lblFinalAsset)
        self.lblTotalProfit = QtWidgets.QLabel(self.layoutWidget)
        self.lblTotalProfit.setObjectName("lblTotalProfit")
        self.verticalLayout.addWidget(self.lblTotalProfit)
        self.lblTotalReturn = QtWidgets.QLabel(self.layoutWidget)
        self.lblTotalReturn.setObjectName("lblTotalReturn")
        self.verticalLayout.addWidget(self.lblTotalReturn)
        self.tblTradeHistory = QtWidgets.QTableWidget(TradeSimulator)
        self.tblTradeHistory.setGeometry(QtCore.QRect(20, 210, 1001, 551))
        self.tblTradeHistory.setRowCount(0)
        self.tblTradeHistory.setColumnCount(16)
        self.tblTradeHistory.setObjectName("tblTradeHistory")
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(15, item)

        self.retranslateUi(TradeSimulator)
        QtCore.QMetaObject.connectSlotsByName(TradeSimulator)

    def retranslateUi(self, TradeSimulator):
        _translate = QtCore.QCoreApplication.translate
        TradeSimulator.setWindowTitle(_translate("TradeSimulator", "模拟交易"))
        self.lblBuyCount.setText(_translate("TradeSimulator", "买入次数："))
        self.lblSellCount.setText(_translate("TradeSimulator", "卖出次数："))
        self.lblSameDayPerformance.setText(_translate("TradeSimulator", "做T次数："))
        self.lblTotalFee.setText(_translate("TradeSimulator", "总手续费："))
        self.lblOriginalInvestment.setText(_translate("TradeSimulator", "初始成本："))
        self.lblFinalAsset.setText(_translate("TradeSimulator", "最终资产："))
        self.lblTotalProfit.setText(_translate("TradeSimulator", "累计收益："))
        self.lblTotalReturn.setText(_translate("TradeSimulator", "盈亏比例："))
        item = self.tblTradeHistory.horizontalHeaderItem(0)
        item.setText(_translate("TradeSimulator", "交易时间"))
        item = self.tblTradeHistory.horizontalHeaderItem(1)
        item.setText(_translate("TradeSimulator", "交易操作"))
        item = self.tblTradeHistory.horizontalHeaderItem(2)
        item.setText(_translate("TradeSimulator", "成交价格"))
        item = self.tblTradeHistory.horizontalHeaderItem(3)
        item.setText(_translate("TradeSimulator", "成交数"))
        item = self.tblTradeHistory.horizontalHeaderItem(4)
        item.setText(_translate("TradeSimulator", "持仓量"))
        item = self.tblTradeHistory.horizontalHeaderItem(5)
        item.setText(_translate("TradeSimulator", "当日开盘"))
        item = self.tblTradeHistory.horizontalHeaderItem(6)
        item.setText(_translate("TradeSimulator", "当日最高"))
        item = self.tblTradeHistory.horizontalHeaderItem(7)
        item.setText(_translate("TradeSimulator", "当日最低"))
        item = self.tblTradeHistory.horizontalHeaderItem(8)
        item.setText(_translate("TradeSimulator", "当日收盘"))
        item = self.tblTradeHistory.horizontalHeaderItem(9)
        item.setText(_translate("TradeSimulator", "MA5"))
        item = self.tblTradeHistory.horizontalHeaderItem(10)
        item.setText(_translate("TradeSimulator", "换手率"))
        item = self.tblTradeHistory.horizontalHeaderItem(11)
        item.setText(_translate("TradeSimulator", "长线偏移"))
        item = self.tblTradeHistory.horizontalHeaderItem(12)
        item.setText(_translate("TradeSimulator", "短线多空"))
        item = self.tblTradeHistory.horizontalHeaderItem(13)
        item.setText(_translate("TradeSimulator", "平均成本"))
        item = self.tblTradeHistory.horizontalHeaderItem(14)
        item.setText(_translate("TradeSimulator", "总收益"))
        item = self.tblTradeHistory.horizontalHeaderItem(15)
        item.setText(_translate("TradeSimulator", "总利润"))
