# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TradeSimulator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradeSimulator(object):
    def setupUi(self, TradeSimulator):
        TradeSimulator.setObjectName("TradeSimulator")
        TradeSimulator.resize(1017, 850)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(TradeSimulator)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.grpUpTrendStartSignal = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpUpTrendStartSignal.setFont(font)
        self.grpUpTrendStartSignal.setObjectName("grpUpTrendStartSignal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpUpTrendStartSignal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rbnUpTrendStartByMACD = QtWidgets.QRadioButton(self.grpUpTrendStartSignal)
        self.rbnUpTrendStartByMACD.setChecked(False)
        self.rbnUpTrendStartByMACD.setObjectName("rbnUpTrendStartByMACD")
        self.horizontalLayout_10.addWidget(self.rbnUpTrendStartByMACD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbnUpTrendStartByMAStay = QtWidgets.QRadioButton(self.grpUpTrendStartSignal)
        self.rbnUpTrendStartByMAStay.setChecked(False)
        self.rbnUpTrendStartByMAStay.setObjectName("rbnUpTrendStartByMAStay")
        self.horizontalLayout_2.addWidget(self.rbnUpTrendStartByMAStay)
        self.spbUpTrendStartMAStayDays = QtWidgets.QSpinBox(self.grpUpTrendStartSignal)
        self.spbUpTrendStartMAStayDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendStartMAStayDays.setFont(font)
        self.spbUpTrendStartMAStayDays.setMinimum(1)
        self.spbUpTrendStartMAStayDays.setMaximum(10)
        self.spbUpTrendStartMAStayDays.setSingleStep(1)
        self.spbUpTrendStartMAStayDays.setProperty("value", 2)
        self.spbUpTrendStartMAStayDays.setObjectName("spbUpTrendStartMAStayDays")
        self.horizontalLayout_2.addWidget(self.spbUpTrendStartMAStayDays)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.rbnUpTrendStartByMACross = QtWidgets.QRadioButton(self.grpUpTrendStartSignal)
        self.rbnUpTrendStartByMACross.setChecked(True)
        self.rbnUpTrendStartByMACross.setObjectName("rbnUpTrendStartByMACross")
        self.verticalLayout_2.addWidget(self.rbnUpTrendStartByMACross)
        self.horizontalLayout_28.addWidget(self.grpUpTrendStartSignal)
        self.grpUpTrendEndSignal = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpUpTrendEndSignal.setFont(font)
        self.grpUpTrendEndSignal.setObjectName("grpUpTrendEndSignal")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.grpUpTrendEndSignal)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.rbnUpTrendEndByMacd = QtWidgets.QRadioButton(self.grpUpTrendEndSignal)
        self.rbnUpTrendEndByMacd.setChecked(False)
        self.rbnUpTrendEndByMacd.setObjectName("rbnUpTrendEndByMacd")
        self.horizontalLayout_29.addWidget(self.rbnUpTrendEndByMacd)
        self.spbUpTrendEndMACDFallDays = QtWidgets.QSpinBox(self.grpUpTrendEndSignal)
        self.spbUpTrendEndMACDFallDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendEndMACDFallDays.setFont(font)
        self.spbUpTrendEndMACDFallDays.setMinimum(1)
        self.spbUpTrendEndMACDFallDays.setMaximum(10)
        self.spbUpTrendEndMACDFallDays.setSingleStep(1)
        self.spbUpTrendEndMACDFallDays.setProperty("value", 3)
        self.spbUpTrendEndMACDFallDays.setObjectName("spbUpTrendEndMACDFallDays")
        self.horizontalLayout_29.addWidget(self.spbUpTrendEndMACDFallDays)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.rbnUpTrendEndByMaBreak = QtWidgets.QRadioButton(self.grpUpTrendEndSignal)
        self.rbnUpTrendEndByMaBreak.setChecked(False)
        self.rbnUpTrendEndByMaBreak.setObjectName("rbnUpTrendEndByMaBreak")
        self.horizontalLayout_30.addWidget(self.rbnUpTrendEndByMaBreak)
        self.spbUpTrendEndMABreakDays = QtWidgets.QSpinBox(self.grpUpTrendEndSignal)
        self.spbUpTrendEndMABreakDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendEndMABreakDays.setFont(font)
        self.spbUpTrendEndMABreakDays.setMinimum(1)
        self.spbUpTrendEndMABreakDays.setMaximum(10)
        self.spbUpTrendEndMABreakDays.setSingleStep(1)
        self.spbUpTrendEndMABreakDays.setProperty("value", 2)
        self.spbUpTrendEndMABreakDays.setObjectName("spbUpTrendEndMABreakDays")
        self.horizontalLayout_30.addWidget(self.spbUpTrendEndMABreakDays)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.rbnUpTrendEndByNoHighAgain = QtWidgets.QRadioButton(self.grpUpTrendEndSignal)
        self.rbnUpTrendEndByNoHighAgain.setChecked(True)
        self.rbnUpTrendEndByNoHighAgain.setObjectName("rbnUpTrendEndByNoHighAgain")
        self.horizontalLayout_33.addWidget(self.rbnUpTrendEndByNoHighAgain)
        self.spbUpTrendEndNoHighDays = QtWidgets.QSpinBox(self.grpUpTrendEndSignal)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendEndNoHighDays.setFont(font)
        self.spbUpTrendEndNoHighDays.setMinimum(2)
        self.spbUpTrendEndNoHighDays.setMaximum(10)
        self.spbUpTrendEndNoHighDays.setSingleStep(1)
        self.spbUpTrendEndNoHighDays.setProperty("value", 5)
        self.spbUpTrendEndNoHighDays.setObjectName("spbUpTrendEndNoHighDays")
        self.horizontalLayout_33.addWidget(self.spbUpTrendEndNoHighDays)
        self.lblUpTrendEndByNoHighAgain = QtWidgets.QLabel(self.grpUpTrendEndSignal)
        self.lblUpTrendEndByNoHighAgain.setObjectName("lblUpTrendEndByNoHighAgain")
        self.horizontalLayout_33.addWidget(self.lblUpTrendEndByNoHighAgain)
        self.verticalLayout_8.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_28.addWidget(self.grpUpTrendEndSignal)
        self.grpDownTrendStartSignal = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpDownTrendStartSignal.setFont(font)
        self.grpDownTrendStartSignal.setObjectName("grpDownTrendStartSignal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grpDownTrendStartSignal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.rbnDownTrendStartByMACD = QtWidgets.QRadioButton(self.grpDownTrendStartSignal)
        self.rbnDownTrendStartByMACD.setChecked(False)
        self.rbnDownTrendStartByMACD.setObjectName("rbnDownTrendStartByMACD")
        self.horizontalLayout_18.addWidget(self.rbnDownTrendStartByMACD)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rbnDownTrendStartByMaBreak = QtWidgets.QRadioButton(self.grpDownTrendStartSignal)
        self.rbnDownTrendStartByMaBreak.setChecked(False)
        self.rbnDownTrendStartByMaBreak.setObjectName("rbnDownTrendStartByMaBreak")
        self.horizontalLayout_19.addWidget(self.rbnDownTrendStartByMaBreak)
        self.spbDownTrendStartMABreakDays = QtWidgets.QSpinBox(self.grpDownTrendStartSignal)
        self.spbDownTrendStartMABreakDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendStartMABreakDays.setFont(font)
        self.spbDownTrendStartMABreakDays.setMinimum(1)
        self.spbDownTrendStartMABreakDays.setMaximum(10)
        self.spbDownTrendStartMABreakDays.setSingleStep(1)
        self.spbDownTrendStartMABreakDays.setProperty("value", 2)
        self.spbDownTrendStartMABreakDays.setObjectName("spbDownTrendStartMABreakDays")
        self.horizontalLayout_19.addWidget(self.spbDownTrendStartMABreakDays)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.rbnDownTrendStartByMACross = QtWidgets.QRadioButton(self.grpDownTrendStartSignal)
        self.rbnDownTrendStartByMACross.setChecked(True)
        self.rbnDownTrendStartByMACross.setObjectName("rbnDownTrendStartByMACross")
        self.verticalLayout_4.addWidget(self.rbnDownTrendStartByMACross)
        self.horizontalLayout_28.addWidget(self.grpDownTrendStartSignal)
        self.grpDownTrendEndSignal = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpDownTrendEndSignal.setFont(font)
        self.grpDownTrendEndSignal.setObjectName("grpDownTrendEndSignal")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.grpDownTrendEndSignal)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.rbnDownTrendEndByMacd = QtWidgets.QRadioButton(self.grpDownTrendEndSignal)
        self.rbnDownTrendEndByMacd.setChecked(False)
        self.rbnDownTrendEndByMacd.setObjectName("rbnDownTrendEndByMacd")
        self.horizontalLayout_31.addWidget(self.rbnDownTrendEndByMacd)
        self.spbDownTrendEndMACDRiseDays = QtWidgets.QSpinBox(self.grpDownTrendEndSignal)
        self.spbDownTrendEndMACDRiseDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendEndMACDRiseDays.setFont(font)
        self.spbDownTrendEndMACDRiseDays.setMinimum(1)
        self.spbDownTrendEndMACDRiseDays.setMaximum(10)
        self.spbDownTrendEndMACDRiseDays.setSingleStep(1)
        self.spbDownTrendEndMACDRiseDays.setProperty("value", 3)
        self.spbDownTrendEndMACDRiseDays.setObjectName("spbDownTrendEndMACDRiseDays")
        self.horizontalLayout_31.addWidget(self.spbDownTrendEndMACDRiseDays)
        self.verticalLayout_9.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.rbnDownTrendEndByMAStay = QtWidgets.QRadioButton(self.grpDownTrendEndSignal)
        self.rbnDownTrendEndByMAStay.setChecked(False)
        self.rbnDownTrendEndByMAStay.setObjectName("rbnDownTrendEndByMAStay")
        self.horizontalLayout_32.addWidget(self.rbnDownTrendEndByMAStay)
        self.spbDownTrendEndMAStayDays = QtWidgets.QSpinBox(self.grpDownTrendEndSignal)
        self.spbDownTrendEndMAStayDays.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendEndMAStayDays.setFont(font)
        self.spbDownTrendEndMAStayDays.setMinimum(1)
        self.spbDownTrendEndMAStayDays.setMaximum(10)
        self.spbDownTrendEndMAStayDays.setSingleStep(1)
        self.spbDownTrendEndMAStayDays.setProperty("value", 2)
        self.spbDownTrendEndMAStayDays.setObjectName("spbDownTrendEndMAStayDays")
        self.horizontalLayout_32.addWidget(self.spbDownTrendEndMAStayDays)
        self.verticalLayout_9.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.rbnDownTrendEndByNoLowAgain = QtWidgets.QRadioButton(self.grpDownTrendEndSignal)
        self.rbnDownTrendEndByNoLowAgain.setChecked(True)
        self.rbnDownTrendEndByNoLowAgain.setObjectName("rbnDownTrendEndByNoLowAgain")
        self.horizontalLayout_34.addWidget(self.rbnDownTrendEndByNoLowAgain)
        self.spbDownTrendEndNoLowDays = QtWidgets.QSpinBox(self.grpDownTrendEndSignal)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendEndNoLowDays.setFont(font)
        self.spbDownTrendEndNoLowDays.setMinimum(2)
        self.spbDownTrendEndNoLowDays.setMaximum(10)
        self.spbDownTrendEndNoLowDays.setSingleStep(1)
        self.spbDownTrendEndNoLowDays.setProperty("value", 5)
        self.spbDownTrendEndNoLowDays.setObjectName("spbDownTrendEndNoLowDays")
        self.horizontalLayout_34.addWidget(self.spbDownTrendEndNoLowDays)
        self.lblDownTrendEndByNoLowAgain = QtWidgets.QLabel(self.grpDownTrendEndSignal)
        self.lblDownTrendEndByNoLowAgain.setObjectName("lblDownTrendEndByNoLowAgain")
        self.horizontalLayout_34.addWidget(self.lblDownTrendEndByNoLowAgain)
        self.verticalLayout_9.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_28.addWidget(self.grpDownTrendEndSignal)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lblMAPeriodShort = QtWidgets.QLabel(TradeSimulator)
        self.lblMAPeriodShort.setObjectName("lblMAPeriodShort")
        self.horizontalLayout_11.addWidget(self.lblMAPeriodShort)
        self.spbMAPeriodShort = QtWidgets.QSpinBox(TradeSimulator)
        self.spbMAPeriodShort.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMAPeriodShort.setFont(font)
        self.spbMAPeriodShort.setMinimum(3)
        self.spbMAPeriodShort.setMaximum(20)
        self.spbMAPeriodShort.setSingleStep(1)
        self.spbMAPeriodShort.setProperty("value", 5)
        self.spbMAPeriodShort.setObjectName("spbMAPeriodShort")
        self.horizontalLayout_11.addWidget(self.spbMAPeriodShort)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblMAPeriodLong = QtWidgets.QLabel(TradeSimulator)
        self.lblMAPeriodLong.setObjectName("lblMAPeriodLong")
        self.horizontalLayout_14.addWidget(self.lblMAPeriodLong)
        self.spbMAPeriodLong = QtWidgets.QSpinBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMAPeriodLong.setFont(font)
        self.spbMAPeriodLong.setMinimum(10)
        self.spbMAPeriodLong.setMaximum(250)
        self.spbMAPeriodLong.setSingleStep(1)
        self.spbMAPeriodLong.setProperty("value", 20)
        self.spbMAPeriodLong.setObjectName("spbMAPeriodLong")
        self.horizontalLayout_14.addWidget(self.spbMAPeriodLong)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_28.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.grpUpTrendStrategy = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpUpTrendStrategy.setFont(font)
        self.grpUpTrendStrategy.setObjectName("grpUpTrendStrategy")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpUpTrendStrategy)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxUpTrendBuyByPercent = QtWidgets.QCheckBox(self.grpUpTrendStrategy)
        self.cbxUpTrendBuyByPercent.setChecked(True)
        self.cbxUpTrendBuyByPercent.setObjectName("cbxUpTrendBuyByPercent")
        self.horizontalLayout_3.addWidget(self.cbxUpTrendBuyByPercent)
        self.spbUpTrendBuyPoint = QtWidgets.QDoubleSpinBox(self.grpUpTrendStrategy)
        self.spbUpTrendBuyPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendBuyPoint.setFont(font)
        self.spbUpTrendBuyPoint.setDecimals(1)
        self.spbUpTrendBuyPoint.setMinimum(-20.0)
        self.spbUpTrendBuyPoint.setMaximum(0.0)
        self.spbUpTrendBuyPoint.setSingleStep(0.1)
        self.spbUpTrendBuyPoint.setProperty("value", -2.0)
        self.spbUpTrendBuyPoint.setObjectName("spbUpTrendBuyPoint")
        self.horizontalLayout_3.addWidget(self.spbUpTrendBuyPoint)
        self.lblUpTrendBuyByPercent = QtWidgets.QLabel(self.grpUpTrendStrategy)
        self.lblUpTrendBuyByPercent.setObjectName("lblUpTrendBuyByPercent")
        self.horizontalLayout_3.addWidget(self.lblUpTrendBuyByPercent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cbxUpTrendSellByPercent = QtWidgets.QCheckBox(self.grpUpTrendStrategy)
        self.cbxUpTrendSellByPercent.setChecked(True)
        self.cbxUpTrendSellByPercent.setObjectName("cbxUpTrendSellByPercent")
        self.horizontalLayout_15.addWidget(self.cbxUpTrendSellByPercent)
        self.spbUpTrendSellPoint = QtWidgets.QDoubleSpinBox(self.grpUpTrendStrategy)
        self.spbUpTrendSellPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendSellPoint.setFont(font)
        self.spbUpTrendSellPoint.setDecimals(1)
        self.spbUpTrendSellPoint.setMinimum(0.0)
        self.spbUpTrendSellPoint.setMaximum(20.0)
        self.spbUpTrendSellPoint.setSingleStep(0.1)
        self.spbUpTrendSellPoint.setProperty("value", 5.0)
        self.spbUpTrendSellPoint.setObjectName("spbUpTrendSellPoint")
        self.horizontalLayout_15.addWidget(self.spbUpTrendSellPoint)
        self.lblUpTrendSellByPercent = QtWidgets.QLabel(self.grpUpTrendStrategy)
        self.lblUpTrendSellByPercent.setObjectName("lblUpTrendSellByPercent")
        self.horizontalLayout_15.addWidget(self.lblUpTrendSellByPercent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.cbxUpTrendBuyByMA5 = QtWidgets.QCheckBox(self.grpUpTrendStrategy)
        self.cbxUpTrendBuyByMA5.setChecked(True)
        self.cbxUpTrendBuyByMA5.setObjectName("cbxUpTrendBuyByMA5")
        self.verticalLayout_3.addWidget(self.cbxUpTrendBuyByMA5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cbxUpTrendSellByMA5 = QtWidgets.QCheckBox(self.grpUpTrendStrategy)
        self.cbxUpTrendSellByMA5.setChecked(True)
        self.cbxUpTrendSellByMA5.setObjectName("cbxUpTrendSellByMA5")
        self.horizontalLayout_13.addWidget(self.cbxUpTrendSellByMA5)
        self.spbUpTrendMA5SellThreshold = QtWidgets.QDoubleSpinBox(self.grpUpTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendMA5SellThreshold.setFont(font)
        self.spbUpTrendMA5SellThreshold.setDecimals(1)
        self.spbUpTrendMA5SellThreshold.setMinimum(5.0)
        self.spbUpTrendMA5SellThreshold.setMaximum(20.0)
        self.spbUpTrendMA5SellThreshold.setSingleStep(0.1)
        self.spbUpTrendMA5SellThreshold.setProperty("value", 10.0)
        self.spbUpTrendMA5SellThreshold.setObjectName("spbUpTrendMA5SellThreshold")
        self.horizontalLayout_13.addWidget(self.spbUpTrendMA5SellThreshold)
        self.lblUpTrendSellByMA5 = QtWidgets.QLabel(self.grpUpTrendStrategy)
        self.lblUpTrendSellByMA5.setObjectName("lblUpTrendSellByMA5")
        self.horizontalLayout_13.addWidget(self.lblUpTrendSellByMA5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxUpTrendSameDayTrade = QtWidgets.QCheckBox(self.grpUpTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxUpTrendSameDayTrade.setFont(font)
        self.cbxUpTrendSameDayTrade.setChecked(True)
        self.cbxUpTrendSameDayTrade.setObjectName("cbxUpTrendSameDayTrade")
        self.horizontalLayout_9.addWidget(self.cbxUpTrendSameDayTrade)
        self.spbUpTrendSameDayProfit = QtWidgets.QDoubleSpinBox(self.grpUpTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbUpTrendSameDayProfit.setFont(font)
        self.spbUpTrendSameDayProfit.setDecimals(1)
        self.spbUpTrendSameDayProfit.setMinimum(0.0)
        self.spbUpTrendSameDayProfit.setMaximum(20.0)
        self.spbUpTrendSameDayProfit.setSingleStep(0.1)
        self.spbUpTrendSameDayProfit.setProperty("value", 2.0)
        self.spbUpTrendSameDayProfit.setObjectName("spbUpTrendSameDayProfit")
        self.horizontalLayout_9.addWidget(self.spbUpTrendSameDayProfit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_27.addWidget(self.grpUpTrendStrategy)
        self.grpDownTrendStrategy = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpDownTrendStrategy.setFont(font)
        self.grpDownTrendStrategy.setObjectName("grpDownTrendStrategy")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grpDownTrendStrategy)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxDownTrendBuyByPercent = QtWidgets.QCheckBox(self.grpDownTrendStrategy)
        self.cbxDownTrendBuyByPercent.setChecked(True)
        self.cbxDownTrendBuyByPercent.setObjectName("cbxDownTrendBuyByPercent")
        self.horizontalLayout_4.addWidget(self.cbxDownTrendBuyByPercent)
        self.spbDownTrendBuyPoint = QtWidgets.QDoubleSpinBox(self.grpDownTrendStrategy)
        self.spbDownTrendBuyPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendBuyPoint.setFont(font)
        self.spbDownTrendBuyPoint.setDecimals(1)
        self.spbDownTrendBuyPoint.setMinimum(-20.0)
        self.spbDownTrendBuyPoint.setMaximum(0.0)
        self.spbDownTrendBuyPoint.setSingleStep(0.1)
        self.spbDownTrendBuyPoint.setProperty("value", -4.0)
        self.spbDownTrendBuyPoint.setObjectName("spbDownTrendBuyPoint")
        self.horizontalLayout_4.addWidget(self.spbDownTrendBuyPoint)
        self.lblDownTrendBuyByPercent = QtWidgets.QLabel(self.grpDownTrendStrategy)
        self.lblDownTrendBuyByPercent.setObjectName("lblDownTrendBuyByPercent")
        self.horizontalLayout_4.addWidget(self.lblDownTrendBuyByPercent)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cbxDownTrendSellByPercent = QtWidgets.QCheckBox(self.grpDownTrendStrategy)
        self.cbxDownTrendSellByPercent.setChecked(True)
        self.cbxDownTrendSellByPercent.setObjectName("cbxDownTrendSellByPercent")
        self.horizontalLayout_16.addWidget(self.cbxDownTrendSellByPercent)
        self.spbDownTrendSellPoint = QtWidgets.QDoubleSpinBox(self.grpDownTrendStrategy)
        self.spbDownTrendSellPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendSellPoint.setFont(font)
        self.spbDownTrendSellPoint.setDecimals(1)
        self.spbDownTrendSellPoint.setMinimum(0.0)
        self.spbDownTrendSellPoint.setMaximum(20.0)
        self.spbDownTrendSellPoint.setSingleStep(0.1)
        self.spbDownTrendSellPoint.setProperty("value", 3.0)
        self.spbDownTrendSellPoint.setObjectName("spbDownTrendSellPoint")
        self.horizontalLayout_16.addWidget(self.spbDownTrendSellPoint)
        self.lblDownTrendSellByPercent = QtWidgets.QLabel(self.grpDownTrendStrategy)
        self.lblDownTrendSellByPercent.setObjectName("lblDownTrendSellByPercent")
        self.horizontalLayout_16.addWidget(self.lblDownTrendSellByPercent)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.cbxDownTrendSellByMA5 = QtWidgets.QCheckBox(self.grpDownTrendStrategy)
        self.cbxDownTrendSellByMA5.setChecked(True)
        self.cbxDownTrendSellByMA5.setObjectName("cbxDownTrendSellByMA5")
        self.verticalLayout_6.addWidget(self.cbxDownTrendSellByMA5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cbxDownTrendBuyByMA5 = QtWidgets.QCheckBox(self.grpDownTrendStrategy)
        self.cbxDownTrendBuyByMA5.setChecked(True)
        self.cbxDownTrendBuyByMA5.setObjectName("cbxDownTrendBuyByMA5")
        self.horizontalLayout_17.addWidget(self.cbxDownTrendBuyByMA5)
        self.spbDownTrendMA5BuyThreshold = QtWidgets.QDoubleSpinBox(self.grpDownTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendMA5BuyThreshold.setFont(font)
        self.spbDownTrendMA5BuyThreshold.setDecimals(1)
        self.spbDownTrendMA5BuyThreshold.setMinimum(-20.0)
        self.spbDownTrendMA5BuyThreshold.setMaximum(-5.0)
        self.spbDownTrendMA5BuyThreshold.setSingleStep(0.1)
        self.spbDownTrendMA5BuyThreshold.setProperty("value", -8.0)
        self.spbDownTrendMA5BuyThreshold.setObjectName("spbDownTrendMA5BuyThreshold")
        self.horizontalLayout_17.addWidget(self.spbDownTrendMA5BuyThreshold)
        self.lblUpTrendBuyByMA5 = QtWidgets.QLabel(self.grpDownTrendStrategy)
        self.lblUpTrendBuyByMA5.setObjectName("lblUpTrendBuyByMA5")
        self.horizontalLayout_17.addWidget(self.lblUpTrendBuyByMA5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.cbxDownTrendSameDayTrade = QtWidgets.QCheckBox(self.grpDownTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxDownTrendSameDayTrade.setFont(font)
        self.cbxDownTrendSameDayTrade.setChecked(True)
        self.cbxDownTrendSameDayTrade.setObjectName("cbxDownTrendSameDayTrade")
        self.horizontalLayout_22.addWidget(self.cbxDownTrendSameDayTrade)
        self.spbDownTrendSameDayProfit = QtWidgets.QDoubleSpinBox(self.grpDownTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbDownTrendSameDayProfit.setFont(font)
        self.spbDownTrendSameDayProfit.setDecimals(1)
        self.spbDownTrendSameDayProfit.setMinimum(0.0)
        self.spbDownTrendSameDayProfit.setMaximum(20.0)
        self.spbDownTrendSameDayProfit.setSingleStep(0.1)
        self.spbDownTrendSameDayProfit.setProperty("value", 2.0)
        self.spbDownTrendSameDayProfit.setObjectName("spbDownTrendSameDayProfit")
        self.horizontalLayout_22.addWidget(self.spbDownTrendSameDayProfit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_27.addWidget(self.grpDownTrendStrategy)
        self.grpFlatTrendStrategy = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpFlatTrendStrategy.setFont(font)
        self.grpFlatTrendStrategy.setObjectName("grpFlatTrendStrategy")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grpFlatTrendStrategy)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.cbxFlatTrendBuyByPercent = QtWidgets.QCheckBox(self.grpFlatTrendStrategy)
        self.cbxFlatTrendBuyByPercent.setChecked(True)
        self.cbxFlatTrendBuyByPercent.setObjectName("cbxFlatTrendBuyByPercent")
        self.horizontalLayout_23.addWidget(self.cbxFlatTrendBuyByPercent)
        self.spbFlatTrendBuyPoint = QtWidgets.QDoubleSpinBox(self.grpFlatTrendStrategy)
        self.spbFlatTrendBuyPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbFlatTrendBuyPoint.setFont(font)
        self.spbFlatTrendBuyPoint.setDecimals(1)
        self.spbFlatTrendBuyPoint.setMinimum(-20.0)
        self.spbFlatTrendBuyPoint.setMaximum(0.0)
        self.spbFlatTrendBuyPoint.setSingleStep(0.1)
        self.spbFlatTrendBuyPoint.setProperty("value", -3.0)
        self.spbFlatTrendBuyPoint.setObjectName("spbFlatTrendBuyPoint")
        self.horizontalLayout_23.addWidget(self.spbFlatTrendBuyPoint)
        self.lblFlatTrendBuyByPercent = QtWidgets.QLabel(self.grpFlatTrendStrategy)
        self.lblFlatTrendBuyByPercent.setObjectName("lblFlatTrendBuyByPercent")
        self.horizontalLayout_23.addWidget(self.lblFlatTrendBuyByPercent)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.cbxFlatTrendSellByPercent = QtWidgets.QCheckBox(self.grpFlatTrendStrategy)
        self.cbxFlatTrendSellByPercent.setChecked(True)
        self.cbxFlatTrendSellByPercent.setObjectName("cbxFlatTrendSellByPercent")
        self.horizontalLayout_24.addWidget(self.cbxFlatTrendSellByPercent)
        self.spbFlatTrendSellPoint = QtWidgets.QDoubleSpinBox(self.grpFlatTrendStrategy)
        self.spbFlatTrendSellPoint.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbFlatTrendSellPoint.setFont(font)
        self.spbFlatTrendSellPoint.setDecimals(1)
        self.spbFlatTrendSellPoint.setMinimum(0.0)
        self.spbFlatTrendSellPoint.setMaximum(20.0)
        self.spbFlatTrendSellPoint.setSingleStep(0.1)
        self.spbFlatTrendSellPoint.setProperty("value", 4.0)
        self.spbFlatTrendSellPoint.setObjectName("spbFlatTrendSellPoint")
        self.horizontalLayout_24.addWidget(self.spbFlatTrendSellPoint)
        self.lblFlatTrendSellByPercent = QtWidgets.QLabel(self.grpFlatTrendStrategy)
        self.lblFlatTrendSellByPercent.setObjectName("lblFlatTrendSellByPercent")
        self.horizontalLayout_24.addWidget(self.lblFlatTrendSellByPercent)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.cbxFlatTrendBuyByBOLL = QtWidgets.QCheckBox(self.grpFlatTrendStrategy)
        self.cbxFlatTrendBuyByBOLL.setChecked(True)
        self.cbxFlatTrendBuyByBOLL.setObjectName("cbxFlatTrendBuyByBOLL")
        self.verticalLayout_7.addWidget(self.cbxFlatTrendBuyByBOLL)
        self.cbxFlatTrendSellByBOLL = QtWidgets.QCheckBox(self.grpFlatTrendStrategy)
        self.cbxFlatTrendSellByBOLL.setChecked(True)
        self.cbxFlatTrendSellByBOLL.setObjectName("cbxFlatTrendSellByBOLL")
        self.verticalLayout_7.addWidget(self.cbxFlatTrendSellByBOLL)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.cbxFlatTrendSameDayTrade = QtWidgets.QCheckBox(self.grpFlatTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.cbxFlatTrendSameDayTrade.setFont(font)
        self.cbxFlatTrendSameDayTrade.setChecked(True)
        self.cbxFlatTrendSameDayTrade.setObjectName("cbxFlatTrendSameDayTrade")
        self.horizontalLayout_26.addWidget(self.cbxFlatTrendSameDayTrade)
        self.spbFlatTrendSameDayProfit = QtWidgets.QDoubleSpinBox(self.grpFlatTrendStrategy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbFlatTrendSameDayProfit.setFont(font)
        self.spbFlatTrendSameDayProfit.setDecimals(1)
        self.spbFlatTrendSameDayProfit.setMinimum(0.0)
        self.spbFlatTrendSameDayProfit.setMaximum(20.0)
        self.spbFlatTrendSameDayProfit.setSingleStep(0.1)
        self.spbFlatTrendSameDayProfit.setProperty("value", 3.0)
        self.spbFlatTrendSameDayProfit.setObjectName("spbFlatTrendSameDayProfit")
        self.horizontalLayout_26.addWidget(self.spbFlatTrendSameDayProfit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27.addWidget(self.grpFlatTrendStrategy)
        self.grpShareAllowed = QtWidgets.QGroupBox(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.grpShareAllowed.setFont(font)
        self.grpShareAllowed.setObjectName("grpShareAllowed")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpShareAllowed)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblSharePerTrade = QtWidgets.QLabel(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblSharePerTrade.setFont(font)
        self.lblSharePerTrade.setObjectName("lblSharePerTrade")
        self.horizontalLayout_6.addWidget(self.lblSharePerTrade)
        self.spbMoneyPerTrade = QtWidgets.QSpinBox(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMoneyPerTrade.setFont(font)
        self.spbMoneyPerTrade.setMinimum(1000)
        self.spbMoneyPerTrade.setMaximum(1000000)
        self.spbMoneyPerTrade.setSingleStep(1000)
        self.spbMoneyPerTrade.setProperty("value", 35000)
        self.spbMoneyPerTrade.setObjectName("spbMoneyPerTrade")
        self.horizontalLayout_6.addWidget(self.spbMoneyPerTrade)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblInitialShare = QtWidgets.QLabel(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblInitialShare.setFont(font)
        self.lblInitialShare.setObjectName("lblInitialShare")
        self.horizontalLayout_5.addWidget(self.lblInitialShare)
        self.spbInitialInvestment = QtWidgets.QSpinBox(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbInitialInvestment.setFont(font)
        self.spbInitialInvestment.setMinimum(1)
        self.spbInitialInvestment.setMaximum(5)
        self.spbInitialInvestment.setSingleStep(1)
        self.spbInitialInvestment.setProperty("value", 1)
        self.spbInitialInvestment.setObjectName("spbInitialInvestment")
        self.horizontalLayout_5.addWidget(self.spbInitialInvestment)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblMaxShare = QtWidgets.QLabel(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMaxShare.setFont(font)
        self.lblMaxShare.setObjectName("lblMaxShare")
        self.horizontalLayout_7.addWidget(self.lblMaxShare)
        self.spbMaxHolding = QtWidgets.QSpinBox(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMaxHolding.setFont(font)
        self.spbMaxHolding.setMinimum(2)
        self.spbMaxHolding.setMaximum(10)
        self.spbMaxHolding.setSingleStep(1)
        self.spbMaxHolding.setProperty("value", 3)
        self.spbMaxHolding.setObjectName("spbMaxHolding")
        self.horizontalLayout_7.addWidget(self.spbMaxHolding)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblMinShare = QtWidgets.QLabel(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblMinShare.setFont(font)
        self.lblMinShare.setObjectName("lblMinShare")
        self.horizontalLayout_8.addWidget(self.lblMinShare)
        self.spbMinHolding = QtWidgets.QSpinBox(self.grpShareAllowed)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.spbMinHolding.setFont(font)
        self.spbMinHolding.setMinimum(0)
        self.spbMinHolding.setMaximum(5)
        self.spbMinHolding.setSingleStep(1)
        self.spbMinHolding.setProperty("value", 1)
        self.spbMinHolding.setObjectName("spbMinHolding")
        self.horizontalLayout_8.addWidget(self.spbMinHolding)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_27.addWidget(self.grpShareAllowed)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lblStockNumber = QtWidgets.QLabel(TradeSimulator)
        self.lblStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStockNumber.setFont(font)
        self.lblStockNumber.setObjectName("lblStockNumber")
        self.horizontalLayout_12.addWidget(self.lblStockNumber)
        self.iptStockNumber = QtWidgets.QLineEdit(TradeSimulator)
        self.iptStockNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.iptStockNumber.setFont(font)
        self.iptStockNumber.setMaxLength(6)
        self.iptStockNumber.setObjectName("iptStockNumber")
        self.horizontalLayout_12.addWidget(self.iptStockNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblStartDate = QtWidgets.QLabel(TradeSimulator)
        self.lblStartDate.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.horizontalLayout.addWidget(self.lblStartDate)
        self.dteStart = QtWidgets.QDateEdit(TradeSimulator)
        self.dteStart.setSpecialValueText("")
        self.dteStart.setObjectName("dteStart")
        self.horizontalLayout.addWidget(self.dteStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lblEndDate = QtWidgets.QLabel(TradeSimulator)
        self.lblEndDate.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.lblEndDate.setFont(font)
        self.lblEndDate.setObjectName("lblEndDate")
        self.horizontalLayout_25.addWidget(self.lblEndDate)
        self.dteEnd = QtWidgets.QDateEdit(TradeSimulator)
        self.dteEnd.setSpecialValueText("")
        self.dteEnd.setObjectName("dteEnd")
        self.horizontalLayout_25.addWidget(self.dteEnd)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.btnStartTrading = QtWidgets.QPushButton(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartTrading.setFont(font)
        self.btnStartTrading.setObjectName("btnStartTrading")
        self.verticalLayout.addWidget(self.btnStartTrading)
        self.btnShowDiagram = QtWidgets.QPushButton(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnShowDiagram.setFont(font)
        self.btnShowDiagram.setObjectName("btnShowDiagram")
        self.verticalLayout.addWidget(self.btnShowDiagram)
        self.horizontalLayout_27.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.tblTradeHistory = QtWidgets.QTableWidget(TradeSimulator)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.tblTradeHistory.setFont(font)
        self.tblTradeHistory.setRowCount(0)
        self.tblTradeHistory.setColumnCount(13)
        self.tblTradeHistory.setObjectName("tblTradeHistory")
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTradeHistory.setHorizontalHeaderItem(12, item)
        self.tblTradeHistory.horizontalHeader().setDefaultSectionSize(70)
        self.tblTradeHistory.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_11.addWidget(self.tblTradeHistory)

        self.retranslateUi(TradeSimulator)
        self.cbxUpTrendSameDayTrade.toggled['bool'].connect(self.spbUpTrendSameDayProfit.setEnabled)
        self.rbnUpTrendStartByMAStay.toggled['bool'].connect(self.spbUpTrendStartMAStayDays.setEnabled)
        self.rbnDownTrendStartByMaBreak.toggled['bool'].connect(self.spbDownTrendStartMABreakDays.setEnabled)
        self.cbxUpTrendSellByMA5.toggled['bool'].connect(self.spbUpTrendMA5SellThreshold.setEnabled)
        self.cbxUpTrendSellByPercent.toggled['bool'].connect(self.spbUpTrendSellPoint.setEnabled)
        self.cbxUpTrendBuyByPercent.toggled['bool'].connect(self.spbUpTrendBuyPoint.setEnabled)
        self.cbxDownTrendBuyByPercent.toggled['bool'].connect(self.spbDownTrendBuyPoint.setEnabled)
        self.cbxDownTrendSellByPercent.toggled['bool'].connect(self.spbDownTrendSellPoint.setEnabled)
        self.cbxDownTrendBuyByMA5.toggled['bool'].connect(self.spbDownTrendMA5BuyThreshold.setEnabled)
        self.cbxDownTrendSameDayTrade.toggled['bool'].connect(self.spbDownTrendSameDayProfit.setEnabled)
        self.cbxFlatTrendBuyByPercent.toggled['bool'].connect(self.spbFlatTrendBuyPoint.setEnabled)
        self.cbxFlatTrendSellByPercent.toggled['bool'].connect(self.spbFlatTrendSellPoint.setEnabled)
        self.cbxFlatTrendSameDayTrade.toggled['bool'].connect(self.spbFlatTrendSameDayProfit.setEnabled)
        self.rbnUpTrendEndByMaBreak.toggled['bool'].connect(self.spbUpTrendEndMABreakDays.setEnabled)
        self.rbnUpTrendEndByMacd.toggled['bool'].connect(self.spbUpTrendEndMACDFallDays.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TradeSimulator)

    def retranslateUi(self, TradeSimulator):
        _translate = QtCore.QCoreApplication.translate
        TradeSimulator.setWindowTitle(_translate("TradeSimulator", "模拟交易回测"))
        self.grpUpTrendStartSignal.setTitle(_translate("TradeSimulator", "上升趋势开始信号"))
        self.rbnUpTrendStartByMACD.setText(_translate("TradeSimulator", "MACD金叉"))
        self.rbnUpTrendStartByMAStay.setText(_translate("TradeSimulator", "站稳长期均线"))
        self.spbUpTrendStartMAStayDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnUpTrendStartByMACross.setText(_translate("TradeSimulator", "长短期均线金叉"))
        self.grpUpTrendEndSignal.setTitle(_translate("TradeSimulator", "上升趋势结束信号"))
        self.rbnUpTrendEndByMacd.setText(_translate("TradeSimulator", "MACD红柱连续缩短"))
        self.spbUpTrendEndMACDFallDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnUpTrendEndByMaBreak.setText(_translate("TradeSimulator", "失守短期均线"))
        self.spbUpTrendEndMABreakDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnUpTrendEndByNoHighAgain.setText(_translate("TradeSimulator", "连续"))
        self.spbUpTrendEndNoHighDays.setSuffix(_translate("TradeSimulator", "日"))
        self.lblUpTrendEndByNoHighAgain.setText(_translate("TradeSimulator", "不再创新高"))
        self.grpDownTrendStartSignal.setTitle(_translate("TradeSimulator", "下降趋势开始信号"))
        self.rbnDownTrendStartByMACD.setText(_translate("TradeSimulator", "MACD死叉"))
        self.rbnDownTrendStartByMaBreak.setText(_translate("TradeSimulator", "失守长期均线"))
        self.spbDownTrendStartMABreakDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnDownTrendStartByMACross.setText(_translate("TradeSimulator", "长短期均线死叉"))
        self.grpDownTrendEndSignal.setTitle(_translate("TradeSimulator", "下降趋势结束信号"))
        self.rbnDownTrendEndByMacd.setText(_translate("TradeSimulator", "MACD绿柱连续缩短"))
        self.spbDownTrendEndMACDRiseDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnDownTrendEndByMAStay.setText(_translate("TradeSimulator", "站稳短期均线"))
        self.spbDownTrendEndMAStayDays.setSuffix(_translate("TradeSimulator", "日"))
        self.rbnDownTrendEndByNoLowAgain.setText(_translate("TradeSimulator", "连续"))
        self.spbDownTrendEndNoLowDays.setSuffix(_translate("TradeSimulator", "日"))
        self.lblDownTrendEndByNoLowAgain.setText(_translate("TradeSimulator", "不再创新低"))
        self.lblMAPeriodShort.setText(_translate("TradeSimulator", "短期均线时长"))
        self.spbMAPeriodShort.setSuffix(_translate("TradeSimulator", "日"))
        self.lblMAPeriodLong.setText(_translate("TradeSimulator", "长期均线时长"))
        self.spbMAPeriodLong.setSuffix(_translate("TradeSimulator", "日"))
        self.grpUpTrendStrategy.setTitle(_translate("TradeSimulator", "上升趋势操作方法"))
        self.cbxUpTrendBuyByPercent.setText(_translate("TradeSimulator", "下跌达到"))
        self.spbUpTrendBuyPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblUpTrendBuyByPercent.setText(_translate("TradeSimulator", "买入"))
        self.cbxUpTrendSellByPercent.setText(_translate("TradeSimulator", "上涨达到"))
        self.spbUpTrendSellPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblUpTrendSellByPercent.setText(_translate("TradeSimulator", "卖出"))
        self.cbxUpTrendBuyByMA5.setText(_translate("TradeSimulator", "回调至五日均线买入"))
        self.cbxUpTrendSellByMA5.setText(_translate("TradeSimulator", "偏离五日均线"))
        self.spbUpTrendMA5SellThreshold.setSuffix(_translate("TradeSimulator", "%"))
        self.lblUpTrendSellByMA5.setText(_translate("TradeSimulator", "减仓"))
        self.cbxUpTrendSameDayTrade.setText(_translate("TradeSimulator", "日内做T 预期收益"))
        self.spbUpTrendSameDayProfit.setSuffix(_translate("TradeSimulator", "%"))
        self.grpDownTrendStrategy.setTitle(_translate("TradeSimulator", "下降趋势操作方法"))
        self.cbxDownTrendBuyByPercent.setText(_translate("TradeSimulator", "下跌达到"))
        self.spbDownTrendBuyPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblDownTrendBuyByPercent.setText(_translate("TradeSimulator", "买入"))
        self.cbxDownTrendSellByPercent.setText(_translate("TradeSimulator", "上涨达到"))
        self.spbDownTrendSellPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblDownTrendSellByPercent.setText(_translate("TradeSimulator", "卖出"))
        self.cbxDownTrendSellByMA5.setText(_translate("TradeSimulator", "反弹至五日均线卖出"))
        self.cbxDownTrendBuyByMA5.setText(_translate("TradeSimulator", "偏离五日均线"))
        self.spbDownTrendMA5BuyThreshold.setSuffix(_translate("TradeSimulator", "%"))
        self.lblUpTrendBuyByMA5.setText(_translate("TradeSimulator", "补仓"))
        self.cbxDownTrendSameDayTrade.setText(_translate("TradeSimulator", "日内做T 预期收益"))
        self.spbDownTrendSameDayProfit.setSuffix(_translate("TradeSimulator", "%"))
        self.grpFlatTrendStrategy.setTitle(_translate("TradeSimulator", "震荡趋势操作方法"))
        self.cbxFlatTrendBuyByPercent.setText(_translate("TradeSimulator", "下跌达到"))
        self.spbFlatTrendBuyPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblFlatTrendBuyByPercent.setText(_translate("TradeSimulator", "买入"))
        self.cbxFlatTrendSellByPercent.setText(_translate("TradeSimulator", "上涨达到"))
        self.spbFlatTrendSellPoint.setSuffix(_translate("TradeSimulator", "%"))
        self.lblFlatTrendSellByPercent.setText(_translate("TradeSimulator", "卖出"))
        self.cbxFlatTrendBuyByBOLL.setText(_translate("TradeSimulator", "布林线下轨买入"))
        self.cbxFlatTrendSellByBOLL.setText(_translate("TradeSimulator", "布林线上轨卖出"))
        self.cbxFlatTrendSameDayTrade.setText(_translate("TradeSimulator", "日内做T 预期收益"))
        self.spbFlatTrendSameDayProfit.setSuffix(_translate("TradeSimulator", "%"))
        self.grpShareAllowed.setTitle(_translate("TradeSimulator", "仓位控制"))
        self.lblSharePerTrade.setText(_translate("TradeSimulator", "每份价值"))
        self.spbMoneyPerTrade.setSuffix(_translate("TradeSimulator", "元"))
        self.lblInitialShare.setText(_translate("TradeSimulator", "初始底仓"))
        self.spbInitialInvestment.setSuffix(_translate("TradeSimulator", "份"))
        self.lblMaxShare.setText(_translate("TradeSimulator", "最大持仓"))
        self.spbMaxHolding.setSuffix(_translate("TradeSimulator", "份"))
        self.lblMinShare.setText(_translate("TradeSimulator", "最小持仓"))
        self.spbMinHolding.setSuffix(_translate("TradeSimulator", "份"))
        self.lblStockNumber.setText(_translate("TradeSimulator", "股票代码/名称"))
        self.iptStockNumber.setText(_translate("TradeSimulator", "贵州茅台"))
        self.lblStartDate.setText(_translate("TradeSimulator", "开始日期"))
        self.dteStart.setDisplayFormat(_translate("TradeSimulator", "yyyy-MM-dd"))
        self.lblEndDate.setText(_translate("TradeSimulator", "结束日期"))
        self.dteEnd.setDisplayFormat(_translate("TradeSimulator", "yyyy-MM-dd"))
        self.btnStartTrading.setText(_translate("TradeSimulator", "开始模拟交易回测"))
        self.btnShowDiagram.setText(_translate("TradeSimulator", "显示K线图"))
        item = self.tblTradeHistory.horizontalHeaderItem(0)
        item.setText(_translate("TradeSimulator", "交易时间"))
        item = self.tblTradeHistory.horizontalHeaderItem(1)
        item.setText(_translate("TradeSimulator", "交易操作"))
        item = self.tblTradeHistory.horizontalHeaderItem(2)
        item.setText(_translate("TradeSimulator", "成交价格"))
        item = self.tblTradeHistory.horizontalHeaderItem(3)
        item.setText(_translate("TradeSimulator", "成交数量"))
        item = self.tblTradeHistory.horizontalHeaderItem(4)
        item.setText(_translate("TradeSimulator", "持仓股数"))
        item = self.tblTradeHistory.horizontalHeaderItem(5)
        item.setText(_translate("TradeSimulator", "当日开盘"))
        item = self.tblTradeHistory.horizontalHeaderItem(6)
        item.setText(_translate("TradeSimulator", "当日最高"))
        item = self.tblTradeHistory.horizontalHeaderItem(7)
        item.setText(_translate("TradeSimulator", "当日最低"))
        item = self.tblTradeHistory.horizontalHeaderItem(8)
        item.setText(_translate("TradeSimulator", "当日收盘"))
        item = self.tblTradeHistory.horizontalHeaderItem(9)
        item.setText(_translate("TradeSimulator", "当日换手"))
        item = self.tblTradeHistory.horizontalHeaderItem(10)
        item.setText(_translate("TradeSimulator", "平均成本"))
        item = self.tblTradeHistory.horizontalHeaderItem(11)
        item.setText(_translate("TradeSimulator", "累计收益"))
        item = self.tblTradeHistory.horizontalHeaderItem(12)
        item.setText(_translate("TradeSimulator", "盈亏比例"))
